/* ================= FISICA: SPIEGAZIONI, ESEMPI SVOLTI, COLLEGAMENTI MEDICI =================
   Per ogni argomento: sp = spiegazione (paragrafi), es = esempi svolti {q domanda, p passaggi, r risultato},
   med = dove si incontra in medicina. Si aggiungono agli argomenti di FIS_TOPICS al caricamento. */
const FIS_EXPL={
/* ---------- Unità 1 · Metodi della fisica ---------- */
u1a:{sp:["Una grandezza fisica è qualcosa che si può misurare: si scrive sempre come numero + unità di misura. «3» non vuol dire nulla, «3 m» sì. Il Sistema Internazionale (SI) sceglie 7 grandezze fondamentali, con un'unità ciascuna; tutte le altre si ottengono combinandole.",
 "Le unità derivate si ricavano dalle formule. Siccome F = m·a, il newton è kg·m/s². Siccome il lavoro è forza per spostamento, il joule è N·m = kg·m²/s². Così, conoscendo le formule, si ricostruisce qualsiasi unità senza impararla a memoria.",
 "I prefissi sono potenze di 10 che si attaccano all'unità: 1 km = 10³ m, 1 mg = 10⁻³ g, 1 µs = 10⁻⁶ s. Attenzione: il chilogrammo è l'unica unità fondamentale che ha già un prefisso nel nome.",
 "Una grandezza è estensiva se raddoppia raddoppiando la quantità di materia (massa, volume, energia, calore), intensiva se non cambia (temperatura, pressione, densità). Se tagli a metà una mela, la sua massa si dimezza ma la temperatura resta quella."],
 es:[{q:"Scrivi il pascal in unità fondamentali.",p:["Pa = N/m²","N = kg·m/s²","Pa = (kg·m/s²)/m² = kg/(m·s²)"],r:"1 Pa = 1 kg·m⁻¹·s⁻²"},
     {q:"Quanti microgrammi ci sono in 2 mg?",p:["1 mg = 10⁻³ g e 1 µg = 10⁻⁶ g","1 mg = 10³ µg","2 mg = 2·10³ µg"],r:"2000 µg"}],
 med:"Dosaggi dei farmaci in mg o µg, concentrazioni in mg/dL, pressione in mmHg: in reparto le unità non SI sono la norma, per questo la conversione è un'abilità di base."},
u1b:{sp:["Per convertire si moltiplica per un «fattore 1»: una frazione che vale 1 perché sopra e sotto c'è la stessa quantità scritta in unità diverse. Esempio: 1 h / 3600 s = 1. Le unità si semplificano come lettere in algebra.",
 "Le conversioni di aree e volumi sono la trappola più frequente: se 1 cm = 10⁻² m, allora 1 cm² = (10⁻²)² m² = 10⁻⁴ m² e 1 cm³ = 10⁻⁶ m³. L'esponente si moltiplica per 2 o per 3.",
 "La notazione scientifica scrive un numero come a·10ⁿ con 1 ≤ a < 10. Per moltiplicare si moltiplicano le a e si sommano gli esponenti; per dividere si dividono le a e si sottraggono gli esponenti. All'esame non c'è la calcolatrice: lavorare con le potenze di 10 è il modo più veloce e sicuro.",
 "Stimare l'ordine di grandezza (la potenza di 10 più vicina) serve a controllare un risultato: se calcoli che un globulo rosso è largo 7 m, c'è un errore di unità (sono circa 7 µm)."],
 es:[{q:"Converti 108 km/h in m/s.",p:["108 km/h = 108 · 1000 m / 3600 s","= 108 / 3,6 m/s"],r:"30 m/s"},
     {q:"Un flacone contiene 250 mL. Quanti m³ sono?",p:["1 mL = 1 cm³ = 10⁻⁶ m³","250 mL = 250·10⁻⁶ m³"],r:"2,5·10⁻⁴ m³"},
     {q:"Calcola (6·10⁴) · (5·10⁻⁷).",p:["6·5 = 30","10⁴·10⁻⁷ = 10⁻³","30·10⁻³ = 3·10⁻²"],r:"3·10⁻² = 0,03"}],
 med:"Portata cardiaca circa 5 L/min = 8,3·10⁻⁵ m³/s; pressione arteriosa 120 mmHg ≈ 16 kPa: sono le conversioni tipiche dei problemi d'esame."},
u1c:{sp:["Un vettore è una freccia: la lunghezza è il modulo, la retta su cui sta è la direzione, la punta indica il verso. Spostamento, velocità, accelerazione e forza sono vettori; per questo due forze da 3 N non danno sempre 6 N.",
 "Somma con il metodo punta-coda: si mette la coda del secondo vettore sulla punta del primo; la somma va dalla coda del primo alla punta del secondo. È lo stesso della regola del parallelogramma.",
 "Il modo più pratico per sommare vettori è scomporli in componenti: aₓ = a·cos θ e a_y = a·sin θ (θ misurato dall'asse x). Si sommano separatamente le x e le y, poi si ricompone il modulo con Pitagora.",
 "Prodotto scalare a·b = ab·cos θ (dà un numero, serve per il lavoro). Prodotto vettoriale |a×b| = ab·sin θ (dà un vettore perpendicolare a entrambi, serve per la forza di Lorentz e il momento). Se θ = 90° il prodotto scalare è zero; se θ = 0° è zero quello vettoriale."],
 es:[{q:"Una forza di 10 N forma 30° con il pavimento. Quanto valgono le componenti orizzontale e verticale?",p:["Fₓ = 10·cos 30° ≈ 10·0,87","F_y = 10·sin 30° = 10·0,5"],r:"Fₓ ≈ 8,7 N; F_y = 5 N"},
     {q:"Due spostamenti: 6 m verso est e 8 m verso nord. Quanto dista il punto di arrivo?",p:["Sono perpendicolari: uso Pitagora","√(6² + 8²) = √(36 + 64) = √100"],r:"10 m"}],
 med:"In biomeccanica la forza di un muscolo si scompone nella parte che fa ruotare l'articolazione e in quella che la comprime."},
u1d:{sp:["Ogni grandezza ha una «dimensione» scritta con le grandezze fondamentali: [L] lunghezza, [M] massa, [T] tempo. Velocità [L T⁻¹], accelerazione [L T⁻²], forza [M L T⁻²], energia [M L² T⁻²].",
 "Regola d'oro: si possono sommare o uguagliare solo grandezze con le stesse dimensioni. Se una formula dà m/s da una parte e m/s² dall'altra, è sbagliata. È il modo più rapido per scartare risposte nelle domande a scelta multipla.",
 "Una grandezza adimensionale è un rapporto tra grandezze omogenee: le unità si semplificano. Esempi: numero di Reynolds, indice di rifrazione, rendimento, costante dielettrica relativa εᵣ, angoli in radianti, deformazione relativa ΔL/L."],
 es:[{q:"La formula v = √(2gh) è dimensionalmente corretta?",p:["[g·h] = (L T⁻²)·L = L² T⁻²","√(L² T⁻²) = L T⁻¹","È proprio una velocità"],r:"Sì"},
     {q:"Quale grandezza ha dimensioni M L² T⁻³?",p:["Energia = M L² T⁻²","Divisa per un tempo: M L² T⁻³","Energia al secondo = potenza"],r:"La potenza (watt)"}]},
/* ---------- Unità 2 · Meccanica ---------- */
u2a:{sp:["La cinematica descrive il moto senza chiedersi perché avviene. Servono tre grandezze: posizione x, velocità v (quanto cambia x nel tempo) e accelerazione a (quanto cambia v nel tempo).",
 "Moto rettilineo uniforme: v costante, a = 0. Lo spazio cresce in modo lineare, s = v·t; nel grafico x–t è una retta, nel grafico v–t una riga orizzontale.",
 "Moto uniformemente accelerato: a costante. La velocità cresce in modo lineare (v = v₀ + at), lo spazio in modo quadratico (s = v₀t + ½at²): nel grafico x–t è una parabola. La terza formula, v² = v₀² + 2as, non contiene il tempo ed è utilissima quando il tempo non è dato.",
 "La caduta libera è un moto uniformemente accelerato verso il basso con a = g ≈ 9,8 m/s². Senza aria, una piuma e un martello cadono insieme: l'accelerazione non dipende dalla massa.",
 "Velocità media = spazio totale / tempo totale. Non è la media aritmetica delle velocità, a meno che i tempi dei due tratti siano uguali."],
 es:[{q:"Un'auto a 20 m/s frena con decelerazione costante di 5 m/s². In quanto spazio si ferma?",p:["v = 0, v₀ = 20 m/s, a = −5 m/s²","v² = v₀² + 2as → 0 = 400 − 10·s","s = 400/10"],r:"40 m (in 4 s)"},
     {q:"Vai a 60 km/h per 1 ora e torni a 30 km/h sullo stesso percorso. Velocità media?",p:["Andata: 60 km in 1 h; ritorno: 60 km in 2 h","Spazio totale 120 km, tempo totale 3 h","120/3"],r:"40 km/h, non 45"}],
 med:"Lo spazio di frenata cresce con il quadrato della velocità: a velocità doppia serve uno spazio quadruplo (traumatologia stradale)."},
u2b:{sp:["Nel moto parabolico il trucco è separare le due direzioni, che sono indipendenti. In orizzontale non ci sono forze (aria trascurata): vₓ resta costante. In verticale agisce solo g: v_y diminuisce salendo, si annulla in cima e cresce scendendo.",
 "Il tempo di volo dipende solo dal moto verticale. Un proiettile sparato in orizzontale e uno lasciato cadere dalla stessa altezza toccano terra nello stesso istante.",
 "Moto circolare uniforme: il modulo della velocità è costante ma la direzione cambia continuamente, quindi c'è un'accelerazione, diretta verso il centro: aᶜ = v²/r = ω²r. Serve una forza centripeta F = m·v²/r (tensione di una fune, attrito delle gomme, gravità per un satellite).",
 "Periodo T = tempo di un giro; frequenza f = 1/T (giri al secondo); velocità angolare ω = 2π/T; velocità lineare v = ω·r."],
 es:[{q:"Un sasso è lanciato in orizzontale a 10 m/s da un'altezza di 5 m (g = 10). Quanto lontano cade?",p:["Tempo di caduta: 5 = ½·10·t² → t = 1 s","In orizzontale MRU: x = 10·1"],r:"10 m"},
     {q:"Una centrifuga fa girare una provetta a 0,1 m dall'asse con v = 30 m/s. Quanto vale l'accelerazione centripeta?",p:["aᶜ = v²/r = 900/0,1"],r:"9000 m/s², circa 900 g"}],
 med:"La centrifuga separa i componenti del sangue perché l'accelerazione centripeta, migliaia di volte g, fa sedimentare in fretta le particelle più dense."},
u2c:{sp:["Le forze sono la causa dei cambiamenti di moto. Primo principio: se la forza risultante è zero, la velocità non cambia (fermo resta fermo, in moto continua dritto e uniforme). Secondo principio: ΣF = m·a, cioè la forza risultante produce un'accelerazione nella sua direzione. Terzo principio: le forze nascono sempre a coppie uguali e opposte su corpi diversi.",
 "Metodo per ogni problema: disegna il corpo, tutte le forze che agiscono su di esso (peso, normale, tensioni, attriti, molle), scegli gli assi, scrivi ΣF = m·a lungo ciascun asse.",
 "Peso P = m·g (la massa non cambia, il peso sì: sulla Luna è circa 1/6). La forza gravitazionale tra due masse è F = G·m₁m₂/r². La normale N è la spinta del piano d'appoggio, perpendicolare alla superficie: su un piano orizzontale N = mg, su un piano inclinato N = mg·cos θ.",
 "Attrito: quello statico impedisce il moto fino a un valore massimo µₛN; quello dinamico, durante lo scorrimento, vale µ_d N ed è di solito un po' minore. Molla: F = −k·x, la forza è proporzionale all'allungamento e opposta ad esso (legge di Hooke)."],
 es:[{q:"Una cassa di 20 kg è tirata con 100 N su un pavimento con µ_d = 0,3 (g = 10). Quanto vale l'accelerazione?",p:["Attrito: µN = 0,3·20·10 = 60 N","Risultante: 100 − 60 = 40 N","a = 40/20"],r:"2 m/s²"},
     {q:"Su un piano inclinato liscio di 30° scivola un corpo di 4 kg (g = 10). Quanto valgono la normale e l'accelerazione?",p:["N = mg cos 30° = 40·0,87 ≈ 35 N","a = g sin 30° = 10·0,5"],r:"N ≈ 35 N; a = 5 m/s²"}],
 med:"Nella trazione ortopedica un peso appeso a una carrucola esercita una tensione costante sull'arto: è il secondo principio in equilibrio."},
u2d:{sp:["Il lavoro misura quanta energia una forza trasferisce a un corpo: L = F·s·cos θ. Se la forza aiuta il moto il lavoro è positivo, se si oppone (attrito, frenata) è negativo, se è perpendicolare (normale, forza centripeta) è nullo.",
 "Energia cinetica Ec = ½mv²: dipende dal quadrato della velocità. Teorema dell'energia cinetica: il lavoro di tutte le forze è uguale alla variazione di Ec.",
 "Le forze conservative (peso, molla, forza elettrica) hanno un'energia potenziale: U = mgh per il peso, U = ½kx² per la molla. Il loro lavoro dipende solo dal punto di partenza e di arrivo, non dal percorso. L'attrito invece è dissipativo: trasforma energia meccanica in calore.",
 "Se agiscono solo forze conservative, l'energia meccanica Ec + U si conserva: quello che perdi in altezza lo guadagni in velocità. È il metodo più rapido per molti esercizi: non serve conoscere la forma del percorso.",
 "Potenza P = L/t: quanto velocemente si fa lavoro. Un kWh è un'energia (potenza per tempo), non una potenza."],
 es:[{q:"Un pendolo parte da fermo 20 cm più in alto del punto più basso. Che velocità ha in fondo? (g = 10)",p:["mgh = ½mv² → v = √(2gh)","v = √(2·10·0,2) = √4"],r:"2 m/s"},
     {q:"Una persona di 60 kg sale 3 m di scale in 6 s. Che potenza sviluppa? (g = 10)",p:["L = mgh = 60·10·3 = 1800 J","P = 1800/6"],r:"300 W"}],
 med:"Il cuore compie circa 1 J di lavoro a battito: con 70 battiti al minuto la sua potenza meccanica è di poco più di 1 W."},
u2e:{sp:["Un corpo rigido non si deforma ma può ruotare. Per farlo ruotare conta il momento torcente M = F·b, dove b è il braccio: la distanza perpendicolare tra la retta d'azione della forza e il fulcro. Per questo una porta si apre facilmente spingendo vicino alla maniglia e a fatica vicino ai cardini.",
 "Equilibrio di un corpo rigido: servono entrambe le condizioni, somma delle forze nulla (non trasla) e somma dei momenti nulla (non ruota). Per le leve la seconda diventa F₁·b₁ = F₂·b₂.",
 "Leve: 1° genere fulcro in mezzo (altalena, forbici, la testa sulla colonna); 2° genere resistenza in mezzo (carriola, sollevarsi sulle punte dei piedi): sempre vantaggiosa; 3° genere potenza in mezzo (pinzette, avambraccio flesso dal bicipite): sempre svantaggiosa, ma il carico si sposta di più e più in fretta.",
 "Il centro di massa è il punto che si muove come se tutta la massa fosse lì: per due masse x_cm = (m₁x₁ + m₂x₂)/(m₁ + m₂), più vicino alla massa maggiore. Un corpo appoggiato è in equilibrio stabile se la verticale del baricentro cade dentro la base d'appoggio."],
 es:[{q:"Il bicipite è attaccato a 4 cm dal gomito; in mano, a 32 cm, c'è un peso di 50 N. Che forza deve fare il bicipite (avambraccio orizzontale, peso dell'avambraccio trascurato)?",p:["Momenti rispetto al gomito: F·0,04 = 50·0,32","F = 16/0,04"],r:"400 N, otto volte il peso"},
     {q:"Due bambini di 20 kg e 30 kg su un'altalena lunga 3 m con fulcro al centro. Dove deve sedersi il più pesante se il leggero sta all'estremità?",p:["Leggero: 20·1,5 = 30 (in kg·m, g si semplifica)","Pesante: 30·b = 30"],r:"a 1 m dal fulcro"}],
 med:"Le forze su muscoli e articolazioni sono molto maggiori dei carichi sollevati: è il motivo delle lesioni da sollevamento con la schiena flessa."},
u2f:{sp:["La quantità di moto p = m·v unisce massa e velocità: un camion lento e un proiettile veloce possono avere la stessa p. È un vettore, con la direzione della velocità.",
 "Il secondo principio si può scrivere F = Δp/Δt. Da qui il teorema dell'impulso: F·Δt = Δp. A parità di variazione di quantità di moto, allungare il tempo dell'urto riduce la forza: è il principio di airbag, caschi, ginocchia piegate quando si atterra.",
 "In un sistema isolato (forze esterne nulle o trascurabili durante l'urto) la quantità di moto totale si conserva. Vale per urti, esplosioni, rinculo di un'arma.",
 "Urto elastico: si conserva anche l'energia cinetica (biglie da biliardo, idealmente). Urto anelastico: parte dell'energia cinetica diventa calore e deformazione; se i corpi restano attaccati è completamente anelastico e la velocità finale si ricava solo dalla conservazione di p."],
 es:[{q:"Una palla da 0,5 kg arriva a 10 m/s contro un muro e rimbalza a 10 m/s. L'urto dura 0,05 s. Che forza media ha esercitato il muro?",p:["Δp = 0,5·10 − (0,5·(−10)) = 10 kg·m/s","F = Δp/Δt = 10/0,05"],r:"200 N"},
     {q:"Un carrello di 3 kg a 4 m/s urta un carrello fermo di 1 kg e restano uniti. Quanta energia cinetica si perde?",p:["v finale = 3·4/(3+1) = 3 m/s","Ec prima = ½·3·16 = 24 J; dopo = ½·4·9 = 18 J"],r:"6 J (il 25%)"}],
 med:"Nei traumi conta la durata dell'urto: cinture e airbag allungano l'arresto del corpo e riducono le forze sugli organi."},
/* ---------- Unità 3 · Meccanica dei fluidi ---------- */
u3a:{sp:["Un fluido (liquido o gas) non ha forma propria: le sue molecole scorrono. I liquidi sono praticamente incomprimibili, i gas no. Per i fluidi si ragiona con la densità ρ = m/V e la pressione p = F/A invece che con masse e forze.",
 "In un liquido fermo la pressione aumenta con la profondità perché ogni strato regge il peso di quelli sopra: p = p₀ + ρgh (Stevino). Dipende solo da h, non dalla forma del recipiente né dalla quantità di liquido.",
 "Principio di Pascal: un aumento di pressione in un punto di un fluido chiuso si trasmette identico ovunque. Nel torchio idraulico una piccola forza su un pistone piccolo genera una grande forza su un pistone grande (ma il pistone grande si sposta di meno: il lavoro si conserva).",
 "Pressione assoluta = pressione relativa (manometrica) + pressione atmosferica. Torricelli: l'atmosfera regge 760 mm di mercurio (1 atm). Con l'acqua, 13,6 volte meno densa, servirebbero circa 10 m: per questo ogni 10 m di immersione la pressione cresce di circa 1 atm."],
 es:[{q:"Pressione relativa del sangue ai piedi rispetto al cuore in una persona in piedi, con dislivello di 1,3 m (ρ = 1060 kg/m³, g = 10)?",p:["Δp = ρgh = 1060·10·1,3 ≈ 13 800 Pa","In mmHg: 13 800/133"],r:"circa 100 mmHg in più"},
     {q:"Torchio idraulico: pistoni di raggio 1 cm e 10 cm. Quale forza sul piccolo solleva un'auto di 10 000 N?",p:["Le aree stanno come i raggi al quadrato: 1 : 100","F = 10 000/100"],r:"100 N"}],
 med:"Per questo la pressione si misura al braccio, all'altezza del cuore, e una flebo va appesa abbastanza in alto da vincere la pressione venosa."},
u3b:{sp:["Un corpo immerso riceve dal fluido una spinta verso l'alto perché la pressione sotto (più profonda) è maggiore di quella sopra. Il risultato è il principio di Archimede: la spinta è uguale al peso del fluido spostato, S = ρ_fluido·g·V_immerso.",
 "Confronto tra peso e spinta a corpo tutto immerso: se ρ_corpo > ρ_fluido affonda, se è minore risale, se è uguale resta sospeso (come un pesce o un sommergibile).",
 "Un corpo che galleggia si immerge fino a quando la spinta eguaglia il peso: ρ_fluido·V_imm = ρ_corpo·V, quindi la frazione immersa è ρ_corpo/ρ_fluido. Il ghiaccio (920) in acqua (1000) sta sotto al 92%.",
 "Peso apparente = peso − spinta: un oggetto in acqua «pesa» meno. Misurando il peso in aria e in acqua si ricava la densità di un corpo (principio della pesata idrostatica)."],
 es:[{q:"Un tronco di densità 600 kg/m³ e volume 0,5 m³ galleggia in acqua. Quale volume è immerso e quale carico massimo può sostenere?",p:["V_imm = 0,6·0,5 = 0,3 m³","Carico max: tutta la spinta disponibile, ρ_acqua·V = 500 kg, meno la massa del tronco 300 kg"],r:"0,3 m³ immersi; circa 200 kg di carico"},
     {q:"Un oggetto pesa 10 N in aria e 6 N in acqua. Qual è la sua densità?",p:["Spinta = 10 − 6 = 4 N = peso dell'acqua spostata","Il corpo pesa 10/4 = 2,5 volte l'acqua di pari volume"],r:"2500 kg/m³"}],
 med:"In acqua la spinta scarica le articolazioni: è il principio dell'idrokinesiterapia e della riabilitazione in piscina."},
u3c:{sp:["Un fluido ideale è incomprimibile e senza attrito interno. In moto stazionario la portata Q = A·v (volume che passa ogni secondo) è uguale in ogni sezione del tubo: equazione di continuità. Dove il tubo si stringe il fluido accelera.",
 "Nei condotti che si ramificano conta la sezione TOTALE: l'aorta ha circa 3–5 cm², i capillari tutti insieme migliaia di cm². Per questo il sangue corre nell'aorta (decine di cm/s) e quasi si ferma nei capillari (meno di 1 mm/s), dove avvengono gli scambi.",
 "Teorema di Bernoulli: lungo un tubo p + ½ρv² + ρgh resta costante. È la conservazione dell'energia per unità di volume: pressione, energia cinetica, energia potenziale. In un tubo orizzontale, dove la velocità aumenta la pressione diminuisce.",
 "Applicazioni: in una stenosi (restringimento) il sangue accelera e la pressione laterale cala, la parete può essere schiacciata dall'esterno; in un aneurisma (dilatazione) il sangue rallenta e la pressione sulla parete già sfiancata aumenta, che peggiora la dilatazione."],
 es:[{q:"In un'arteria il sangue scorre a 0,2 m/s; in un tratto di stenosi la sezione è un quarto. Velocità nella stenosi e calo di pressione? (ρ = 1000 kg/m³)",p:["v₂ = 0,2·4 = 0,8 m/s","Δp = ½ρ(v₂² − v₁²) = 500·(0,64 − 0,04)"],r:"0,8 m/s; Δp = 300 Pa (circa 2 mmHg)"},
     {q:"Un tubo di sezione 2 cm² porta 6 L/min. Quanto vale la velocità?",p:["Q = 6·10⁻³ m³ / 60 s = 10⁻⁴ m³/s","v = Q/A = 10⁻⁴ / 2·10⁻⁴"],r:"0,5 m/s"}],
 med:"Il soffio udibile su una stenosi carotidea nasce dal flusso accelerato e turbolento a valle del restringimento."},
u3d:{sp:["I fluidi reali hanno attrito interno, la viscosità η (in Pa·s). Gli strati vicini alla parete sono frenati e restano fermi, quelli al centro vanno più veloci: in un tubo il profilo di velocità del moto laminare è parabolico. La differenza di velocità tra strati vicini è il gradiente di velocità.",
 "Per far scorrere un fluido viscoso serve una differenza di pressione. Legge di Poiseuille (moto laminare): Q = π r⁴ Δp / (8 η l). La portata è proporzionale alla quarta potenza del raggio: piccole variazioni del calibro di un vaso cambiano moltissimo il flusso.",
 "Come nella legge di Ohm (V = RI), si definisce la resistenza idraulica R = Δp/Q = 8ηl/(πr⁴). Vasi in serie: le resistenze si sommano. Vasi in parallelo: si sommano gli inversi, e la resistenza totale scende.",
 "Oltre una certa velocità il moto diventa turbolento: vortici, rumore, molta più energia dissipata. Il numero di Reynolds Re = ρvd/η lo prevede: indicativamente laminare sotto 2000, turbolento sopra qualche migliaio."],
 es:[{q:"Un'arteriola si restringe del 20% del raggio (r → 0,8 r). Di quanto cala la portata a parità di Δp?",p:["Q ∝ r⁴","0,8⁴ = 0,64·0,64 ≈ 0,41"],r:"scende a circa il 41%, cioè quasi del 60%"},
     {q:"Due vasi uguali, ciascuno con resistenza R, sono messi in parallelo. Quanto vale la resistenza totale?",p:["1/R_tot = 1/R + 1/R = 2/R"],r:"R/2"}],
 med:"Le arteriole regolano la pressione arteriosa proprio così: una piccola vasocostrizione cambia enormemente la resistenza periferica."},
u3e:{sp:["Le molecole sulla superficie di un liquido sono attratte solo verso l'interno: la superficie si comporta come una membrana tesa. La tensione superficiale τ (N/m) è l'energia (o la forza per unità di lunghezza) necessaria per allargarla.",
 "Una superficie curva spinge verso il suo centro: dentro una goccia o una bolla la pressione è maggiore che fuori. Legge di Laplace per una sfera: Δp = 2τ/r. Più la sfera è piccola, più la pressione interna è alta.",
 "Capillarità: in un tubo sottile un liquido che bagna le pareti (acqua nel vetro) sale, uno che non le bagna (mercurio) scende. L'altezza è maggiore quanto più il tubo è sottile.",
 "Il syllabus 2026 la chiede in forma qualitativa: conta capire il segno degli effetti, non fare conti complessi."],
 es:[{q:"Due bolle di sapone di raggio diverso sono collegate da un tubicino. Che cosa succede?",p:["Δp = 2τ/r: la bolla piccola ha pressione interna maggiore","L'aria passa dalla pressione alta alla bassa"],r:"La piccola si svuota nella grande"}],
 med:"Gli alveoli piccoli tenderebbero a svuotarsi in quelli grandi; il surfattante abbassa la tensione superficiale e li stabilizza. Nei prematuri senza surfattante si ha la sindrome da distress respiratorio."},
/* ---------- Unità 4 · Onde meccaniche ---------- */
u4a:{sp:["Un'onda è una perturbazione che viaggia: le particelle del mezzo oscillano attorno alla loro posizione, ma non si spostano con l'onda. Si trasporta energia, non materia (un tappo sull'acqua sale e scende, non viaggia con l'onda).",
 "Trasversale: le particelle oscillano perpendicolarmente alla direzione di propagazione (corda). Longitudinale: oscillano nella stessa direzione, con compressioni e rarefazioni (suono nei fluidi).",
 "Grandezze: ampiezza A (spostamento massimo), lunghezza d'onda λ (distanza tra due creste), periodo T (tempo di un'oscillazione), frequenza f = 1/T (in hertz), pulsazione ω = 2πf. In un periodo l'onda avanza di una lunghezza d'onda, quindi v = λ/T = λ·f.",
 "La velocità dipende dal mezzo (il suono: circa 340 m/s in aria, 1500 m/s in acqua e nei tessuti molli), la frequenza dipende dalla sorgente. Cambiando mezzo f resta uguale e varia λ."],
 es:[{q:"Un ultrasuono da 2 MHz attraversa un tessuto molle (v = 1500 m/s). Quanto vale λ?",p:["λ = v/f = 1500 / 2·10⁶"],r:"7,5·10⁻⁴ m = 0,75 mm"},
     {q:"Un suono di 680 Hz passa dall'aria (340 m/s) all'acqua (1500 m/s). Come cambiano f e λ?",p:["f resta 680 Hz","λ aria = 340/680 = 0,5 m; λ acqua = 1500/680 ≈ 2,2 m"],r:"f invariata; λ da 0,5 m a circa 2,2 m"}],
 med:"Più alta è la frequenza degli ultrasuoni, più piccola è λ e più fini sono i dettagli visibili in ecografia, ma minore è la profondità raggiunta."},
u4b:{sp:["L'intensità di un'onda è la potenza che attraversa ogni metro quadrato: I = P/A (W/m²). Per una sorgente puntiforme la potenza si distribuisce su una sfera di area 4πr², quindi I ∝ 1/r²: a distanza doppia l'intensità è un quarto.",
 "L'intensità è proporzionale al quadrato dell'ampiezza: ampiezza doppia, intensità quadrupla.",
 "L'orecchio percepisce intensità che vanno da 10⁻¹² a circa 1 W/m²: dodici ordini di grandezza. Per questo si usa una scala logaritmica, il livello sonoro in decibel: β = 10·log₁₀(I/I₀), con I₀ = 10⁻¹² W/m². Ogni fattore 10 nell'intensità aggiunge 10 dB.",
 "Regole rapide: ×2 → +3 dB; ×10 → +10 dB; ×100 → +20 dB; ×1000 → +30 dB. Due sorgenti uguali da 60 dB insieme fanno 63 dB, non 120."],
 es:[{q:"Un suono ha intensità 10⁻⁵ W/m². Quanti decibel?",p:["I/I₀ = 10⁻⁵ / 10⁻¹² = 10⁷","β = 10·log₁₀(10⁷) = 10·7"],r:"70 dB"},
     {q:"A 2 m da una sirena si misurano 100 dB. Quanti a 20 m?",p:["Distanza ×10 → intensità ÷100","÷100 = −20 dB"],r:"80 dB"}],
 med:"L'esposizione prolungata sopra gli 85 dB danneggia le cellule ciliate della coclea; l'audiometria misura le soglie in decibel per frequenza."},
u4c:{sp:["Quando sorgente e ascoltatore si avvicinano, le creste arrivano più ravvicinate: la frequenza percepita è più alta. Quando si allontanano, più bassa. È l'effetto Doppler: il suono della sirena che cambia mentre l'ambulanza passa.",
 "La sorgente emette sempre la stessa frequenza: cambia solo quella percepita. Lo spostamento di frequenza è proporzionale alla velocità relativa.",
 "Il syllabus 2026 chiede la descrizione qualitativa. Nel 2025 è uscito un calcolo semplice in percentuale: per velocità piccole rispetto al suono, la variazione relativa di frequenza è circa v/v_suono.",
 "Ecografia: una sonda emette impulsi di ultrasuoni e ascolta gli echi riflessi dalle interfacce tra tessuti diversi. Dal tempo di ritorno, con v ≈ 1540 m/s, si ricava la profondità (andata e ritorno: d = v·t/2)."],
 es:[{q:"Un'ambulanza si avvicina a 34 m/s (suono 340 m/s) emettendo 1000 Hz. Che frequenza si sente circa?",p:["f' = f·v/(v − v_s) = 1000·340/306"],r:"circa 1110 Hz (+11%)"},
     {q:"Un'eco torna alla sonda dopo 65 µs (v = 1540 m/s). A che profondità è l'interfaccia?",p:["d = v·t/2 = 1540·65·10⁻⁶ / 2"],r:"circa 5 cm"}],
 med:"L'ecodoppler misura velocità e verso del flusso sanguigno dallo spostamento di frequenza degli ultrasuoni riflessi dai globuli rossi."},
u4d:{sp:["L'oscillatore armonico è il modello di ogni vibrazione: una massa attaccata a una molla, spostata dall'equilibrio, viene richiamata da una forza F = −kx e oscilla con x(t) = A·cos(ωt).",
 "Il periodo dipende solo da massa e rigidità: T = 2π√(m/k). Massa maggiore → oscillazione più lenta; molla più rigida → più rapida. Non dipende dall'ampiezza (isocronismo): per questo un pendolo può segnare il tempo.",
 "Un'onda armonica è un'oscillazione che si propaga: y(x,t) = A·sin(kx − ωt), con numero d'onda k = 2π/λ e pulsazione ω = 2π/T. Il rapporto ω/k è la velocità dell'onda.",
 "Quando due onde si incontrano gli spostamenti si sommano (sovrapposizione). Se arrivano in fase (creste con creste) l'ampiezza si somma: interferenza costruttiva. Se arrivano in opposizione (creste con ventri) si annullano: interferenza distruttiva. Conta la differenza di cammino: multiplo intero di λ → costruttiva; multiplo dispari di λ/2 → distruttiva."],
 es:[{q:"Una massa di 2 kg su una molla con k = 200 N/m. Quanto vale il periodo? (π ≈ 3,14)",p:["T = 2π√(2/200) = 2π·√0,01 = 2π·0,1"],r:"circa 0,63 s"},
     {q:"Due altoparlanti emettono la stessa nota con λ = 0,8 m. In un punto la differenza di distanza è 1,2 m. Che interferenza c'è?",p:["1,2/0,8 = 1,5 lunghezze d'onda = 3·(λ/2)","Multiplo dispari di λ/2"],r:"distruttiva (quasi silenzio)"}],
 med:"Le cuffie con cancellazione del rumore producono un'onda in opposizione di fase: interferenza distruttiva."},
/* ---------- Unità 5 · Termodinamica ---------- */
u5a:{sp:["Temperatura e calore non sono la stessa cosa. La temperatura misura lo stato di agitazione delle molecole; il calore è energia che passa da un corpo all'altro perché hanno temperature diverse, sempre dal più caldo al più freddo, fino all'equilibrio termico.",
 "Il calore necessario per cambiare la temperatura di un corpo è Q = c·m·ΔT. Il calore specifico c dice quanto un materiale «resiste» a scaldarsi: l'acqua ha un c altissimo (4186 J/(kg·K)), per questo il mare d'estate resta fresco e il corpo, fatto per il 60% d'acqua, cambia temperatura lentamente. La capacità termica C = c·m riguarda l'oggetto intero.",
 "Durante un passaggio di stato (fusione, ebollizione) il calore fornito non alza la temperatura: serve a rompere i legami tra le molecole. Q = λ·m, con λ calore latente (fusione del ghiaccio 334 kJ/kg, evaporazione dell'acqua circa 2260 kJ/kg).",
 "Calorimetria: in un recipiente isolato il calore ceduto dal corpo caldo è uguale a quello assorbito dal freddo. Da qui la temperatura di equilibrio, che è una media pesata con m·c."],
 es:[{q:"Si mescolano 2 kg d'acqua a 80 °C e 3 kg a 20 °C. Temperatura finale?",p:["T = (2·80 + 3·20)/(2 + 3) (stesso c)","= (160 + 60)/5"],r:"44 °C"},
     {q:"Quanto calore serve per far evaporare 10 g di sudore? (λ = 2260 kJ/kg)",p:["Q = λ·m = 2260·0,01 kJ"],r:"22,6 kJ sottratti alla pelle"}],
 med:"L'evaporazione del sudore è il principale meccanismo di raffreddamento sotto sforzo: il calore latente viene preso dal corpo."},
u5b:{sp:["Un gas perfetto è un modello: molecole puntiformi che non interagiscono se non urtandosi. Il suo stato è descritto da pressione p, volume V, temperatura T (sempre in kelvin) e numero di moli n, legati da pV = nRT.",
 "Casi particolari: a T costante pV = costante (Boyle: dimezzi il volume, la pressione raddoppia); a p costante V/T = costante; a V costante p/T = costante. Per due stati dello stesso gas: p₁V₁/T₁ = p₂V₂/T₂.",
 "La pressione nasce dagli urti delle molecole sulle pareti. La temperatura assoluta è proporzionale all'energia cinetica media delle molecole: per questo l'energia interna di un gas perfetto dipende solo da T (ΔU = n·c_v·ΔT).",
 "In condizioni normali (0 °C, 1 atm) una mole occupa circa 22,4 L. I gas reali si discostano dal modello a pressioni alte e temperature basse (non è nel syllabus 2026, ma è uscito nel 2025)."],
 es:[{q:"Un pallone contiene aria a 27 °C e 1 atm. Lo si scalda a 87 °C a volume costante. Pressione finale?",p:["Temperature in kelvin: 300 K → 360 K","p₂ = 1·360/300"],r:"1,2 atm"},
     {q:"Un sub espira una bolla di 1 L a 30 m di profondità (4 atm). Che volume ha in superficie (T costante)?",p:["p₁V₁ = p₂V₂ → 4·1 = 1·V₂"],r:"4 L"}],
 med:"Durante la risalita l'aria nei polmoni si espande: se un sub trattiene il respiro rischia il barotrauma polmonare."},
u5c:{sp:["Primo principio: l'energia si conserva. La variazione di energia interna di un sistema è il calore ricevuto meno il lavoro che il sistema compie: ΔU = Q − L. Convenzione: Q > 0 se entra, L > 0 se il gas si espande e spinge l'ambiente.",
 "Nel piano p–V il lavoro è l'area sotto la curva della trasformazione. A pressione costante L = p·ΔV. Se il gas viene compresso il lavoro è negativo (è l'ambiente a farlo sul gas).",
 "Le quattro trasformazioni del gas perfetto: isocora (V costante: L = 0, il calore va tutto in energia interna); isobara (p costante: L = pΔV); isoterma (T costante: ΔU = 0, il calore assorbito diventa tutto lavoro); adiabatica (nessuno scambio di calore: ΔU = −L, espandendosi il gas si raffredda, comprimendosi si scalda).",
 "Reversibile: lenta, una successione di stati di equilibrio, percorribile al contrario. Le trasformazioni reali (rapide, con attriti, con salti di temperatura) sono irreversibili. In un ciclo il gas torna allo stato iniziale: ΔU = 0 e il lavoro netto è l'area racchiusa."],
 es:[{q:"Un gas riceve 500 J di calore e si espande compiendo 200 J di lavoro. Quanto varia l'energia interna?",p:["ΔU = Q − L = 500 − 200"],r:"+300 J (la temperatura sale)"},
     {q:"Un gas a 2·10⁵ Pa si espande a pressione costante da 3 L a 5 L. Lavoro?",p:["ΔV = 2 L = 2·10⁻³ m³","L = 2·10⁵ · 2·10⁻³"],r:"400 J"}],
 med:"Una pompa per bicicletta si scalda gonfiando: la compressione rapida è quasi adiabatica e il lavoro fatto sul gas ne aumenta l'energia interna."},
u5d:{sp:["Il primo principio non dice in che direzione vanno i processi; lo dice il secondo. Clausius: il calore non passa spontaneamente dal freddo al caldo. Kelvin: nessuna macchina ciclica può trasformare in lavoro tutto il calore preso da una sola sorgente.",
 "Una macchina termica prende calore Q_c da una sorgente calda, ne trasforma una parte in lavoro L e cede il resto Q_f a una sorgente fredda. Rendimento η = L/Q_c = 1 − Q_f/Q_c, sempre minore di 1.",
 "Il rendimento massimo possibile tra due temperature è quello della macchina di Carnot (reversibile): η = 1 − T_f/T_c, con le temperature in kelvin. Per avvicinarsi al 100% servirebbe T_f = 0 K, irraggiungibile.",
 "L'entropia S è una funzione di stato che misura il «disordine»: il numero di modi microscopici compatibili con lo stato macroscopico. In un sistema isolato l'entropia non diminuisce mai: resta costante nei processi reversibili e aumenta in quelli irreversibili. Per un calore Q scambiato reversibilmente a temperatura T: ΔS = Q/T."],
 es:[{q:"Una macchina assorbe 1000 J e cede 700 J alla sorgente fredda a ogni ciclo. Lavoro e rendimento?",p:["L = 1000 − 700 = 300 J","η = 300/1000"],r:"300 J; 30%"},
     {q:"Quanta entropia acquista 1 kg di ghiaccio che fonde a 0 °C? (λ = 334 kJ/kg)",p:["Q = 334 000 J a T = 273 K","ΔS = Q/T = 334 000/273"],r:"circa 1220 J/K"}],
 med:"Il corpo umano è una macchina con rendimento basso (circa 20–25% nel lavoro muscolare): il resto dell'energia diventa calore."},
u5e:{sp:["Conduzione: il calore passa per contatto, da molecola a molecola, senza spostamento di materia. La potenza trasmessa è Q/t = k·A·ΔT/d: cresce con la superficie e la differenza di temperatura, diminuisce con lo spessore. I metalli conducono bene, aria e grasso male (isolanti).",
 "Convezione: il calore è trasportato da un fluido che si muove (l'aria calda sale, il sangue porta il calore dal centro alla pelle).",
 "Irraggiamento: ogni corpo emette onde elettromagnetiche (infrarosso a temperatura ambiente), con una potenza che cresce con la quarta potenza della temperatura assoluta. È l'unico modo di trasmettere calore nel vuoto (il Sole).",
 "Il corpo a riposo perde calore soprattutto per irraggiamento; in un ambiente caldo o durante lo sforzo prevale l'evaporazione del sudore."],
 es:[{q:"Raddoppiando lo spessore di una coperta, come cambia il calore perso per conduzione (stessi ΔT e area)?",p:["Q/t ∝ 1/d"],r:"si dimezza"}],
 med:"Le termocamere misurano l'infrarosso emesso dalla pelle; il tessuto adiposo isola, per questo l'ipotermia è più rapida nei soggetti magri."},
/* ---------- Unità 6 · Elettricità e magnetismo ---------- */
u6a:{sp:["La carica elettrica esiste in due tipi, positiva e negativa; è quantizzata (multipla di e = 1,6·10⁻¹⁹ C) e si conserva: non si crea né si distrugge, si sposta.",
 "Legge di Coulomb: due cariche puntiformi si attraggono (segni opposti) o si respingono (stesso segno) con F = k·q₁q₂/r², k ≈ 9·10⁹ N·m²/C². Come la gravità è una legge dell'inverso del quadrato, ma è enormemente più intensa.",
 "Nei conduttori (metalli, soluzioni saline) le cariche si muovono liberamente; negli isolanti no. Avvicinando un corpo carico a un conduttore le sue cariche si separano: induzione elettrostatica. In un isolante le molecole si orientano senza spostarsi: polarizzazione.",
 "In un conduttore in equilibrio le cariche in eccesso stanno sulla superficie e il campo all'interno è nullo (gabbia di Faraday)."],
 es:[{q:"Due cariche si respingono con 9 N. La distanza viene triplicata e una carica raddoppiata. Nuova forza?",p:["F ∝ q₁q₂/r²: ×2 per la carica, ÷9 per la distanza","9·2/9"],r:"2 N"}],
 med:"Il defibrillatore e l'elettrocardiografo usano elettrodi metallici e gel conduttivo: la pelle secca è un cattivo conduttore."},
u6b:{sp:["Il campo elettrico E descrive come una carica modifica lo spazio intorno a sé: è la forza per unità di carica, E = F/q (N/C = V/m). Si disegna con linee di campo: escono dalle cariche positive, entrano nelle negative, non si incrociano, sono più fitte dove il campo è più intenso.",
 "Il potenziale elettrico V (volt) è l'energia potenziale per unità di carica. Conta la differenza di potenziale: una carica q che passa da un punto all'altro guadagna o perde energia q·ΔV. Una carica positiva lasciata libera va spontaneamente verso potenziali più bassi.",
 "Le superfici equipotenziali (stesso V) sono sempre perpendicolari alle linee di campo; spostarsi su di esse non costa lavoro. Per una carica puntiforme sono sfere concentriche; in un condensatore piano sono piani paralleli alle armature.",
 "In un campo uniforme una carica subisce una forza costante F = qE: si muove di moto uniformemente accelerato (come un sasso nel campo di gravità). La velocità finale si trova dall'energia: ½mv² = q·ΔV."],
 es:[{q:"Tra due armature distanti 1 cm c'è una d.d.p. di 100 V. Quanto vale il campo e che forza subisce un elettrone?",p:["E = ΔV/d = 100/0,01 = 10⁴ V/m","F = eE = 1,6·10⁻¹⁹ · 10⁴"],r:"10⁴ V/m; 1,6·10⁻¹⁵ N"},
     {q:"Un protone attraversa una d.d.p. di 1000 V partendo da fermo. Energia cinetica finale?",p:["Ec = q·ΔV = e·1000 V"],r:"1000 eV = 1,6·10⁻¹⁶ J"}],
 med:"La membrana di un neurone a riposo ha una d.d.p. di circa −70 mV su uno spessore di 7 nm: il campo è di circa 10⁷ V/m."},
u6c:{sp:["Un condensatore è fatto di due conduttori (armature) separati da un isolante. Collegato a una pila, si carica con +Q e −Q: il rapporto C = Q/V si chiama capacità e si misura in farad (di solito µF o pF).",
 "Per il condensatore piano C = ε₀εᵣA/d: armature più grandi e più vicine immagazzinano più carica. Un dielettrico tra le armature si polarizza, riduce il campo interno e aumenta la capacità di εᵣ volte.",
 "Energia immagazzinata: U = ½CV² = ½QV. È l'energia che il defibrillatore accumula e poi scarica in pochi millisecondi.",
 "Collegamenti (al contrario delle resistenze): in parallelo le capacità si sommano, C = C₁ + C₂; in serie si sommano gli inversi, 1/C = 1/C₁ + 1/C₂."],
 es:[{q:"Un defibrillatore ha un condensatore da 100 µF caricato a 2000 V. Quanta energia immagazzina?",p:["U = ½CV² = ½·10⁻⁴·(2·10³)²","= ½·10⁻⁴·4·10⁶"],r:"200 J"},
     {q:"Due condensatori da 6 µF e 3 µF in serie. Capacità equivalente?",p:["1/C = 1/6 + 1/3 = 1/6 + 2/6 = 3/6"],r:"2 µF"}],
 med:"La membrana cellulare (doppio strato lipidico isolante tra due soluzioni conduttive) si comporta come un condensatore di circa 1 µF/cm²."},
u6d:{sp:["La corrente elettrica è un flusso ordinato di cariche: I = Δq/Δt, in ampere. Per convenzione va dal polo + al polo −. Un generatore ideale mantiene ai suoi capi una differenza di potenziale costante, come una «pompa» per le cariche.",
 "Legge di Ohm: nei conduttori ohmici V = R·I. La resistenza dipende dal materiale e dalla forma: R = ρ·l/A (resistività per lunghezza diviso sezione). Un filo lungo e sottile resiste di più.",
 "In serie la corrente è la stessa e le resistenze si sommano. In parallelo la tensione è la stessa, le correnti si dividono (di più dove la resistenza è minore) e si sommano gli inversi: la resistenza equivalente è minore della più piccola.",
 "Una resistenza attraversata da corrente si scalda (effetto Joule): P = V·I = R·I² = V²/R. L'energia consumata è potenza per tempo, in joule o in kWh."],
 es:[{q:"Resistenze da 4 Ω e 12 Ω in parallelo collegate a 12 V. Resistenza equivalente e corrente totale?",p:["1/R = 1/4 + 1/12 = 3/12 + 1/12 = 4/12 → R = 3 Ω","I = 12/3"],r:"3 Ω; 4 A (3 A nella prima, 1 A nella seconda)"},
     {q:"Un asciugacapelli da 2000 W resta acceso 15 minuti. Quanta energia consuma?",p:["E = P·t = 2 kW · 0,25 h"],r:"0,5 kWh = 1,8·10⁶ J"}],
 med:"Il pericolo di una scossa dipende dalla corrente che attraversa il corpo: la pelle bagnata ha resistenza molto più bassa e lascia passare correnti molto maggiori a parità di tensione."},
u6e:{sp:["Il campo magnetico B (tesla) è generato da magneti e da correnti: Oersted vide che un filo percorso da corrente devia l'ago di una bussola. Le linee di B sono sempre chiuse: non esistono poli magnetici isolati.",
 "Una carica in moto in un campo magnetico subisce la forza di Lorentz F = qvB sin θ, perpendicolare sia a v sia a B. Su una carica ferma, o che si muove parallela a B, la forza è nulla. Un filo percorso da corrente in un campo subisce F = I·l·B.",
 "Siccome è sempre perpendicolare alla velocità, la forza di Lorentz non compie lavoro: curva la traiettoria senza cambiare il modulo della velocità. In un campo uniforme la carica percorre una circonferenza di raggio r = mv/(qB).",
 "Induzione elettromagnetica: se il flusso magnetico Φ = B·A·cos θ attraverso un circuito cambia nel tempo, nel circuito nasce una f.e.m. = −ΔΦ/Δt (Faraday-Neumann). Il segno meno (Lenz) dice che la corrente indotta si oppone alla variazione che l'ha generata. Un flusso costante non induce nulla."],
 es:[{q:"Un elettrone si muove a 10⁶ m/s perpendicolarmente a un campo di 0,01 T. Forza?",p:["F = evB = 1,6·10⁻¹⁹ · 10⁶ · 10⁻²"],r:"1,6·10⁻¹⁵ N"},
     {q:"Il flusso in una spira passa da 0,02 Wb a 0 in 0,1 s. Quanto vale la f.e.m. indotta media?",p:["|ΔΦ|/Δt = 0,02/0,1"],r:"0,2 V"}],
 med:"La risonanza magnetica usa campi B da 1,5–3 T; il segnale viene letto per induzione nelle bobine. Anche la stimolazione magnetica transcranica induce correnti nel tessuto cerebrale."},
/* ---------- Unità 7 · Fisica delle radiazioni ---------- */
u7a:{sp:["Le onde elettromagnetiche sono campi elettrici e magnetici che oscillano perpendicolari tra loro e alla direzione di propagazione. Non hanno bisogno di un mezzo: nel vuoto viaggiano tutte a c = 3·10⁸ m/s, e vale c = λ·f.",
 "Lo spettro, in ordine di frequenza crescente (e lunghezza d'onda decrescente): onde radio, microonde, infrarosso, visibile (rosso 700 nm → violetto 400 nm), ultravioletto, raggi X, raggi γ.",
 "La luce è anche fatta di pacchetti di energia, i fotoni: E = h·f = h·c/λ, con h ≈ 6,6·10⁻³⁴ J·s. Un fotone X ha un'energia migliaia di volte maggiore di un fotone visibile.",
 "Ionizzante o no dipende dall'energia del singolo fotone rispetto all'energia di ionizzazione degli atomi (qualche eV, circa 10 eV per le molecole biologiche), non dall'intensità del fascio. Radio, microonde, infrarosso e visibile non ionizzano; UV di alta energia, X e γ sì."],
 es:[{q:"Energia di un fotone verde (λ = 500 nm)? (hc ≈ 1240 eV·nm)",p:["E = hc/λ = 1240/500 eV"],r:"circa 2,5 eV"},
     {q:"Frequenza di una radiazione con λ = 3 m?",p:["f = c/λ = 3·10⁸ / 3"],r:"10⁸ Hz = 100 MHz (onde radio)"}],
 med:"I raggi X (decine di keV) ionizzano e permettono la radiografia; i telefoni cellulari (fotoni di circa 10⁻⁵ eV) scaldano ma non ionizzano."},
u7b:{sp:["Riflessione: il raggio riflesso giace nello stesso piano di quello incidente e della normale, e forma con la normale lo stesso angolo.",
 "Nei materiali la luce rallenta: l'indice di rifrazione n = c/v è sempre ≥ 1 (aria ≈ 1, acqua 1,33, vetro circa 1,5). Passando da un mezzo all'altro il raggio cambia direzione secondo la legge di Snell: n₁ sin θ₁ = n₂ sin θ₂.",
 "Verso un mezzo più rifrangente il raggio si avvicina alla normale; verso uno meno rifrangente si allontana. In quest'ultimo caso, oltre l'angolo limite (sin θ_L = n₂/n₁) la luce non esce più: riflessione totale. È così che la luce resta intrappolata nelle fibre ottiche.",
 "In una lastra a facce parallele le due rifrazioni si compensano: il raggio esce parallelo a quello entrato, solo spostato di lato. Cambiando mezzo la frequenza resta la stessa, cambiano velocità e lunghezza d'onda."],
 es:[{q:"Angolo limite tra vetro (n = 1,5) e aria?",p:["sin θ_L = 1/1,5 ≈ 0,67","θ_L ≈ 42°"],r:"circa 42°"},
     {q:"Un raggio passa dall'aria all'acqua (n = 1,33) con incidenza 30°. Angolo di rifrazione?",p:["sin θ₂ = sin 30°/1,33 = 0,5/1,33 ≈ 0,38","θ₂ ≈ 22°"],r:"circa 22°, più vicino alla normale"}],
 med:"Endoscopi e broncoscopi usano fasci di fibre ottiche per portare luce dentro il corpo e immagini fuori."},
u7c:{sp:["Una lente convergente sottile (più spessa al centro) fa convergere i raggi paralleli all'asse in un punto, il fuoco F, a distanza f dalla lente. Il potere diottrico D = 1/f si misura in diottrie (f in metri).",
 "Equazione dei punti coniugati: 1/p + 1/q = 1/f, con p distanza dell'oggetto e q dell'immagine. Ingrandimento m = −q/p: se è negativo l'immagine è capovolta.",
 "Costruzione con tre raggi: quello parallelo all'asse esce passando per il fuoco; quello per il centro della lente non devia; quello passante per il fuoco anteriore esce parallelo.",
 "Casi: oggetto oltre 2f → immagine reale, capovolta, rimpicciolita (fotocamera, occhio); tra f e 2f → reale, capovolta, ingrandita (proiettore); in f → nessuna immagine; dentro f → virtuale, diritta, ingrandita (lente d'ingrandimento)."],
 es:[{q:"Lente con f = 10 cm, oggetto a 30 cm. Dove si forma l'immagine e com'è?",p:["1/q = 1/10 − 1/30 = 3/30 − 1/30 = 2/30 → q = 15 cm","m = −15/30 = −0,5"],r:"a 15 cm, reale, capovolta, metà"},
     {q:"Una lente ha potere +4 D. Qual è la distanza focale?",p:["f = 1/D = 1/4 m"],r:"25 cm"}],
 med:"Cristallino e cornea formano un sistema convergente di circa 60 diottrie; l'immagine sulla retina è reale e capovolta, il cervello la raddrizza."},
u7d:{sp:["Attraversando un materiale, una parte dei fotoni viene assorbita. Ogni strato sottile assorbe la stessa frazione di quello che gli arriva: per questo l'intensità non cala in modo lineare ma esponenziale con lo spessore, I = I₀·e^(−µx).",
 "In chimica e in laboratorio si usa la forma decimale, la legge di Lambert-Beer: A = log₁₀(I₀/I) = ε·c·l. L'assorbanza A è proporzionale alla concentrazione c e al cammino ottico l (ε è il coefficiente di assorbimento molare, tipico della sostanza e della lunghezza d'onda).",
 "Trasmittanza T = I/I₀ = 10^(−A): con A = 1 passa il 10%, con A = 2 l'1%, con A = 3 lo 0,1%. Raddoppiare spessore o concentrazione raddoppia A, non dimezza T.",
 "È il principio dello spettrofotometro: misurando A si risale alla concentrazione di una sostanza in soluzione."],
 es:[{q:"Una soluzione trasmette il 10% della luce. Se si raddoppia la concentrazione, quanto ne trasmette?",p:["T = 10% → A = 1","Concentrazione ×2 → A = 2","T = 10⁻²"],r:"1%"},
     {q:"A = 0,5 con una cuvetta da 1 cm. Che assorbanza dà la stessa soluzione in una cuvetta da 3 cm?",p:["A ∝ l"],r:"1,5"}],
 med:"Il pulsossimetro misura la saturazione di ossigeno confrontando l'assorbimento di luce rossa e infrarossa da parte di emoglobina ossigenata e non ossigenata."},
u7e:{sp:["Alcuni nuclei sono instabili e si trasformano spontaneamente emettendo radiazione: sono radioattivi. Isotopi = stesso numero atomico Z (stesso elemento), diverso numero di neutroni e quindi di massa A.",
 "Decadimenti: α, il nucleo emette un nucleo di elio (A − 4, Z − 2), radiazione poco penetrante, fermata da un foglio di carta; β⁻, un neutrone diventa protone ed esce un elettrone (Z + 1, A invariato), fermata da pochi mm di alluminio; γ, un nucleo eccitato emette un fotone (A e Z invariati), molto penetrante, serve piombo o cemento.",
 "Il decadimento del singolo nucleo è casuale, ma su tanti nuclei vale la legge N(t) = N₀·e^(−λt). L'emivita T½ = ln2/λ è il tempo dopo cui ne resta metà: dopo n emivite resta N₀/2ⁿ.",
 "L'attività A = λN è il numero di decadimenti al secondo, in becquerel (Bq). Diminuisce con la stessa emivita dei nuclei."],
 es:[{q:"Il tecnezio-99m (T½ = 6 h) è somministrato con un'attività di 800 MBq. Quanta ne resta dopo 24 h?",p:["24 h = 4 emivite","800/2⁴ = 800/16"],r:"50 MBq"},
     {q:"Il ²²⁶Ra (Z = 88) decade α. Che nucleo si forma?",p:["A: 226 − 4 = 222","Z: 88 − 2 = 86 (radon)"],r:"²²²Rn"}],
 med:"In medicina nucleare si scelgono isotopi con emivita breve (ore) per fare l'esame con poca dose; in radioterapia si usano fotoni e particelle per distruggere le cellule tumorali."}
};
FIS_TOPICS.forEach(t=>{const x=FIS_EXPL[t.id];if(x)Object.assign(t,x);});

/* ===== Completamento di tutte le parti (10 ottobre 2026, sera): voci del syllabus, esempi, animazioni, esercizi ===== */
FIS_EXPL.u2a.sp.splice(1,0,"La legge oraria x(t) dice dove si trova il corpo a ogni istante; la traiettoria è la linea che percorre. Velocità media = Δx/Δt; la velocità istantanea è quella in un preciso istante, cioè la pendenza del grafico posizione-tempo in quel punto. Allo stesso modo l'accelerazione istantanea è la pendenza del grafico velocità-tempo, e nel grafico velocità-tempo l'area sotto la curva è lo spazio percorso. Saper leggere questi grafici è una delle richieste esplicite del syllabus.");
FIS_EXPL.u3a.sp.unshift("Stati di aggregazione: nei solidi le particelle restano in posizioni fisse e il corpo ha forma e volume propri; i liquidi hanno volume proprio ma prendono la forma del recipiente; i gas occupano tutto lo spazio disponibile. Liquidi e gas sono fluidi perché scorrono: non oppongono resistenza a uno sforzo di taglio.");
FIS_EXPL.u3a.sp.push("Il manometro misura la pressione relativa, cioè la differenza rispetto all'atmosfera: in un manometro a U il dislivello h del liquido dà Δp = ρgh. Lo sfigmomanometro esprime la pressione arteriosa in mmHg, cioè come altezza di una colonna di mercurio, la stessa unità dell'esperimento di Torricelli.");
FIS_EXPL.u5a.sp.unshift("Sistema è la parte di universo che si studia (un gas in un cilindro, il corpo umano), ambiente tutto il resto; lo stato del sistema è descritto da variabili come pressione, volume e temperatura. Scale di temperatura: Celsius (0 °C fusione del ghiaccio, 100 °C ebollizione a 1 atm), Kelvin (T = t + 273,15; 0 K è lo zero assoluto) e Fahrenheit (°F = 1,8·°C + 32). Una variazione di 1 °C è uguale a una di 1 K.");
FIS_EXPL.u5b.sp.push("Calore specifico dei gas ideali: dipende da come si scalda il gas. A volume costante tutto il calore diventa energia interna; per un gas monoatomico c_v = (3/2)R per mole. A pressione costante il gas si espande e compie anche lavoro, quindi serve più calore: c_p = c_v + R, cioè (5/2)R per un monoatomico (relazione di Mayer).");
FIS_EXPL.u6b.sp.push("Con più cariche vale il principio di sovrapposizione: il campo totale è la somma vettoriale dei campi di ciascuna carica, mentre i potenziali (scalari) si sommano con il loro segno. Due cariche uguali danno campo nullo nel punto medio. L'energia potenziale di due cariche puntiformi è U = k·q₁q₂/r: positiva se si respingono, negativa se si attraggono.");
FIS_EXPL.u3e.es.push({q:"Un capillare di raggio 0,25 mm è immerso in acqua (τ = 0,073 N/m, g = 10 m/s²). Di quanto sale l'acqua?",p:["h = 2τ/(ρ·g·r)","= 2·0,073 / (1000·10·0,25·10⁻³) = 0,146/2,5"],r:"circa 0,058 m, cioè 6 cm"});
FIS_EXPL.u5e.es.push({q:"Un vetro di 2 m², spesso 4 mm, separa 20 °C da 0 °C (k = 0,8 W/(m·K)). Quanta potenza passa per conduzione?",p:["Q/t = k·A·ΔT/d","= 0,8·2·20/0,004"],r:"8000 W: per questo si usano i doppi vetri con aria in mezzo"});
FIS_EXPL.u6a.es.push({q:"Due cariche di +2 µC e +3 µC distano 30 cm. Quanto vale la forza?",p:["F = k·q₁q₂/r² = 9·10⁹ · (2·10⁻⁶)(3·10⁻⁶) / 0,3²","= 0,054 / 0,09"],r:"0,6 N, repulsiva"});
FIS_EXPL.u1d.med="In farmacologia si controllano le unità come le dimensioni: una dose in mg/kg moltiplicata per il peso in kg dà mg; una velocità di infusione in mL/h per un tempo in h dà mL. Se l'unità finale non torna, il calcolo è sbagliato.";
const FIS_ANIM2={u1a:"estensive",u1b:"potenze",u1d:"dimensioni",u2f:"urti",u3e:"laplace",u5d:"carnot",u5e:"calore",u6a:"coulomb",u6c:"condensatore"};
FIS_TOPICS.forEach(t=>{const x=FIS_EXPL[t.id];if(x)Object.assign(t,x);if(FIS_ANIM2[t.id])t.anim=FIS_ANIM2[t.id];});

/* domande aggiuntive: ogni argomento ha ora almeno 6 domande, con almeno 2 a completamento */
FIS_QB.push(
{t:"u1a",k:"m",q:"Quale di queste grandezze è intensiva?",o:["massa","volume","temperatura","energia interna","quantità di calore"],a:2,s:"Non dipende dalla quantità di materia: tagliando un corpo a metà la temperatura resta uguale."},
{t:"u1a",k:"m",q:"Quale coppia contiene solo grandezze vettoriali?",o:["massa e tempo","velocità e forza","energia e lavoro","temperatura e pressione","densità e volume"],a:1,s:"Hanno modulo, direzione e verso."},
{t:"u1c",k:"m",q:"Il valore di cos 60° è:",o:["0","0,5","0,71","0,87","1"],a:1,s:"cos 60° = sin 30° = 0,5."},
{t:"u1c",k:"c",q:"Il prodotto scalare di due vettori perpendicolari vale ____.",a:["ZERO","0"],s:"a·b = ab·cos 90° = 0."},
{t:"u1c",k:"c",q:"Il prodotto vettoriale di due vettori è un vettore ____ a entrambi.",a:["PERPENDICOLARE","ORTOGONALE"],s:"Regola della mano destra."},
{t:"u1d",k:"m",q:"Quale grandezza è adimensionale?",o:["velocità","indice di rifrazione","pressione","energia","accelerazione"],a:1,s:"n = c/v: rapporto tra due velocità."},
{t:"u1d",k:"c",q:"Le dimensioni della pressione sono [M][L]^a[T]⁻²: l'esponente a vale ____.",a:["-1","−1","MENOUNO"],s:"Pa = N/m² = kg·m⁻¹·s⁻²."},
{t:"u1d",k:"c",q:"Una formula è sicuramente sbagliata se i due membri hanno ____ diverse.",a:["DIMENSIONI"],s:"Si possono uguagliare solo grandezze omogenee."},
{t:"u2a",k:"m",q:"Nel grafico posizione-tempo di un moto rettilineo uniforme si ottiene:",o:["una parabola","una retta inclinata","una retta sull'asse dei tempi","un'iperbole","una sinusoide"],a:1,s:"x = x₀ + vt: la pendenza è la velocità."},
{t:"u2a",k:"c",q:"Nel grafico velocità-tempo lo spazio percorso è uguale all'____ sotto la curva.",a:["AREA"],s:"Per un moto uniforme è un rettangolo v·t."},
{t:"u2b",k:"m",q:"Un sasso è lanciato orizzontalmente da 20 m d'altezza (g = 10 m/s²). Il tempo di volo è:",o:["1 s","2 s","4 s","0,5 s","dipende dalla velocità orizzontale"],a:1,s:"20 = ½·10·t² → t = 2 s; il moto orizzontale non conta."},
{t:"u2b",k:"c",q:"Nel moto circolare uniforme l'accelerazione è diretta verso il ____ della circonferenza.",a:["CENTRO"],s:"Accelerazione centripeta v²/r."},
{t:"u2b",k:"c",q:"Un corpo compie un giro ogni 2 s: la frequenza è ____ Hz.",a:["0.5","0,5"],s:"f = 1/T."},
{t:"u2e",k:"m",q:"Le pinzette e l'avambraccio flesso dal bicipite sono leve di:",o:["primo genere","secondo genere","terzo genere","quarto genere","nessun genere"],a:2,s:"La forza motrice sta tra fulcro e resistenza: sempre svantaggiose."},
{t:"u2e",k:"c",q:"Un corpo rigido è in equilibrio se sono nulle la somma delle forze e la somma dei ____.",a:["MOMENTI","MOMENTITORCENTI"],s:"Equilibrio traslazionale e rotazionale."},
{t:"u2e",k:"c",q:"Una massa di 2 kg in x = 0 e una di 3 kg in x = 5 m: il centro di massa è in x = ____ m.",a:["3","TRE"],s:"(2·0 + 3·5)/(2 + 3) = 3 m."},
{t:"u3a",k:"m",q:"Un manometro misura:",o:["la pressione assoluta più quella atmosferica","la differenza tra pressione assoluta e atmosferica","sempre 1 atm","la densità del fluido","la portata"],a:1,s:"Pressione relativa (manometrica)."},
{t:"u3a",k:"c",q:"Nell'esperimento di Torricelli l'atmosfera sostiene una colonna di mercurio alta ____ mm.",a:["760"],s:"1 atm = 760 mmHg."},
{t:"u3e",k:"m",q:"Secondo la legge di Laplace, la differenza di pressione tra interno ed esterno di una goccia:",o:["non dipende dal raggio","è maggiore se la goccia è più piccola","è maggiore se la goccia è più grande","è sempre nulla","dipende solo dalla densità"],a:1,s:"Δp = 2τ/r."},
{t:"u3e",k:"m",q:"In un tubo capillare di vetro l'acqua:",o:["scende sotto il livello esterno","sale, tanto più quanto il tubo è sottile","sale, tanto più quanto il tubo è largo","resta allo stesso livello","sale solo se è calda"],a:1,s:"h = 2τ/(ρgr)."},
{t:"u3e",k:"m",q:"La tensione superficiale si misura in:",o:["N/m","N/m²","J/kg","Pa·s","N·m"],a:0,s:"Forza per unità di lunghezza (o energia per unità di superficie, J/m²)."},
{t:"u3e",k:"m",q:"Il surfattante polmonare:",o:["aumenta la tensione superficiale negli alveoli","riduce la tensione superficiale e stabilizza gli alveoli piccoli","è un gas","aumenta la viscosità del sangue","trasporta l'ossigeno"],a:1,s:"Senza surfattante gli alveoli piccoli collassano (distress respiratorio del prematuro)."},
{t:"u3e",k:"c",q:"Il mercurio in un capillare di vetro ____ rispetto al livello esterno (sale/scende).",a:["SCENDE"],s:"Non bagna il vetro."},
{t:"u3e",k:"c",q:"La legge di ____ lega la pressione di curvatura al raggio di una superficie curva.",a:["LAPLACE"],s:"Δp = 2τ/r."},
{t:"u3e",k:"c",q:"Collegando due bolle di sapone di raggio diverso si svuota quella più ____.",a:["PICCOLA"],s:"Ha la pressione interna maggiore."},
{t:"u4b",k:"c",q:"Dieci sorgenti uguali da 50 dB, insieme, producono ____ dB.",a:["60"],s:"Intensità ×10 → +10 dB."},
{t:"u4b",k:"c",q:"A distanza doppia da una sorgente puntiforme l'intensità diventa un ____ (scrivi la frazione in lettere).",a:["QUARTO"],s:"I ∝ 1/r²."},
{t:"u4c",k:"m",q:"Se una sorgente sonora si allontana dall'ascoltatore, la frequenza percepita:",o:["aumenta","diminuisce","resta uguale","si annulla","raddoppia"],a:1,s:"Le creste arrivano più distanziate."},
{t:"u4c",k:"m",q:"In ecografia la profondità di un'interfaccia si ricava da:",o:["l'intensità dell'eco soltanto","il tempo di andata e ritorno dell'eco e la velocità del suono nei tessuti","la frequenza della sonda soltanto","il colore dell'immagine","l'effetto Doppler soltanto"],a:1,s:"d = v·t/2."},
{t:"u4c",k:"c",q:"Gli ultrasuoni hanno frequenza superiore a ____ kHz.",a:["20"],s:"Limite superiore dell'udibile."},
{t:"u4d",k:"m",q:"Raddoppiando la massa appesa a una molla, il periodo di oscillazione:",o:["raddoppia","si dimezza","aumenta di √2 volte","resta uguale","quadruplica"],a:2,s:"T = 2π√(m/k)."},
{t:"u3d",k:"c",q:"Nel moto laminare in un tubo il profilo delle velocità è ____ (massima al centro, nulla alle pareti).",a:["PARABOLICO"],s:"Gli strati vicini alla parete sono frenati dalla viscosità."},
{t:"u5b",k:"c",q:"Nell'equazione pV = nRT la temperatura va espressa in ____.",a:["KELVIN","K"],s:"Scala assoluta."},
{t:"u5b",k:"c",q:"Per un gas monoatomico c_v = (3/2)R e c_p = c_v + R = (x/2)R: x vale ____.",a:["5","CINQUE"],s:"Relazione di Mayer."},
{t:"u5d",k:"m",q:"Una macchina termica lavora tra 600 K e 300 K. Il rendimento massimo possibile è:",o:["25%","50%","75%","100%","200%"],a:1,s:"η = 1 − 300/600."},
{t:"u5d",k:"c",q:"In un sistema isolato l'entropia non può ____ (aumentare/diminuire).",a:["DIMINUIRE"],s:"Secondo principio."},
{t:"u5d",k:"c",q:"Spontaneamente il calore passa dal corpo più caldo a quello più ____.",a:["FREDDO"],s:"Enunciato di Clausius."},
{t:"u5e",k:"m",q:"Nel vuoto il calore si trasmette solo per:",o:["conduzione","convezione","irraggiamento","evaporazione","diffusione"],a:2,s:"Onde elettromagnetiche."},
{t:"u5e",k:"m",q:"Raddoppiando lo spessore di uno strato isolante (stessi ΔT e area), la potenza trasmessa per conduzione:",o:["raddoppia","si dimezza","resta uguale","quadruplica","si annulla"],a:1,s:"Q/t = kAΔT/d."},
{t:"u5e",k:"m",q:"Il trasporto di calore dovuto al movimento di un fluido si chiama:",o:["conduzione","convezione","irraggiamento","capillarità","osmosi"],a:1,s:"Il fluido caldo sale, il freddo scende."},
{t:"u5e",k:"c",q:"La potenza irraggiata da un corpo è proporzionale alla ____ potenza della temperatura assoluta.",a:["QUARTA"],s:"Legge di Stefan-Boltzmann (cenno)."},
{t:"u5e",k:"c",q:"A riposo il corpo umano disperde calore soprattutto per ____.",a:["IRRAGGIAMENTO"],s:"Sotto sforzo prevale l'evaporazione del sudore."},
{t:"u6a",k:"m",q:"Avvicinando un corpo carico a una sferetta metallica scarica, senza toccarla:",o:["la sferetta acquista una carica netta dello stesso segno","le cariche della sferetta si separano (induzione) e la sferetta viene attratta","non succede nulla","la sferetta diventa un isolante","si crea una corrente continua"],a:1,s:"Induzione elettrostatica."},
{t:"u6a",k:"c",q:"La carica dell'elettrone vale in modulo 1,6·10^x C: l'esponente x è ____.",a:["-19","−19"],s:"e = 1,6·10⁻¹⁹ C."},
{t:"u6a",k:"c",q:"Dimezzando la distanza tra due cariche la forza di Coulomb diventa ____ volte più grande.",a:["4","QUATTRO"],s:"F ∝ 1/r²."},
{t:"u6b",k:"m",q:"Due cariche uguali +q sono a distanza d. Il campo elettrico nel punto medio è:",o:["il doppio di quello di una sola carica","nullo","uguale a quello di una sola carica","infinito","diretto verso una delle due cariche"],a:1,s:"Sovrapposizione: due vettori uguali e opposti."},
{t:"u6e",k:"c",q:"La generazione di una f.e.m. per variazione del flusso magnetico si chiama induzione ____.",a:["ELETTROMAGNETICA"],s:"Faraday-Neumann-Lenz."},
{t:"u7b",k:"m",q:"In un materiale la luce viaggia a 2·10⁸ m/s. L'indice di rifrazione è:",o:["0,67","1","1,5","2","3"],a:2,s:"n = c/v = 3/2."},
{t:"u7b",k:"c",q:"Per la legge della riflessione l'angolo di riflessione è ____ all'angolo di incidenza.",a:["UGUALE"],s:"Entrambi misurati dalla normale."},
{t:"u7c",k:"m",q:"Un oggetto è a 20 cm da una lente convergente con f = 10 cm. L'immagine si forma a:",o:["10 cm","20 cm","30 cm","40 cm","all'infinito"],a:1,s:"1/q = 1/10 − 1/20 = 1/20: oggetto in 2f, immagine in 2f, capovolta e uguale."},
{t:"u7c",k:"c",q:"Una lente con distanza focale 50 cm ha un potere di ____ diottrie.",a:["2","DUE"],s:"D = 1/f = 1/0,5 m."},
{t:"u7d",k:"m",q:"Una soluzione ha assorbanza 2. Quale frazione della luce trasmette?",o:["2%","1%","10%","20%","50%"],a:1,s:"T = 10⁻²."},
{t:"u7d",k:"c",q:"Secondo Lambert-Beer l'assorbanza è proporzionale alla concentrazione e al ____ ottico.",a:["CAMMINO"],s:"A = ε·c·l."},
{t:"u7d",k:"c",q:"Lo strumento che misura l'assorbanza per ricavare una concentrazione è lo ____.",a:["SPETTROFOTOMETRO"],s:"Usato in tutti i laboratori di analisi."}
);

/* mappa del syllabus ufficiale 2026/27: ogni voce → argomento dell'app */
const FIS_MAP=[
["u1","Notazione scientifica; grandezze fisiche, dimensioni e unità, Sistema Internazionale",["u1a","u1b","u1d"]],
["u1","Conversioni, stima dell'ordine di grandezza; grandezze estensive e intensive, scalari e vettoriali",["u1b","u1a"]],
["u1","Funzioni trigonometriche elementari; vettori: componenti, somma, differenza, prodotto scalare e vettoriale",["u1c"]],
["u2","Cinematica: posizione, spostamento, traiettoria e legge oraria; velocità e accelerazione medie e istantanee",["u2a"]],
["u2","Moto rettilineo uniforme, uniformemente accelerato, caduta libera, moto parabolico; moto circolare uniforme",["u2a","u2b"]],
["u2","Tre principi della dinamica; equilibrio traslazionale; peso, gravitazione, contatto, attrito, tensione, Hooke",["u2c"]],
["u2","Lavoro, potenza, teorema dell'energia cinetica, forze conservative, energia potenziale, conservazione",["u2d"]],
["u2","Quantità di moto, impulso, conservazione nei sistemi isolati",["u2f"]],
["u2","Centro di massa, corpo rigido, momento torcente, equilibrio rotazionale, leve nel corpo umano",["u2e"]],
["u3","Stati di aggregazione; pressione e densità",["u3a"]],
["u3","Stevino, Pascal, Archimede e galleggiamento; Torricelli e manometro",["u3a","u3b"]],
["u3","Flusso e portata; moto stazionario, laminare e turbolento; continuità; Bernoulli, stenosi e aneurisma",["u3c","u3d"]],
["u3","Viscosità, profilo parabolico, gradiente di velocità; Poiseuille; resistenze in serie e in parallelo",["u3d"]],
["u3","Tensione superficiale, capillarità, interfacce piane e curve, legge di Laplace (qualitativa)",["u3e"]],
["u4","Onde meccaniche; oscillatore armonico; frequenza, periodo, pulsazione, lunghezza d'onda, velocità; equazione dell'onda armonica; onde trasversali e longitudinali",["u4a","u4d"]],
["u4","Sovrapposizione e interferenza",["u4d"]],
["u4","Energia, potenza e intensità delle onde; legge dell'inverso del quadrato",["u4b"]],
["u4","Onde acustiche, velocità del suono, intensità e percezione, decibel",["u4a","u4b"]],
["u4","Effetto Doppler (qualitativo)",["u4c"]],
["u5","Sistema e ambiente; variabili e stato; funzioni di stato; scale di temperatura; gas perfetti",["u5a","u5b"]],
["u5","Calore, capacità termica, calore specifico (anche dei gas ideali), passaggi di stato, calore latente, calorimetria",["u5a","u5b"]],
["u5","Conduzione, convezione, irraggiamento",["u5e"]],
["u5","Primo principio; energia interna, calore e lavoro; reversibili e irreversibili; isoterma, isocora, isobara, adiabatica",["u5c"]],
["u5","Secondo principio, cicli, macchine termiche, rendimento, Carnot; entropia e sua interpretazione statistica",["u5d"]],
["u6","Carica, conservazione, Coulomb; campo elettrico e linee di forza; campo di più cariche; moto in campo uniforme",["u6a","u6b"]],
["u6","Energia potenziale e potenziale elettrico; conservazione dell'energia",["u6b"]],
["u6","Conduttori e dielettrici: induzione elettrostatica e polarizzazione (qualitativa)",["u6a","u6c"]],
["u6","Corrente continua, generatore ideale, leggi di Ohm, resistività, effetto Joule, resistenze in serie e parallelo",["u6d"]],
["u6","Capacità, condensatore piano, dielettrico, energia, condensatori in serie e parallelo",["u6c"]],
["u6","Campo magnetico dalle correnti (Oersted); forza di Lorentz su carica e su filo; moto circolare",["u6e"]],
["u6","Induzione elettromagnetica, Faraday-Neumann-Lenz, correnti indotte e loro verso",["u6e"]],
["u7","Onde elettromagnetiche: campi E e B perpendicolari, λ, f, velocità, ampiezza, intensità; spettro",["u7a"]],
["u7","Fotone ed energia E = hf; radiazioni ionizzanti e non ionizzanti",["u7a"]],
["u7","Assorbimento della radiazione: legge di Lambert-Beer",["u7d"]],
["u7","Radioattività: nuclei instabili, isotopi, attività, legge del decadimento, emivita, decadimenti α, β, γ",["u7e"]],
["u7","Ottica: riflessione, rifrazione, indice di rifrazione; lenti convergenti sottili e punti coniugati",["u7b","u7c"]]
];

