/* ================= FISICA: problemi guidati ed esercizi significativi (approfondimento) =================
   Per ogni argomento: un problema guidato a più passaggi (si aggiunge agli esempi svolti) e 4–6 domande nuove,
   sempre sulle voci del syllabus 2026/27. Numeri pensati per il calcolo a mente (g = 10 m/s² se non diversamente indicato). */
const FIS_PROB={
u1a:{q:"Una sacca contiene 500 mL di soluzione fisiologica con densità 1,005 g/cm³. Qual è la massa? Quali grandezze sono estensive?",p:["500 mL = 500 cm³","m = ρ·V = 1,005 · 500 = 502,5 g","Massa e volume dipendono dalla quantità (estensive); la densità no (intensiva)"],r:"circa 0,50 kg; massa e volume estensive, densità intensiva"},
u1b:{q:"Un'infusione va a 2 mL/min per 3 ore. Quanto liquido entra in litri e in m³?",p:["3 h = 180 min","2 · 180 = 360 mL = 0,36 L","1 L = 10⁻³ m³ → 0,36·10⁻³ = 3,6·10⁻⁴ m³"],r:"0,36 L = 3,6·10⁻⁴ m³"},
u1c:{q:"Un arto in trazione è tirato da due forze di 30 N perpendicolari tra loro. Quanto vale la risultante e che angolo forma?",p:["Sono perpendicolari: Pitagora","R = √(30² + 30²) = 30·√2 ≈ 42 N","Componenti uguali → bisettrice: 45° da ciascuna forza"],r:"circa 42 N, a 45°"},
u1d:{q:"Il periodo T di un pendolo dipende solo dalla lunghezza l e da g. Con l'analisi dimensionale trova la forma della formula.",p:["T = l^a · g^b → [T] = [L]^a · [L T⁻²]^b","Per L: a + b = 0; per T: −2b = 1","b = −½, a = ½"],r:"T ∝ √(l/g) (la formula vera è T = 2π√(l/g))"},
u2a:{q:"Un'auto va a 72 km/h. Il guidatore vede un ostacolo, reagisce dopo 1 s e poi frena con 5 m/s². In quanti metri si ferma?",p:["72 km/h = 20 m/s","Durante la reazione (moto uniforme): 20 · 1 = 20 m","Frenata: s = v²/(2a) = 400/10 = 40 m"],r:"60 m in tutto (il tempo di reazione pesa un terzo)"},
u2b:{q:"Un pallone è calciato a 20 m/s con un angolo di 30°. Quanto resta in aria e quanto lontano cade? (g = 10)",p:["vₓ = 20·cos 30° ≈ 17,3 m/s; v_y = 20·sin 30° = 10 m/s","Tempo di volo = 2·v_y/g = 2 s","Gittata = vₓ · t ≈ 17,3 · 2"],r:"2 s; circa 35 m"},
u2c:{q:"Una persona di 70 kg sta su una bilancia in un ascensore che accelera verso l'alto a 2 m/s². Che cosa segna la bilancia? (g = 10)",p:["Forze: normale N verso l'alto, peso mg verso il basso","N − mg = m·a → N = m(g + a) = 70 · 12","N = 840 N, come se pesasse 84 kg"],r:"840 N (84 kg sulla scala); in discesa accelerata segnerebbe meno"},
u2d:{q:"Un atleta di 60 kg sale 12 m di scale in 20 s. Lavoro contro la gravità, potenza ed energia chimica consumata se il rendimento muscolare è del 20%?",p:["L = m·g·h = 60·10·12 = 7200 J","P = 7200/20 = 360 W","Energia chimica = 7200/0,20 = 36 000 J ≈ 8,6 kcal"],r:"7200 J; 360 W; circa 36 kJ"},
u2e:{q:"Alzandosi sulla punta di un piede si ha una leva di 2° genere: fulcro sulle dita, peso del corpo (700 N) a 10 cm dalle dita, tendine d'Achille a 15 cm. Che forza fa il polpaccio?",p:["Momenti rispetto alle dita: F·0,15 = 700·0,10","F = 70/0,15"],r:"circa 470 N: leva vantaggiosa, la forza è minore del peso"},
u2f:{q:"Una persona di 60 kg salta giù da 1,25 m. Atterrando a gambe tese si ferma in 0,01 s, piegando le gambe in 0,2 s. Forze medie di arresto? (g = 10)",p:["Velocità all'arrivo: v = √(2gh) = √25 = 5 m/s","Δp = 60 · 5 = 300 kg·m/s","Gambe tese: F = 300/0,01 = 30 000 N; piegate: 300/0,2 = 1500 N"],r:"30 000 N contro 1500 N: piegare le gambe riduce la forza di 20 volte"},
u3a:{q:"Una flebo è appesa 1 m sopra il braccio; la pressione venosa è circa 10 mmHg (1330 Pa). Il liquido entra? Quale altezza minima serve? (ρ = 1000 kg/m³)",p:["Pressione della colonna: ρgh = 1000·10·1 = 10 000 Pa ≈ 75 mmHg","75 mmHg > 10 mmHg: il liquido entra","Altezza minima: h = 1330/(1000·10) ≈ 0,13 m"],r:"sì; servono almeno circa 13 cm"},
u3b:{q:"Un sub con l'attrezzatura ha massa 80 kg e volume 0,082 m³. In mare (ρ = 1025 kg/m³) galleggia? Quanta zavorra serve per restare sospeso?",p:["Spinta = massa d'acqua spostata = 1025 · 0,082 ≈ 84 kg (×g)","84 kg > 80 kg: tende a galleggiare","Servono circa 4 kg di piombo (trascurando il suo volume)"],r:"galleggia; circa 4 kg di zavorra"},
u3c:{q:"L'aorta ha sezione 4 cm² e il sangue vi scorre a 25 cm/s; i capillari, tutti insieme, hanno 2500 cm². Portata e velocità nei capillari?",p:["Q = A·v = 4·10⁻⁴ m² · 0,25 m/s = 10⁻⁴ m³/s = 6 L/min","v_cap = Q/A = 10⁻⁴ / 0,25 = 4·10⁻⁴ m/s"],r:"6 L/min; 0,4 mm/s nei capillari"},
u3d:{q:"Un'arteriola si dilata e il suo raggio aumenta del 10%. Come cambiano resistenza e portata, a parità di Δp?",p:["R ∝ 1/r⁴","1,1⁴ = 1,21 · 1,21 ≈ 1,46","R diventa circa 1/1,46 ≈ 0,68 di prima; Q aumenta di 1,46 volte"],r:"resistenza −32%, portata +46%"},
u3e:{q:"Confronta la sovrappressione dentro una goccia d'acqua di raggio 1 mm e una di 0,1 mm (τ = 0,07 N/m).",p:["Δp = 2τ/r","r = 1 mm: 0,14/0,001 = 140 Pa","r = 0,1 mm: 0,14/0,0001 = 1400 Pa"],r:"140 Pa e 1400 Pa: raggio 10 volte più piccolo, pressione 10 volte più grande"},
u4a:{q:"Su una corda passano 5 creste in 2 s e due creste vicine distano 0,4 m. Frequenza, periodo e velocità dell'onda?",p:["f = 5/2 = 2,5 Hz","T = 1/f = 0,4 s","v = λ·f = 0,4 · 2,5"],r:"2,5 Hz; 0,4 s; 1 m/s"},
u4b:{q:"In un reparto rumoroso ci sono 90 dB; con i tappi si scende a 70 dB. Di quanto si riduce l'intensità? E se i macchinari da 90 dB diventano due?",p:["−20 dB = intensità divisa per 10² = 100","Due sorgenti uguali: intensità ×2 → +3 dB"],r:"intensità 100 volte minore; con due macchinari 93 dB"},
u4c:{q:"Una sonda ecografica a 5 MHz lavora nei tessuti (1540 m/s). Lunghezza d'onda? Un'eco torna dopo 130 µs: a che profondità è l'interfaccia?",p:["λ = v/f = 1540 / 5·10⁶ ≈ 3·10⁻⁴ m = 0,3 mm","Andata e ritorno: d = v·t/2 = 1540 · 130·10⁻⁶ / 2"],r:"circa 0,3 mm; circa 10 cm"},
u4d:{q:"Una massa di 0,5 kg appesa a una molla oscilla con periodo 0,5 s. Quanto vale la costante elastica? (π² ≈ 10)",p:["T = 2π√(m/k) → k = 4π²m/T²","k = 4·10·0,5 / 0,25"],r:"80 N/m"},
u5a:{q:"Un paziente di 70 kg passa da 39 a 37 °C sudando. Quanto calore perde (c ≈ 3500 J/(kg·K)) e quanto sudore deve evaporare (λ ≈ 2400 kJ/kg)?",p:["Q = c·m·ΔT = 3500 · 70 · 2 = 490 000 J","m_sudore = Q/λ = 490 kJ / 2400 kJ/kg ≈ 0,2 kg"],r:"circa 490 kJ; circa 0,2 L di sudore evaporato"},
u5b:{q:"Una bombola di ossigeno da 10 L è a 150 atm. A temperatura costante, quanti litri dà a 1 atm? Per quanto tempo a 2 L/min?",p:["Boyle: p₁V₁ = p₂V₂ → V₂ = 150 · 10 / 1 = 1500 L","Tempo = 1500 / 2 = 750 min"],r:"circa 1500 L; circa 12 ore e mezza (un po' meno: 10 L restano nella bombola)"},
u5c:{q:"Un gas si espande a pressione costante di 1·10⁵ Pa da 2 L a 6 L e intanto assorbe 1000 J. Quanto lavoro compie e come cambia la sua energia interna?",p:["L = p·ΔV = 10⁵ · 4·10⁻³ = 400 J","ΔU = Q − L = 1000 − 400"],r:"400 J di lavoro; ΔU = +600 J (la temperatura sale)"},
u5d:{q:"Un motore assorbe 2000 J a 500 K e cede 1400 J a 300 K per ciclo. Rendimento reale, rendimento massimo e variazione di entropia dell'universo?",p:["η = (2000 − 1400)/2000 = 30%","Carnot: 1 − 300/500 = 40%","ΔS = −2000/500 + 1400/300 = −4 + 4,67"],r:"30% contro 40% massimo; ΔS ≈ +0,67 J/K: ciclo irreversibile"},
u5e:{q:"Un neonato perde calore per irraggiamento: perché lo si mette in incubatrice con pareti calde e non solo con aria calda?",p:["L'irraggiamento netto dipende dalla differenza tra T⁴ della pelle e T⁴ delle superfici intorno","Pareti fredde → grande perdita anche se l'aria è calda","Pareti calde riducono la differenza e quindi la perdita"],r:"perché conta la temperatura delle superfici che lo circondano, non solo quella dell'aria"},
u6a:{q:"Un corpo ha carica +3,2 nC. Quanti elettroni gli mancano?",p:["n = Q/e","= 3,2·10⁻⁹ / 1,6·10⁻¹⁹"],r:"2·10¹⁰ elettroni"},
u6b:{q:"Un elettrone parte da fermo e attraversa una d.d.p. di 100 V. Energia acquistata e velocità finale? (m ≈ 9·10⁻³¹ kg)",p:["E = e·ΔV = 100 eV = 1,6·10⁻¹⁷ J","½mv² = E → v = √(2E/m) = √(3,2·10⁻¹⁷ / 9·10⁻³¹) ≈ √(3,6·10¹³)"],r:"100 eV; circa 6·10⁶ m/s"},
u6c:{q:"Due condensatori da 4 µF e 12 µF. Capacità equivalente in parallelo e in serie; in serie a 12 V, quanta carica ha ciascuno?",p:["Parallelo: 4 + 12 = 16 µF","Serie: 1/C = 1/4 + 1/12 = 4/12 → C = 3 µF","In serie la carica è uguale: Q = 3 µF · 12 V = 36 µC"],r:"16 µF; 3 µF; 36 µC su ciascuno"},
u6d:{q:"Una lampada da 60 W funziona a 230 V. Corrente, resistenza ed energia consumata in 5 ore?",p:["I = P/V = 60/230 ≈ 0,26 A","R = V²/P = 52 900/60 ≈ 880 Ω","E = 60 W · 5 h = 300 Wh"],r:"circa 0,26 A; circa 880 Ω; 0,3 kWh"},
u6e:{q:"Un protone (m = 1,67·10⁻²⁷ kg) a 10⁶ m/s entra perpendicolarmente in un campo di 0,1 T. Raggio della traiettoria?",p:["r = m·v/(q·B)","= 1,67·10⁻²⁷ · 10⁶ / (1,6·10⁻¹⁹ · 0,1) = 1,67·10⁻²¹ / 1,6·10⁻²⁰"],r:"circa 0,10 m"},
u7a:{q:"Un fotone X ha energia 30 keV. Quanto vale la sua lunghezza d'onda? (hc ≈ 1240 eV·nm)",p:["λ = hc/E = 1240 eV·nm / 30 000 eV","≈ 0,041 nm"],r:"circa 0,04 nm (4·10⁻¹¹ m): ionizzante"},
u7b:{q:"Un raggio passa dal vetro (n = 1,5) all'acqua (n = 1,33) con incidenza 60°. Esce o viene riflesso totalmente?",p:["Angolo limite: sin θ_L = 1,33/1,5 ≈ 0,89 → θ_L ≈ 62°","60° < 62°: il raggio esce","sin θ₂ = 1,5 · sin 60° / 1,33 ≈ 0,98 → θ₂ ≈ 78°"],r:"esce quasi radente (circa 78°); sopra i 62° sarebbe riflessione totale"},
u7c:{q:"Una lente da +5 diottrie forma l'immagine di un oggetto posto a 40 cm. Dove e com'è l'immagine?",p:["f = 1/5 m = 20 cm","1/q = 1/20 − 1/40 = 1/40 → q = 40 cm","m = −q/p = −1"],r:"a 40 cm, reale, capovolta, stessa grandezza (oggetto in 2f)"},
u7d:{q:"Uno standard di glucosio 2 mmol/L dà assorbanza 0,5; un campione nella stessa cuvetta dà 0,4. Concentrazione del campione?",p:["A = ε·c·l: con stessi ε e l, A ∝ c","c = 2 · 0,4/0,5"],r:"1,6 mmol/L"},
u7e:{q:"Lo iodio-131 ha emivita di 8 giorni. Quale frazione resta dopo 24 giorni? Dopo quanti giorni si scende sotto l'1%?",p:["24/8 = 3 emivite → 1/2³ = 1/8","2⁶ = 64 (1,6%), 2⁷ = 128 (0,8%)","7 emivite = 56 giorni"],r:"1/8 (12,5%); circa 56 giorni"}
};
Object.keys(FIS_PROB).forEach(id=>{const x=FIS_EXPL[id];if(x&&x.es)x.es.push(FIS_PROB[id]);});
FIS_TOPICS.forEach(t=>{const x=FIS_EXPL[t.id];if(x&&x.es)t.es=x.es;});

FIS_QB.push(
/* u1 metodi */
{t:"u1a",k:"m",q:"Quale delle seguenti NON è un'unità fondamentale del SI?",o:["metro","kilogrammo","secondo","newton","ampere"],a:3,s:"Il newton è derivato: kg·m/s²."},
{t:"u1a",k:"m",q:"L'unità SI della quantità di sostanza è:",o:["il kilogrammo","la mole","il litro","il kelvin","la candela"],a:1,s:"Una delle 7 unità fondamentali."},
{t:"u1a",k:"c",q:"Nel SI la temperatura si misura in ____.",a:["KELVIN","K"],s:"Il grado Celsius è ammesso ma non è l'unità fondamentale."},
{t:"u1a",k:"m",q:"Il joule espresso in unità fondamentali è:",o:["kg·m/s","kg·m²/s²","kg·m/s²","kg²·m/s","kg·m²/s"],a:1,s:"J = N·m = kg·m/s² · m."},
{t:"u1b",k:"m",q:"Una pressione di 120 mmHg (1 mmHg ≈ 133 Pa) vale circa:",o:["1,6 kPa","16 kPa","160 kPa","1,6 MPa","0,16 kPa"],a:1,s:"120 · 133 ≈ 16 000 Pa."},
{t:"u1b",k:"m",q:"Una portata cardiaca di 5 L/min espressa in m³/s è circa:",o:["8,3·10⁻⁵","8,3·10⁻³","5·10⁻³","0,083","300"],a:0,s:"5·10⁻³ m³ / 60 s ≈ 8,3·10⁻⁵ m³/s."},
{t:"u1b",k:"c",q:"Per passare da km/h a m/s si divide per ____ (scrivi il numero).",a:["3.6","3,6"],s:"1 km/h = 1000 m / 3600 s."},
{t:"u1b",k:"m",q:"(4·10⁻³)² vale:",o:["1,6·10⁻⁵","16·10⁻⁹","8·10⁻⁶","1,6·10⁻⁶","16·10⁻³"],a:0,s:"16·10⁻⁶ = 1,6·10⁻⁵."},
{t:"u1c",k:"m",q:"Due forze di 6 N e 8 N. Il modulo della loro risultante NON può essere:",o:["2 N","10 N","14 N","16 N","7 N"],a:3,s:"La risultante sta tra |6 − 8| = 2 N e 6 + 8 = 14 N."},
{t:"u1c",k:"m",q:"Un vettore di modulo 10 forma 60° con l'asse x. La sua componente x vale:",o:["5","8,7","10","0","6"],a:0,s:"10 · cos 60° = 5."},
{t:"u1c",k:"c",q:"La somma di due vettori uguali in modulo e direzione ma di verso opposto ha modulo ____.",a:["ZERO","0"],s:"Si annullano."},
{t:"u1c",k:"m",q:"Il prodotto scalare di due vettori paralleli e concordi di modulo 3 e 4 è:",o:["0","7","12","1","−12"],a:2,s:"3 · 4 · cos 0° = 12."},
{t:"u1d",k:"m",q:"Quale combinazione ha le dimensioni di una velocità?",o:["g·t²","√(g·h)","g/h","h/t²","m·g"],a:1,s:"√(L T⁻² · L) = L T⁻¹."},
{t:"u1d",k:"m",q:"Il numero di Reynolds Re = ρvd/η è:",o:["misurato in pascal","adimensionale","misurato in m/s","misurato in kg/m³","misurato in newton"],a:1,s:"Rapporto tra effetti inerziali e viscosi."},
{t:"u1d",k:"c",q:"La potenza ha dimensioni [M][L]²[T]^x: x vale ____.",a:["-3","−3"],s:"W = J/s = kg·m²·s⁻³."},
{t:"u1d",k:"m",q:"Quale grandezza ha le stesse dimensioni del lavoro?",o:["forza","potenza","energia cinetica","quantità di moto","pressione"],a:2,s:"Entrambe in joule."},
/* u2 meccanica */
{t:"u2a",k:"m",q:"Un corpo lasciato cadere da fermo percorre in 3 s (g = 10 m/s²):",o:["15 m","30 m","45 m","90 m","9 m"],a:2,s:"s = ½ g t² = 5 · 9."},
{t:"u2a",k:"m",q:"Partendo da fermo con a = 2 m/s², dopo 10 s la velocità è:",o:["5 m/s","10 m/s","20 m/s","100 m/s","200 m/s"],a:2,s:"v = a·t."},
{t:"u2a",k:"c",q:"Un oggetto lanciato verso l'alto a 20 m/s (g = 10) sale fino a ____ m.",a:["20","VENTI"],s:"h = v²/(2g) = 400/20."},
{t:"u2a",k:"m",q:"Nel grafico velocità-tempo di un moto uniformemente accelerato la pendenza della retta rappresenta:",o:["lo spazio percorso","l'accelerazione","la posizione iniziale","il tempo","la forza"],a:1,s:"Δv/Δt; l'area è invece lo spazio."},
{t:"u2b",k:"m",q:"In un moto circolare uniforme, raddoppiando la velocità a parità di raggio, l'accelerazione centripeta:",o:["raddoppia","quadruplica","si dimezza","resta uguale","aumenta di √2"],a:1,s:"a = v²/r."},
{t:"u2b",k:"m",q:"Nel punto più alto della traiettoria un proiettile lanciato a 45° (aria trascurabile) ha:",o:["velocità nulla","solo velocità orizzontale","solo velocità verticale","accelerazione nulla","velocità massima"],a:1,s:"v_y = 0, vₓ costante; l'accelerazione resta g."},
{t:"u2b",k:"c",q:"A parità di velocità iniziale, la gittata massima si ottiene lanciando a ____ gradi.",a:["45"],s:"sin(2θ) massimo per θ = 45°."},
{t:"u2b",k:"m",q:"Una centrifuga fa 50 giri al secondo. Il periodo è:",o:["50 s","0,02 s","0,2 s","2 s","0,5 s"],a:1,s:"T = 1/f = 1/50 s."},
{t:"u2c",k:"m",q:"Un corpo di 5 kg è fermo su un piano orizzontale. La reazione normale vale (g = 10):",o:["0","5 N","50 N","500 N","0,5 N"],a:2,s:"N = mg."},
{t:"u2c",k:"m",q:"La forza della Terra su una mela e quella della mela sulla Terra:",o:["la prima è molto maggiore","sono uguali in modulo e opposte","la seconda è nulla","si annullano perché agiscono sullo stesso corpo","dipendono dalla velocità"],a:1,s:"Terzo principio: agiscono su corpi diversi."},
{t:"u2c",k:"c",q:"Una molla con k = 200 N/m allungata di 5 cm esercita una forza di ____ N.",a:["10","DIECI"],s:"F = k·x = 200 · 0,05."},
{t:"u2c",k:"m",q:"Una cassa di 10 kg con coefficiente di attrito statico 0,5 (g = 10). La forza minima per smuoverla è:",o:["5 N","10 N","50 N","100 N","500 N"],a:2,s:"µₛ·N = 0,5 · 100."},
{t:"u2c",k:"m",q:"Un corpo si muove a velocità costante su un piano con attrito. La forza risultante su di esso è:",o:["nulla","uguale al peso","uguale all'attrito","nella direzione del moto","verso l'alto"],a:0,s:"Velocità costante → a = 0 (primo principio)."},
{t:"u2d",k:"m",q:"Un corpo di 4 kg che si muove a 3 m/s ha energia cinetica:",o:["6 J","12 J","18 J","36 J","24 J"],a:2,s:"½ · 4 · 9."},
{t:"u2d",k:"m",q:"Un corpo di 2 kg cade da 5 m (g = 10, aria trascurabile). Arriva a terra a:",o:["5 m/s","10 m/s","50 m/s","100 m/s","√5 m/s"],a:1,s:"v = √(2gh) = √100; la massa non conta."},
{t:"u2d",k:"c",q:"Il lavoro della forza peso lungo un percorso chiuso vale ____.",a:["ZERO","0","NULLO"],s:"Forza conservativa."},
{t:"u2d",k:"m",q:"Una forza di 10 N sposta un corpo di 3 m formando 60° con lo spostamento. Il lavoro è:",o:["30 J","15 J","26 J","0 J","5 J"],a:1,s:"L = F·s·cos 60° = 30 · 0,5."},
{t:"u2d",k:"c",q:"1 kWh corrisponde a ____ MJ.",a:["3.6","3,6"],s:"1000 W · 3600 s = 3,6·10⁶ J."},
{t:"u2e",k:"m",q:"Una forza di 20 N applicata perpendicolarmente a 0,5 m dal fulcro produce un momento di:",o:["10 N·m","40 N·m","20,5 N·m","0,025 N·m","100 N·m"],a:0,s:"M = F·b."},
{t:"u2e",k:"m",q:"Nella leva di secondo genere:",o:["il fulcro sta tra forza e resistenza","la resistenza sta tra fulcro e forza","la forza sta tra fulcro e resistenza","il vantaggio è sempre minore di 1","non c'è mai equilibrio"],a:1,s:"Carriola, punta dei piedi: sempre vantaggiosa."},
{t:"u2e",k:"c",q:"Un corpo appoggiato è stabile se la verticale passante per il ____ cade dentro la base d'appoggio.",a:["BARICENTRO","CENTRODIMASSA","CENTRODIGRAVITA"],s:"Per questo con le stampelle si allarga la base."},
{t:"u2e",k:"m",q:"Un peso di 60 N sta a 1 m dal fulcro di un'asta. Dall'altra parte, a 3 m, per l'equilibrio serve una forza di:",o:["20 N","60 N","180 N","30 N","10 N"],a:0,s:"60 · 1 = F · 3."},
{t:"u2f",k:"m",q:"Un pattinatore di 50 kg, fermo, lancia una palla di 1 kg a 10 m/s. Rincula a:",o:["0,2 m/s","2 m/s","10 m/s","0,02 m/s","5 m/s"],a:0,s:"0 = 1·10 − 50·v → v = 0,2 m/s."},
{t:"u2f",k:"m",q:"L'unità di misura dell'impulso è:",o:["N","N·s","J","W","N/s"],a:1,s:"Impulso = F·Δt = Δp (kg·m/s)."},
{t:"u2f",k:"c",q:"In un urto completamente anelastico i corpi dopo l'urto si muovono ____ (una parola).",a:["UNITI","INSIEME","ATTACCATI"],s:"Stessa velocità finale."},
{t:"u2f",k:"m",q:"Una forza di 50 N agisce per 0,2 s su un corpo fermo di 2 kg. La velocità finale è:",o:["2,5 m/s","5 m/s","10 m/s","20 m/s","50 m/s"],a:1,s:"Impulso 10 N·s = 2 · v."},
/* u3 fluidi */
{t:"u3a",k:"m",q:"Una forza di 100 N su un'area di 2 cm² esercita una pressione di:",o:["50 Pa","5·10⁵ Pa","200 Pa","5·10³ Pa","2·10⁴ Pa"],a:1,s:"100 / 2·10⁻⁴ m²."},
{t:"u3a",k:"m",q:"A quale profondità in acqua la pressione assoluta è circa 3 atm?",o:["10 m","20 m","30 m","3 m","300 m"],a:1,s:"1 atm in superficie + 1 atm ogni 10 m."},
{t:"u3a",k:"c",q:"In un torchio idraulico con pistoni di 10 cm² e 1000 cm² la forza viene moltiplicata per ____.",a:["100","CENTO"],s:"Rapporto delle aree."},
{t:"u3a",k:"m",q:"In vasi comunicanti che contengono lo stesso liquido, il livello:",o:["è più alto nel vaso più largo","è più alto nel vaso più stretto","è lo stesso in tutti","dipende dalla forma","dipende dalla quantità"],a:2,s:"Stevino: stessa pressione alla stessa profondità."},
{t:"u3b",k:"m",q:"Un cubo di 1 dm³ completamente immerso in acqua riceve una spinta di (g = 10):",o:["1 N","10 N","100 N","0,1 N","1000 N"],a:1,s:"1 dm³ d'acqua = 1 kg → 10 N."},
{t:"u3b",k:"m",q:"Un corpo galleggia in acqua con metà del volume immerso. La sua densità è:",o:["250 kg/m³","500 kg/m³","1000 kg/m³","2000 kg/m³","1500 kg/m³"],a:1,s:"Frazione immersa = ρ_corpo/ρ_acqua."},
{t:"u3b",k:"c",q:"Un oggetto pesa 30 N in aria e 20 N in acqua: la spinta di Archimede vale ____ N.",a:["10","DIECI"],s:"Peso apparente = peso − spinta."},
{t:"u3b",k:"m",q:"Lo stesso blocco di legno galleggia in acqua dolce e poi in acqua salata. In acqua salata:",o:["affonda di più","emerge un po' di più","la spinta supera il peso","affonda del tutto","non cambia nulla"],a:1,s:"Densità maggiore → basta meno volume immerso."},
{t:"u3c",k:"m",q:"In un tubo la sezione si riduce a un terzo. La velocità del fluido ideale:",o:["si riduce a un terzo","triplica","resta uguale","aumenta di 9 volte","si annulla"],a:1,s:"A·v costante."},
{t:"u3c",k:"m",q:"In un aneurisma (dilatazione dell'arteria) il sangue:",o:["accelera e la pressione sulla parete cala","rallenta e la pressione sulla parete aumenta","si ferma","è sempre turbolento","non cambia"],a:1,s:"Continuità + Bernoulli: la dilatazione tende a peggiorare."},
{t:"u3c",k:"c",q:"Nel SI la portata si misura in metri cubi al ____.",a:["SECONDO"],s:"m³/s."},
{t:"u3c",k:"m",q:"In un tubo orizzontale l'acqua va a 1 m/s nel punto A e a 3 m/s nel punto B. La pressione in A rispetto a B è:",o:["minore di 4000 Pa","maggiore di 4000 Pa","uguale","maggiore di 2000 Pa","maggiore di 9000 Pa"],a:1,s:"½·1000·(9 − 1) = 4000 Pa."},
{t:"u3d",k:"m",q:"Raddoppiando la lunghezza di un tubo (stessi raggio e Δp), la portata di Poiseuille:",o:["raddoppia","si dimezza","diventa 1/16","resta uguale","quadruplica"],a:1,s:"Q ∝ 1/l."},
{t:"u3d",k:"m",q:"Raddoppiando sia il raggio sia la lunghezza di un tubo (stessa Δp), la portata:",o:["raddoppia","aumenta di 8 volte","aumenta di 16 volte","resta uguale","si dimezza"],a:1,s:"16 (r⁴) / 2 (l) = 8."},
{t:"u3d",k:"m",q:"Tre vasi uguali, ciascuno con resistenza R, collegati in serie hanno resistenza totale:",o:["R/3","R","3R","9R","R/9"],a:2,s:"In serie si sommano."},
{t:"u3d",k:"c",q:"Un numero di Reynolds molto alto indica un moto ____.",a:["TURBOLENTO"],s:"Sotto circa 2000 è laminare."},
{t:"u3d",k:"c",q:"L'unità SI della viscosità è il pascal per ____.",a:["SECONDO"],s:"Pa·s."},
{t:"u3e",k:"m",q:"Un insetto cammina sull'acqua grazie:",o:["alla spinta di Archimede","alla tensione superficiale","alla viscosità","alla pressione atmosferica","alla capillarità"],a:1,s:"La superficie si comporta come una membrana tesa."},
{t:"u3e",k:"m",q:"Un detergente aggiunto all'acqua:",o:["aumenta la tensione superficiale","riduce la tensione superficiale","non cambia nulla","aumenta la densità","fa salire di più l'acqua nei capillari"],a:1,s:"È un tensioattivo, come il surfattante."},
{t:"u3e",k:"c",q:"Dimezzando il raggio di un capillare, l'altezza a cui sale l'acqua ____ (raddoppia/dimezza).",a:["RADDOPPIA"],s:"h ∝ 1/r."},
/* u4 onde */
{t:"u4a",k:"m",q:"Un suono di 340 Hz in aria (340 m/s) ha lunghezza d'onda:",o:["1 m","0,1 m","10 m","340 m","1/340 m"],a:0,s:"λ = v/f."},
{t:"u4a",k:"m",q:"Il suono NON si propaga:",o:["nell'acqua","nell'aria","nel vuoto","nelle ossa","nei metalli"],a:2,s:"Serve un mezzo materiale."},
{t:"u4a",k:"c",q:"Nelle onde ____ le particelle oscillano nella stessa direzione di propagazione.",a:["LONGITUDINALI"],s:"Come il suono nei fluidi."},
{t:"u4a",k:"m",q:"Se la frequenza di un'onda raddoppia nello stesso mezzo, la lunghezza d'onda:",o:["raddoppia","si dimezza","resta uguale","quadruplica","si annulla"],a:1,s:"v = λf fissa."},
{t:"u4b",k:"m",q:"Un suono di 80 dB rispetto a uno di 50 dB ha intensità:",o:["30 volte maggiore","300 volte maggiore","1000 volte maggiore","1,6 volte maggiore","3 volte maggiore"],a:2,s:"30 dB = fattore 10³."},
{t:"u4b",k:"m",q:"A 1 m da una sorgente l'intensità è 10⁻⁴ W/m². A 10 m vale:",o:["10⁻⁵ W/m²","10⁻⁶ W/m²","10⁻³ W/m²","10⁻⁸ W/m²","10⁻⁴ W/m²"],a:1,s:"Distanza ×10 → intensità ÷100."},
{t:"u4b",k:"c",q:"L'intensità sonora si misura in watt al metro ____.",a:["QUADRO","QUADRATO"],s:"W/m²."},
{t:"u4c",k:"m",q:"L'effetto Doppler si osserva:",o:["solo con la luce","solo con il suono","con tutte le onde, quando sorgente e osservatore si muovono l'uno rispetto all'altro","solo nel vuoto","solo se la sorgente è ferma"],a:2,s:"Anche con la luce (spostamento verso il rosso)."},
{t:"u4c",k:"m",q:"Nell'ecodoppler, il sangue che si allontana dalla sonda produce un'eco di frequenza:",o:["maggiore di quella emessa","minore di quella emessa","uguale","nulla","doppia"],a:1,s:"Allontanamento → frequenza minore."},
{t:"u4c",k:"c",q:"L'esame che usa l'effetto Doppler degli ultrasuoni per studiare il flusso del sangue si chiama ____.",a:["ECODOPPLER","ECOCOLORDOPPLER","DOPPLER"],s:"Misura velocità e verso del flusso."},
{t:"u4d",k:"m",q:"Una massa di 2 kg su una molla oscilla con periodo π/5 s. La costante elastica è:",o:["50 N/m","100 N/m","200 N/m","400 N/m","20 N/m"],a:2,s:"k = 4π²m/T² = 4π²·2/(π²/25) = 200 N/m."},
{t:"u4d",k:"m",q:"Due onde identiche si sovrappongono in opposizione di fase. L'ampiezza risultante è:",o:["doppia","nulla","uguale","metà","quadrupla"],a:1,s:"Interferenza distruttiva."},
{t:"u4d",k:"c",q:"Il periodo di un oscillatore armonico ____ dipende dall'ampiezza (scrivi «non» o «sì»).",a:["NON"],s:"Isocronismo."},
{t:"u4d",k:"m",q:"Un'oscillazione ha periodo 2 s. La sua pulsazione ω vale:",o:["π rad/s","2π rad/s","π/2 rad/s","4π rad/s","1 rad/s"],a:0,s:"ω = 2π/T."},
/* u5 termodinamica */
{t:"u5a",k:"m",q:"Quanto calore serve per scaldare 2 kg d'acqua da 20 a 70 °C? (c = 4,2 kJ/(kg·K))",o:["42 kJ","210 kJ","420 kJ","840 kJ","100 kJ"],a:2,s:"4,2 · 2 · 50."},
{t:"u5a",k:"m",q:"Durante l'ebollizione a pressione costante, se si fornisce calore la temperatura dell'acqua:",o:["aumenta","diminuisce","resta costante","oscilla","raddoppia"],a:2,s:"Il calore va nel passaggio di stato (calore latente)."},
{t:"u5a",k:"c",q:"37 °C corrispondono a circa ____ K.",a:["310"],s:"37 + 273."},
{t:"u5a",k:"m",q:"Si mescolano 1 kg d'acqua a 10 °C e 3 kg a 50 °C. La temperatura finale è:",o:["20 °C","30 °C","40 °C","45 °C","25 °C"],a:2,s:"(1·10 + 3·50)/4."},
{t:"u5b",k:"m",q:"Una mole di gas perfetto a 0 °C e 1 atm occupa:",o:["1 L","22,4 L","2,24 L","224 L","8,31 L"],a:1,s:"Volume molare in condizioni normali."},
{t:"u5b",k:"m",q:"A volume costante la temperatura di un gas passa da 300 K a 600 K. La pressione:",o:["raddoppia","si dimezza","resta uguale","quadruplica","aumenta di √2"],a:0,s:"p/T costante."},
{t:"u5b",k:"c",q:"Un gas a 27 °C si trova alla temperatura assoluta di ____ K.",a:["300"],s:"27 + 273."},
{t:"u5b",k:"m",q:"Nell'inspirazione il volume dei polmoni aumenta; a temperatura costante la pressione interna:",o:["aumenta","scende sotto quella atmosferica e l'aria entra","resta uguale","diventa zero","raddoppia"],a:1,s:"Boyle."},
{t:"u5c",k:"m",q:"In una trasformazione isoterma di un gas perfetto:",o:["ΔU = 0 e Q = L","Q = 0","L = 0","ΔU = Q","la pressione è costante"],a:0,s:"L'energia interna dipende solo da T."},
{t:"u5c",k:"m",q:"In un'espansione adiabatica un gas:",o:["si scalda","si raffredda","mantiene la temperatura","assorbe calore","cede calore"],a:1,s:"ΔU = −L < 0."},
{t:"u5c",k:"c",q:"In un ciclo termodinamico completo la variazione di energia interna è ____.",a:["ZERO","NULLA","0"],s:"Si torna allo stato iniziale."},
{t:"u5c",k:"m",q:"Nel piano p-V il lavoro di una trasformazione è rappresentato da:",o:["la pendenza della curva","l'area sotto la curva","la lunghezza della curva","il punto finale","l'intercetta"],a:1,s:"L = ∫p dV."},
{t:"u5d",k:"m",q:"Una macchina termica con rendimento del 100%:",o:["è possibile se reversibile","è impossibile per il secondo principio","esiste nei motori moderni","è la macchina di Carnot","si ottiene a 0 °C"],a:1,s:"Enunciato di Kelvin."},
{t:"u5d",k:"m",q:"Una trasformazione reversibile:",o:["aumenta sempre l'entropia dell'universo","lascia invariata l'entropia dell'universo","la diminuisce","avviene rapidamente","ha attriti"],a:1,s:"Le irreversibili la aumentano."},
{t:"u5d",k:"c",q:"Secondo l'interpretazione statistica, l'entropia cresce con il numero di ____ microscopici compatibili con lo stato macroscopico.",a:["STATI","MICROSTATI","MODI"],s:"Boltzmann: S = k ln W."},
{t:"u5d",k:"m",q:"1000 J di calore passano da un corpo a 400 K a uno a 200 K. La variazione di entropia totale è:",o:["−2,5 J/K","0","+2,5 J/K","+5 J/K","−5 J/K"],a:2,s:"−1000/400 + 1000/200 = −2,5 + 5."},
{t:"u5e",k:"m",q:"In inverno una maniglia di metallo sembra più fredda del legno alla stessa temperatura perché:",o:["è davvero più fredda","conduce meglio il calore e lo sottrae più in fretta alla mano","irraggia di più","fa più convezione","ha calore specifico nullo"],a:1,s:"Conta la conducibilità."},
{t:"u5e",k:"m",q:"Una coperta tiene caldo soprattutto perché:",o:["produce calore","intrappola aria, che conduce poco","riflette i raggi X","aumenta la convezione","ha alta conducibilità"],a:1,s:"L'aria ferma è un ottimo isolante."},
{t:"u5e",k:"c",q:"La conducibilità termica dei metalli è ____ di quella dell'aria (maggiore/minore).",a:["MAGGIORE"],s:"Migliaia di volte maggiore."},
/* u6 elettricità e magnetismo */
{t:"u6a",k:"m",q:"Due cariche si attraggono con forza F. Raddoppiando entrambe le cariche e la distanza, la forza diventa:",o:["F","2F","4F","F/4","16F"],a:0,s:"×4 per le cariche, ÷4 per la distanza."},
{t:"u6a",k:"m",q:"Strofinando una bacchetta di vetro con un panno di seta, il vetro si carica positivamente perché:",o:["acquista protoni","perde elettroni","perde protoni","acquista neutroni","crea carica"],a:1,s:"Si spostano solo gli elettroni; la carica si conserva."},
{t:"u6a",k:"c",q:"Nel SI la carica elettrica si misura in ____.",a:["COULOMB","C"],s:"1 C = 1 A·s."},
{t:"u6b",k:"m",q:"Le linee del campo elettrico:",o:["escono dalle cariche negative","escono dalle cariche positive ed entrano nelle negative","sono sempre chiuse","si incrociano","sono parallele alle equipotenziali"],a:1,s:"Sono perpendicolari alle equipotenziali."},
{t:"u6b",k:"m",q:"Tra due armature distanti 2 mm con una d.d.p. di 10 V il campo vale:",o:["5 V/m","20 V/m","5000 V/m","0,2 V/m","20 000 V/m"],a:2,s:"E = V/d = 10/0,002."},
{t:"u6b",k:"c",q:"Spostare una carica lungo una superficie equipotenziale richiede un lavoro ____.",a:["NULLO","ZERO","0"],s:"ΔV = 0."},
{t:"u6b",k:"m",q:"Il campo di una carica puntiforme, a distanza doppia, diventa:",o:["la metà","un quarto","il doppio","uguale","un ottavo"],a:1,s:"E ∝ 1/r²."},
{t:"u6c",k:"m",q:"Raddoppiando la distanza tra le armature di un condensatore piano, la capacità:",o:["raddoppia","si dimezza","quadruplica","resta uguale","si annulla"],a:1,s:"C = ε₀εᵣA/d."},
{t:"u6c",k:"m",q:"Un condensatore da 10 µF caricato a 100 V immagazzina:",o:["0,05 J","0,5 J","1 J","0,1 J","5 J"],a:0,s:"½ · 10⁻⁵ · 10⁴."},
{t:"u6c",k:"c",q:"L'unità di misura della capacità è il ____.",a:["FARAD","F"],s:"1 F = 1 C/V."},
{t:"u6c",k:"m",q:"Inserendo un dielettrico in un condensatore che resta collegato alla pila, la carica sulle armature:",o:["diminuisce","aumenta","resta uguale","si annulla","cambia segno"],a:1,s:"C aumenta e V è fissata: Q = CV aumenta."},
{t:"u6d",k:"m",q:"Un filo ha resistenza R. Un filo dello stesso materiale, lungo il doppio e con sezione doppia, ha resistenza:",o:["R","2R","R/2","4R","R/4"],a:0,s:"R = ρl/A: ×2 e ÷2."},
{t:"u6d",k:"m",q:"Tre resistenze da 30 Ω in parallelo equivalgono a:",o:["90 Ω","10 Ω","30 Ω","3 Ω","60 Ω"],a:1,s:"30/3."},
{t:"u6d",k:"c",q:"Una resistenza da 10 Ω percorsa da 2 A dissipa ____ W.",a:["40","QUARANTA"],s:"P = R·I²."},
{t:"u6d",k:"m",q:"Due lampadine uguali in serie a una pila: se una si brucia (circuito aperto), l'altra:",o:["si spegne","brilla di più","brilla uguale","brilla meno ma resta accesa","si brucia"],a:0,s:"In serie la corrente è unica: il circuito si interrompe."},
{t:"u6e",k:"m",q:"Una carica si muove parallela alle linee di un campo magnetico uniforme. La forza magnetica è:",o:["massima","nulla","uguale a qvB","diretta come B","opposta a v"],a:1,s:"sin 0° = 0."},
{t:"u6e",k:"m",q:"Un filo lungo 0,5 m percorso da 4 A è perpendicolare a un campo di 0,2 T. La forza sul filo è:",o:["0,4 N","0,1 N","4 N","0,8 N","2 N"],a:0,s:"F = I·l·B."},
{t:"u6e",k:"c",q:"Secondo la legge di ____ la corrente indotta si oppone alla variazione di flusso che l'ha generata.",a:["LENZ"],s:"È il segno meno della legge di Faraday-Neumann."},
{t:"u6e",k:"m",q:"Avvicinando un magnete a una spira ferma:",o:["non succede nulla","si induce una corrente nella spira","la spira si carica elettricamente","il magnete si smagnetizza","la spira si scalda senza corrente"],a:1,s:"Il flusso cambia."},
/* u7 radiazioni */
{t:"u7a",k:"m",q:"In ordine di frequenza crescente:",o:["raggi X, visibile, microonde","microonde, visibile, raggi X","visibile, microonde, raggi X","microonde, raggi X, visibile","hanno tutte la stessa frequenza"],a:1,s:"Radio < microonde < IR < visibile < UV < X < γ."},
{t:"u7a",k:"m",q:"Raddoppiando la frequenza di un fotone, la sua energia:",o:["raddoppia","si dimezza","quadruplica","resta uguale","aumenta di √2"],a:0,s:"E = hf."},
{t:"u7a",k:"c",q:"Le radiazioni capaci di strappare elettroni agli atomi si dicono ____.",a:["IONIZZANTI"],s:"X, γ, UV di alta energia."},
{t:"u7a",k:"m",q:"Quale radiazione è NON ionizzante?",o:["raggi X","raggi gamma","microonde","UV di alta energia","particelle alfa"],a:2,s:"Il singolo fotone ha troppa poca energia."},
{t:"u7b",k:"m",q:"L'angolo limite tra un mezzo con n = 2 e l'aria è:",o:["30°","45°","60°","90°","0°"],a:0,s:"sin θ_L = 1/2."},
{t:"u7b",k:"m",q:"Passando dall'aria all'acqua, la frequenza della luce:",o:["aumenta","diminuisce","resta uguale","si annulla","raddoppia"],a:2,s:"Cambiano velocità e lunghezza d'onda."},
{t:"u7b",k:"c",q:"Entrando in un mezzo con indice di rifrazione maggiore, il raggio si ____ alla normale (avvicina/allontana).",a:["AVVICINA"],s:"Snell."},
{t:"u7c",k:"m",q:"Un oggetto alto 2 cm è a 30 cm da una lente convergente con f = 10 cm. L'immagine è alta:",o:["1 cm","2 cm","4 cm","0,5 cm","6 cm"],a:0,s:"q = 15 cm, ingrandimento −15/30 = −0,5: 1 cm, capovolta."},
{t:"u7c",k:"m",q:"Una lente da +2,5 diottrie ha distanza focale:",o:["2,5 m","40 cm","25 cm","4 m","2,5 cm"],a:1,s:"f = 1/2,5 m."},
{t:"u7c",k:"c",q:"Se l'oggetto è nel fuoco di una lente convergente, l'immagine si forma all'____.",a:["INFINITO"],s:"I raggi escono paralleli."},
{t:"u7d",k:"m",q:"Uno strato trasmette il 50% della luce. Raddoppiando lo spessore, la trasmittanza diventa:",o:["25%","0%","100%","75%","12,5%"],a:0,s:"0,5 · 0,5."},
{t:"u7d",k:"m",q:"Una soluzione trasmette il 10% della luce. La sua assorbanza è:",o:["0,1","1","10","2","0,9"],a:1,s:"A = log(1/0,1)."},
{t:"u7d",k:"c",q:"Attraversando un mezzo assorbente l'intensità della luce cala in modo ____ con lo spessore.",a:["ESPONENZIALE"],s:"I = I₀·e^(−µx)."},
{t:"u7e",k:"m",q:"Nel decadimento β⁻ il numero atomico:",o:["aumenta di 1","diminuisce di 1","diminuisce di 2","resta uguale","aumenta di 2"],a:0,s:"Un neutrone diventa protone."},
{t:"u7e",k:"m",q:"Quale radiazione è fermata da un foglio di carta?",o:["alfa","beta","gamma","raggi X","neutroni"],a:0,s:"Poco penetrante, ma molto dannosa se inalata o ingerita."},
{t:"u7e",k:"c",q:"Dopo 3 tempi di dimezzamento resta 1/____ dei nuclei iniziali.",a:["8","OTTO"],s:"1/2³."},
{t:"u7e",k:"m",q:"Un campione ha attività 1600 Bq. Dopo 4 emivite l'attività è:",o:["400 Bq","200 Bq","100 Bq","50 Bq","0 Bq"],a:2,s:"1600/16."}
);
