/* ================= TEST D'INGRESSO: perché la risposta è giusta e perché le altre sono sbagliate =================
   Per ogni domanda (stesso ordine di FIS_PT, CHI_PT, BIO_PT): t = argomento da ripassare, s = spiegazione della risposta giusta,
   e = per ciascuna opzione (nell'ordine originale) il ragionamento sbagliato che porta a sceglierla ("" per quella giusta). */
const PT_EXPL={
fis:[
 ["u1b","36 km/h = 36 000 m / 3600 s = 10 m/s: per passare da km/h a m/s si divide per 3,6.",["Hai diviso per 10 invece che per 3,6.","","Hai lasciato il numero invariato: km/h e m/s non sono la stessa unità.","Hai moltiplicato invece di dividere.","Hai diviso per 36: il fattore giusto è 3,6."]],
 ["u1b","Si moltiplicano i numeri (3·2 = 6) e si sommano gli esponenti (4 + (−2) = 2): 6·10².",["","Hai moltiplicato gli esponenti (4 · −2 = −8): nel prodotto di potenze si sommano.","Hai sommato i numeri (3 + 2) invece di moltiplicarli.","Hai sottratto gli esponenti (4 − (−2) = 6): si sommano.","Hai dimenticato le potenze di 10."]],
 ["u2a","In caduta libera agisce solo il peso: l'accelerazione è g ≈ 9,8 m/s², costante e uguale per tutti i corpi.",["Aumenta la velocità, non l'accelerazione.","","Diminuirebbe solo con l'attrito dell'aria, qui trascurato.","È zero solo se il corpo si muove a velocità costante.","Galileo: senza aria tutti i corpi cadono con la stessa accelerazione."]],
 ["u2c","Secondo principio: a = F/m = 10/2 = 5 m/s².",["Hai moltiplicato F · m: si divide.","","Hai diviso m/F: è al contrario.","Hai sommato forza e massa.","Hai sottratto: non ha senso fisico."]],
 ["u3a","La pressione è la forza che agisce perpendicolarmente su ogni unità di superficie: p = F/A (pascal = N/m²).",["Con il prodotto, a parità di forza, più area darebbe più pressione: è il contrario (lo sci non affonda nella neve).","","Formula rovesciata.","massa × altezza non è una pressione (manca anche g e la densità).","densità/volume non ha le dimensioni di una pressione."]],
 ["u3b","Un corpo immerso affonda se il suo peso supera la spinta di Archimede, cioè se è più denso del liquido.",["","La spinta c'è sempre, ma è minore del peso.","Anche il legno ha massa, eppure galleggia.","Anche il ghiaccio è solido e galleggia.","L'incomprimibilità non decide il galleggiamento."]],
 ["u4a","In un periodo l'onda avanza di una lunghezza d'onda: v = λ/T = λ·f.",["Avresti velocità diviso frequenza: le unità non tornano (m·s).","","Formula rovesciata: dimensioni sbagliate (1/(m·s)).","Non si sommano grandezze con unità diverse.","Il quadrato di λ non c'entra."]],
 ["u4a","La frequenza è il numero di oscillazioni al secondo: si misura in hertz (1 Hz = 1/s).",["In metri si misura la lunghezza d'onda.","In secondi si misura il periodo, l'inverso della frequenza.","","Il decibel misura il livello di intensità sonora.","Il watt misura la potenza."]],
 ["u5a","T(K) = t(°C) + 273,15: lo zero assoluto è −273,15 °C, la temperatura più bassa possibile.",["0 °C è la fusione del ghiaccio, cioè 273 K.","","Hai sbagliato il segno: 273 °C sono 546 K.","Valore inventato: lo zero assoluto è molto più in basso.","100 °C è l'ebollizione dell'acqua (373 K)."]],
 ["u5b","A volume costante p/T è costante (Gay-Lussac): se T assoluta raddoppia, raddoppia anche p.",["Proporzionalità inversa: vale per p e V a temperatura costante, non qui.","","La pressione resta uguale solo se la temperatura non cambia.","Il quadrato non c'entra: la relazione è lineare.","La pressione si annulla solo allo zero assoluto."]],
 ["u6a","Cariche dello stesso segno si respingono, di segno opposto si attraggono (legge di Coulomb).",["Si attraggono le cariche di segno opposto.","","Interagiscono sempre, con forza che cala come 1/r².","Le cariche non si annullano: si sommano algebricamente solo se stanno sullo stesso corpo.","La forza elettrica dipende dalle cariche, non dalle masse."]],
 ["u6d","Legge di Ohm: la tensione ai capi di un conduttore è proporzionale alla corrente, V = R·I.",["","Formula rovesciata: R = V/I, non V = R/I.","Le unità non tornano: I = V/R.","R = V/I, non V·I.","Questa sarebbe una potenza scritta male: P = R·I²."]],
 ["u7b","Il vetro ha un indice di rifrazione diverso per ogni colore: i colori si rifrangono con angoli diversi e si separano (dispersione).",["La luce attraversa il vetro trasparente.","","Il rosso è solo uno dei colori che compongono la luce bianca.","Un prisma rifrange; la riflessione totale avviene solo in condizioni particolari.","Nel vetro la luce rallenta (v = c/n)."]],
 ["u7b","Legge della riflessione: angolo di riflessione = angolo di incidenza, misurati entrambi dalla normale.",["Il doppio non ha alcun fondamento.","","La metà non ha alcun fondamento.","90° è la direzione della superficie, non l'angolo di riflessione.","Zero solo se la luce arriva perpendicolare."]]
],
chi:[
 ["c1a","Z = 6 vuol dire 6 protoni; in un atomo neutro gli elettroni sono uguali ai protoni: 6.",["4 sono gli elettroni di valenza, non tutti gli elettroni.","","12 è il numero di massa del carbonio-12 (protoni + neutroni).","14 è il numero di massa del carbonio-14.","8 è lo Z dell'ossigeno."]],
 ["c1b","Na cede un elettrone a Cl: si formano Na⁺ e Cl⁻ tenuti insieme dall'attrazione elettrostatica, il legame ionico (grande differenza di elettronegatività).",["Il covalente puro unisce atomi uguali (come in Cl₂).","","Il legame metallico c'è nei metalli puri e nelle leghe.","Il legame idrogeno è un'interazione tra molecole, non un legame che forma il sale.","Le forze di van der Waals sono deboli e tra molecole."]],
 ["c2b","Molarità = moli di soluto per litro di soluzione.",["Grammi per litro sono una concentrazione in massa, non in moli.","","Si riferisce al solvente (ed è la molalità), non al soluto.","È una percentuale p/v (1%).","Non c'entra la quantità di solvente."]],
 ["c2c","L'acqua distillata è ipotonica: l'acqua entra nel globulo rosso per osmosi, che si gonfia fino a rompersi (emolisi).",["Raggrinzisce in una soluzione ipertonica.","","L'osmosi avviene sempre se le concentrazioni sono diverse.","Entrando acqua diventa meno denso, non più denso.","I globuli rossi non si dividono."]],
 ["c3a","Il catalizzatore abbassa l'energia di attivazione: accelera la reazione e alla fine si ritrova intatto.",["Non si consuma: si ritrova uguale alla fine.","","Non sposta l'equilibrio: lo fa solo raggiungere prima.","Non fornisce energia: offre un percorso con barriera più bassa.","È il contrario (quelli che rallentano sono gli inibitori)."]],
 ["c3a","Una reazione bilanciata ha lo stesso numero di atomi di ciascun elemento nei due membri (conservazione della massa).",["Il numero di molecole può cambiare (2 H₂ + O₂ → 2 H₂O: 3 molecole diventano 2).","","Si conservano le masse totali, non le masse molari.","Servono reagenti e prodotti.","Il catalizzatore non c'entra con il bilanciamento."]],
 ["c4a","pH < 7 vuol dire soluzione acida; pH 3 corrisponde a [H₃O⁺] = 10⁻³ M.",["Basica vuol dire pH sopra 7.","Neutra è pH 7.","","Il tampone è un tipo di soluzione, non una zona del pH.","«Satura» riguarda la solubilità, non l'acidità."]],
 ["c4c","Ossidazione = perdita di elettroni (il numero di ossidazione aumenta). Riduzione = acquisto.",["Acquistare elettroni è la riduzione.","","Acquistare protoni riguarda acidi e basi (Brønsted).","I neutroni stanno nel nucleo: le reazioni chimiche non li toccano.","Nell'ossidazione qualcosa cambia sempre."]],
 ["c5b","CH₄ ha solo legami singoli C–H: è il più semplice degli alcani (CₙH₂ₙ₊₂).",["Gli alcheni hanno un doppio legame C=C: servono almeno 2 carboni.","","Gli alcoli hanno il gruppo –OH.","Gli acidi carbossilici hanno –COOH.","Gli aromatici hanno un anello come il benzene."]],
 ["c5a","Isomeri: stessa formula molecolare ma atomi disposti in modo diverso (butano e isobutano: C₄H₁₀).",["","Con formule diverse sono sostanze diverse, non isomeri.","Se la struttura è uguale è la stessa molecola.","Il nome segue la struttura: isomeri diversi hanno nomi diversi.","Gli isomeri hanno di solito proprietà diverse."]],
 ["c6a","Il gruppo ossidrile –OH legato a un carbonio sp³ caratterizza gli alcoli (etanolo, glicerolo).",["","Le ammine hanno –NH₂.","Gli esteri hanno –COO–.","Gli alcani hanno solo C e H.","I chetoni hanno C=O tra due carboni."]],
 ["c6c","–COOH è il gruppo carbossilico: acidi carbossilici (acido acetico, acidi grassi, amminoacidi).",["Le aldeidi hanno –CHO.","","Gli eteri hanno C–O–C.","Le ammine hanno –NH₂.","Gli alcoli hanno solo –OH."]],
 ["c7a","Le proteine sono catene di amminoacidi uniti da legami peptidici.",["I nucleotidi formano gli acidi nucleici (DNA, RNA).","","Il glucosio forma amido, glicogeno e cellulosa.","Gli acidi grassi formano i lipidi.","Il glicerolo fa parte dei trigliceridi e dei fosfolipidi."]],
 ["c7d","Il DNA contiene 2-deossiribosio (senza l'OH in posizione 2'); l'RNA contiene ribosio.",["Il glucosio è un esoso: non sta negli acidi nucleici.","Il ribosio è lo zucchero dell'RNA.","","Il fruttosio è uno zucchero della frutta.","Il lattosio è lo zucchero del latte, un disaccaride."]]
],
bio:[
 ["b1a","I virus non sono cellule: sono acido nucleico + capside e si replicano solo dentro una cellula.",["I batteri sono cellule procariotiche.","I funghi sono fatti di cellule eucariotiche.","","Le piante sono fatte di cellule.","I protozoi sono organismi unicellulari."]],
 ["b1b","I procarioti non hanno un nucleo delimitato da membrana: il DNA sta nel nucleoide.",["Il nucleo con membrana è tipico degli eucarioti.","","I mitocondri esistono solo negli eucarioti (derivano da batteri inglobati).","Il reticolo endoplasmatico è una membrana interna degli eucarioti.","Di solito un batterio (1–5 µm) è molto più piccolo di una cellula umana."]],
 ["b2a","Le cellule somatiche umane sono diploidi: 46 cromosomi, 23 coppie.",["23 cromosomi li hanno i gameti (aploidi).","","44 sono solo gli autosomi: mancano i due sessuali.","48 cromosomi li ha lo scimpanzé.","92 sono i cromatidi dopo la duplicazione (fase G2)."]],
 ["b2b","Il DNA si avvolge attorno agli istoni formando i nucleosomi, il primo livello della cromatina.",["","Gli enzimi catalizzano reazioni: non sono la struttura su cui si avvolge il DNA.","Gli anticorpi sono proteine del sistema immunitario.","Le cicline regolano il ciclo cellulare.","Le tubuline formano i microtubuli."]],
 ["b3b","La trascrizione copia il DNA in RNA (RNA polimerasi).",["La traduzione passa da RNA a proteina.","","La replicazione copia DNA in DNA.","Una mutazione è un cambiamento della sequenza.","Lo splicing rimuove gli introni dall'RNA già trascritto."]],
 ["b3d","Le proteine vengono sintetizzate dai ribosomi, liberi nel citosol o attaccati al reticolo.",["","I lisosomi digeriscono le proteine, non le producono.","Il nucleolo produce i ribosomi, non le proteine.","La membrana contiene proteine ma non le sintetizza.","I vacuoli servono da deposito."]],
 ["b4b","Aa × Aa → 1 AA : 2 Aa : 1 aa: un figlio su quattro è aa.",["Avrebbe ragione se un genitore fosse AA.","","1/2 sono gli eterozigoti Aa.","3/4 sono quelli con almeno un allele A.","Tutti aa solo se entrambi i genitori sono aa."]],
 ["b4c","Nella sindrome di Down (trisomia 21) le cellule hanno tre copie del cromosoma 21: 47 cromosomi.",["","Un X in meno dà la sindrome di Turner.","Le malattie mitocondriali sono un'altra cosa.","Non è un'infezione.","Non dipende dall'alimentazione."]],
 ["b5c","Il mitocondrio produce la maggior parte dell'ATP con la respirazione cellulare (ciclo di Krebs e catena respiratoria).",["Il Golgi modifica e smista le proteine.","","Il lisosoma digerisce.","Il nucleo custodisce il DNA.","Il ribosoma sintetizza le proteine (e consuma energia)."]],
 ["b5f","I lisosomi contengono enzimi digestivi (idrolasi acide) che degradano molecole, organuli vecchi e particelle inglobate.",["Le proteine si producono nei ribosomi.","","Il DNA si duplica nel nucleo.","Questo lo fanno i cloroplasti delle piante.","L'ossigeno lo trasporta l'emoglobina dei globuli rossi."]],
 ["b6c","Gli ormoni vengono rilasciati nel sangue e raggiungono organi lontani: è la segnalazione endocrina.",["","Le ossa sono un tessuto di sostegno.","I nervi trasmettono segnali elettrici; gli ormoni sono segnali chimici nel sangue.","La pelle è un organo di rivestimento.","I muscoli producono movimento."]],
 ["b6a","Tra le cellule c'è la matrice extracellulare: collagene, proteoglicani, acido ialuronico, fibronectina.",["Il citoplasma sta dentro la cellula.","","Il nucleoplasma sta dentro il nucleo.","Il plasma è la parte liquida del sangue.","La linfa circola nei vasi linfatici."]],
 ["b7b","La mitosi produce 2 cellule figlie geneticamente identiche alla madre, con lo stesso numero di cromosomi.",["4 cellule aploidi le produce la meiosi.","","I gameti si formano con la meiosi.","La divisione produce due cellule, non una più grande.","Il numero di cromosomi resta uguale."]],
 ["b7c","La meiosi dimezza il numero di cromosomi e produce i gameti aploidi (cellule uovo e spermatozoi).",["Le cellule del sangue nascono per mitosi.","","I neuroni nascono per mitosi e poi smettono di dividersi.","Cellule identiche le produce la mitosi.","I tessuti crescono per mitosi."]]
]};
Object.keys(PT_EXPL).forEach(k=>{const pt=k==="fis"?FIS_PT:k==="chi"?CHI_PT:BIO_PT;pt.forEach((q,i)=>{const x=PT_EXPL[k][i];if(x){q.t=x[0];q.s=x[1];q.e=x[2];}});});
