/* ================= CONTENUTI: syllabus MUR Fisica 2026/2027 (D.M. 941/2026) ================= */
const EXAM1="2026-12-10", EXAM2="2027-01-11";
/* quote nella simulazione: 31 domande = 21 a risposta multipla + 10 a completamento (formato 2026/27) */
const FIS_UNITS=[
 {id:"u1",ic:"📏",t:"Metodi della fisica",cfu:0.2,q:4,cp:2},
 {id:"u2",ic:"🚀",t:"Meccanica",cfu:1.4,q:6,cp:2},
 {id:"u3",ic:"💧",t:"Meccanica dei fluidi",cfu:1.2,q:5,cp:2},
 {id:"u4",ic:"🔊",t:"Onde meccaniche",cfu:0.4,q:3,cp:1},
 {id:"u5",ic:"🔥",t:"Termodinamica",cfu:1.0,q:5,cp:1},
 {id:"u6",ic:"⚡",t:"Elettricità e magnetismo",cfu:1.2,q:5,cp:1},
 {id:"u7",ic:"☢️",t:"Fisica delle radiazioni",cfu:0.6,q:3,cp:1}
];

const FIS_TOPICS=[
/* ---------- U1 ---------- */
{id:"u1a",u:"u1",t:"Grandezze fisiche e Sistema Internazionale",
 breve:["Le 7 grandezze fondamentali del SI: lunghezza (m), massa (kg), tempo (s), corrente (A), temperatura (K), quantità di sostanza (mol), intensità luminosa (cd).","Tutte le altre sono derivate: N = kg·m/s², J = N·m, W = J/s, Pa = N/m².","Grandezze scalari (massa, tempo, energia, temperatura) e vettoriali (spostamento, velocità, forza): le seconde hanno modulo, direzione e verso.","Prefissi da sapere a memoria: G 10⁹, M 10⁶, k 10³, c 10⁻², m 10⁻³, µ 10⁻⁶, n 10⁻⁹, p 10⁻¹².","Grandezze estensive (dipendono dalla quantità di materia: massa, volume, energia) e intensive (non ne dipendono: temperatura, pressione, densità)."],
 form:[["1 N = 1 kg·m/s²","newton"],["1 J = 1 N·m","joule"],["1 W = 1 J/s","watt"],["1 Pa = 1 N/m²","pascal"]],
 trap:"Il newton, il joule, il pascal e il watt NON sono unità fondamentali: sono derivate. Fondamentali sono m, kg, s, A, K, mol, cd."},
{id:"u1b",u:"u1",t:"Conversioni, notazione scientifica, ordini di grandezza",
 breve:["Converti sempre in unità SI prima di fare i conti.","km/h → m/s: dividi per 3,6 (72 km/h = 20 m/s). m/s → km/h: moltiplica per 3,6.","Volumi: 1 L = 1 dm³ = 1000 cm³ = 10⁻³ m³; 1 mL = 1 cm³.","Aree e volumi si convertono al quadrato e al cubo: 1 cm² = 10⁻⁴ m², 1 cm³ = 10⁻⁶ m³, 1 mm² = 10⁻⁶ m².","Pressione: 1 atm ≈ 1,013·10⁵ Pa ≈ 760 mmHg; 1 mmHg ≈ 133 Pa. Energia: 1 kWh = 3,6·10⁶ J; 1 cal ≈ 4,186 J; 1 eV ≈ 1,6·10⁻¹⁹ J."],
 form:[["v[m/s] = v[km/h] / 3,6"],["1 L = 10⁻³ m³ = 1000 cm³"],["1 atm ≈ 1,013·10⁵ Pa ≈ 760 mmHg"],["1 g/cm³ = 1000 kg/m³"]],
 trap:"L'errore più frequente all'esame: dimenticare che le aree vanno al quadrato. 5 mm² = 5·10⁻⁶ m², non 5·10⁻³ m²."},
{id:"u1c",u:"u1",t:"Vettori e funzioni trigonometriche",anim:"vettori",
 breve:["Un vettore ha modulo, direzione e verso; si somma con la regola del parallelogramma (o punta-coda).","Due vettori perpendicolari: modulo della somma con Pitagora, √(a² + b²).","Componenti: aₓ = a·cos θ, a_y = a·sin θ. Valori da sapere: sin 30° = cos 60° = 0,5; sin 60° = cos 30° ≈ 0,87; sin 45° = cos 45° ≈ 0,71; sin 90° = cos 0° = 1; tan θ = sin θ / cos θ.","Differenza di vettori: a − b = a + (−b), cioè si somma il vettore opposto.","Il prodotto scalare dà uno scalare (es. lavoro F·s·cos θ); il prodotto vettoriale dà un vettore perpendicolare ai due (es. forza di Lorentz)."],
 form:[["|a + b| = √(a² + b² + 2ab·cos θ)"],["aₓ = a cos θ   a_y = a sin θ"],["a·b = ab cos θ   |a×b| = ab sin θ"]],
 trap:"La somma di 3 N e 4 N fa 7 N solo se sono paralleli e concordi. Se sono perpendicolari fa 5 N; se opposti fa 1 N."},
{id:"u1d",u:"u1",t:"Analisi dimensionale e grandezze adimensionali",
 breve:["Le dimensioni si scrivono con M (massa), L (lunghezza), T (tempo).","Forza [M L T⁻²], energia e lavoro [M L² T⁻²], potenza [M L² T⁻³], pressione [M L⁻¹ T⁻²].","In un'equazione corretta i due membri hanno le stesse dimensioni: è un controllo rapido delle formule.","Grandezze adimensionali: rapporti tra grandezze omogenee, come il numero di Reynolds, l'indice di rifrazione, il rendimento, la deformazione relativa, gli angoli in radianti."],
 form:[["[F] = M L T⁻²"],["[E] = M L² T⁻²"],["[P] = M L⁻¹ T⁻²  (pressione)"]],
 trap:"Le domande «quale di queste è adimensionale?» sono frequenti: cerca i rapporti (Reynolds, n, η, rendimento)."},
/* ---------- U2 ---------- */
{id:"u2a",u:"u2",t:"Cinematica: moto rettilineo",anim:"mrua",
 breve:["Moto rettilineo uniforme (MRU): velocità costante, s = v·t.","Moto uniformemente accelerato (MRUA): v = v₀ + a·t, s = v₀t + ½at², v² = v₀² + 2as.","Caduta libera: è un MRUA con a = g ≈ 9,8 m/s² (spesso 10 all'esame), indipendente dalla massa.","Nel grafico velocità–tempo la pendenza è l'accelerazione e l'area sotto la curva è lo spostamento."],
 form:[["v = v₀ + a·t"],["s = v₀·t + ½·a·t²"],["v² = v₀² + 2·a·s"],["caduta da h: t = √(2h/g), v = √(2gh)"]],
 trap:"Velocità media ≠ media delle velocità quando i tempi sono diversi: v_media = spazio totale / tempo totale."},
{id:"u2b",u:"u2",t:"Moto parabolico e moto circolare",anim:"parabolico",
 breve:["Il moto parabolico si scompone: in orizzontale MRU (vₓ costante), in verticale MRUA con −g.","Gittata massima a 45°; angoli complementari (30° e 60°) danno la stessa gittata.","Nel punto più alto la velocità verticale è zero, ma quella orizzontale no.","Moto circolare uniforme: velocità costante in modulo, ma accelerazione centripeta aᶜ = v²/r diretta verso il centro."],
 form:[["gittata R = v₀² sin 2θ / g"],["h_max = v₀² sin² θ / (2g)"],["aᶜ = v²/r = ω²r   ω = 2π/T"]],
 trap:"Nel moto circolare uniforme l'accelerazione NON è nulla: cambia la direzione della velocità."},
{id:"u2c",u:"u2",t:"Principi della dinamica e forze",anim:"piano",
 breve:["1° principio (inerzia): senza forza risultante un corpo resta fermo o in MRU.","2° principio: F = m·a (la forza risultante, non una sola forza).","3° principio: a ogni azione corrisponde una reazione uguale e contraria, applicata all'ALTRO corpo.","Forze tipiche: peso P = mg; forza gravitazionale F = G·m₁m₂/r²; reazione normale N; tensione di un filo; attrito statico (fino a µₛN) e dinamico (µ_d N); forza elastica F = −kx (legge di Hooke).","Piano inclinato liscio: a = g·sin θ; con attrito dinamico: a = g(sin θ − µ cos θ)."],
 form:[["ΣF = m·a"],["P = m·g"],["F_attrito = µ·N"],["F_el = −k·x"],["piano inclinato: P∥ = mg sin θ,  P⊥ = mg cos θ"]],
 trap:"Azione e reazione non si annullano mai tra loro: agiscono su corpi diversi."},
{id:"u2d",u:"u2",t:"Lavoro, energia e potenza",anim:"energia",
 breve:["Lavoro: L = F·s·cos θ (si misura in joule). Una forza perpendicolare allo spostamento non compie lavoro.","Energia cinetica Ec = ½mv²: se v raddoppia, Ec quadruplica.","Energia potenziale gravitazionale U = mgh; elastica U = ½kx².","Teorema dell'energia cinetica: L_totale = ΔEc. Senza attriti l'energia meccanica si conserva.","Potenza P = L/t = F·v (in watt)."],
 form:[["L = F·s·cos θ"],["Ec = ½·m·v²"],["U = m·g·h   U_el = ½·k·x²"],["P = L/t = F·v"]],
 trap:"Un corpo che scivola senza attrito da altezza h arriva con v = √(2gh) qualunque sia la forma del percorso e la massa."},
{id:"u2e",u:"u2",t:"Corpo rigido, momento torcente e leve",anim:"leva",
 breve:["Centro di massa: il punto che si muove come se tutta la massa fosse concentrata lì e tutte le forze esterne agissero su di esso. Per due masse: x_cm = (m₁x₁ + m₂x₂)/(m₁ + m₂).","Corpo rigido: le distanze tra i suoi punti non cambiano; oltre a traslare può ruotare.","Momento torcente di una forza: M = F·b, con b braccio (distanza perpendicolare dal fulcro), in N·m.","Equilibrio di un corpo rigido: somma delle forze = 0 e somma dei momenti = 0.","Leva in equilibrio: F₁·b₁ = F₂·b₂.","Leva di 1° genere (fulcro in mezzo: forbici, altalena), 2° (resistenza in mezzo: schiaccianoci, sollevarsi sulle punte), 3° (potenza in mezzo: avambraccio col bicipite, svantaggiosa ma veloce).","Baricentro: punto di applicazione del peso; equilibrio stabile se la verticale del baricentro cade nella base d'appoggio."],
 form:[["M = F·b"],["F₁·b₁ = F₂·b₂"]],
 trap:"Nell'avambraccio il bicipite deve esercitare una forza molto più grande del peso tenuto in mano (leva di 3° genere)."},
{id:"u2f",u:"u2",t:"Quantità di moto, impulso e urti",
 breve:["Quantità di moto p = m·v: è un vettore (kg·m/s).","Impulso di una forza J = F·Δt = Δp (teorema dell'impulso): per fermare un corpo in un tempo più lungo serve una forza minore (airbag, piegare le ginocchia).","In un sistema isolato la quantità di moto totale si conserva (anche in esplosioni e rinculo).","Urto anelastico: si conserva p ma non l'energia cinetica; se i corpi restano uniti v = (m₁v₁ + m₂v₂)/(m₁ + m₂).","Urto elastico: si conservano sia la quantità di moto sia l'energia cinetica."],
 form:[["p = m·v"],["J = F·Δt = Δp"],["m₁v₁ + m₂v₂ = (m₁ + m₂)·v (urto completamente anelastico)"]],
 trap:"Nel syllabus ufficiale 2026 la quantità di moto c'è (alcune analisi dicevano il contrario) e al 1° appello 2025 è uscito un urto anelastico. Ricorda: negli urti anelastici l'energia cinetica NON si conserva."},
/* ---------- U3 ---------- */
{id:"u3a",u:"u3",t:"Densità, pressione, Stevino e Pascal",anim:"stevino",
 breve:["I fluidi (liquidi e gas) non hanno forma propria e scorrono; i liquidi sono quasi incomprimibili, i gas comprimibili. Densità ρ = m/V (acqua 1000 kg/m³ = 1 g/cm³).","Pressione p = F/A, in pascal.","Legge di Stevino: p = p₀ + ρgh. In acqua ogni 10 m circa +1 atm.","Principio di Pascal: una pressione applicata a un fluido si trasmette uguale in tutti i punti (torchio idraulico: F₂ = F₁·A₂/A₁).","La pressione dipende solo dalla profondità, non dalla forma del recipiente.","Misura della pressione: esperimento di Torricelli (l'atmosfera sostiene circa 760 mm di mercurio) e manometro. La pressione del sangue si misura come pressione relativa (rispetto all'atmosfera) in mmHg."],
 form:[["ρ = m/V"],["p = F/A"],["p = p₀ + ρ·g·h"],["F₂/A₂ = F₁/A₁"]],
 trap:"Un sub a 50 m sente circa 6 atm (5 dall'acqua + 1 dell'atmosfera), non 5."},
{id:"u3b",u:"u3",t:"Principio di Archimede e galleggiamento",anim:"archimede",
 breve:["Spinta di Archimede: S = ρ_fluido·g·V_immerso (uguale al peso del fluido spostato).","Un corpo galleggia se la sua densità media è minore di quella del fluido.","Frazione immersa di un corpo che galleggia = ρ_corpo / ρ_fluido (ghiaccio in acqua: 920/1000 = 92%).","Peso apparente di un corpo immerso = peso − spinta."],
 form:[["S = ρ_f · g · V_imm"],["V_imm / V = ρ_corpo / ρ_fluido"]],
 trap:"La spinta dipende dalla densità del FLUIDO e dal volume immerso, non dalla densità del corpo."},
{id:"u3c",u:"u3",t:"Fluidi ideali: continuità e Bernoulli",anim:"continuita",
 breve:["Portata Q = A·v (m³/s): in un tubo senza perdite resta costante (equazione di continuità).","Se la sezione si dimezza, la velocità raddoppia.","Equazione di Bernoulli: p + ½ρv² + ρgh = costante (fluido ideale, moto stazionario).","In un tubo orizzontale dove il fluido va più veloce la pressione è più bassa (effetto Venturi; aneurisma e stenosi).","Nel sistema circolatorio la portata del cuore è circa 5 L/min: la velocità è minima nei capillari perché la sezione TOTALE è massima."],
 form:[["Q = A·v = costante"],["A₁·v₁ = A₂·v₂"],["p + ½ρv² + ρgh = cost."]],
 trap:"I capillari sono stretti singolarmente, ma la loro sezione complessiva è enorme: per questo il sangue lì va piano."},
{id:"u3d",u:"u3",t:"Fluidi reali: viscosità, Poiseuille, Reynolds",anim:"poiseuille",tag:"Reynolds uscito nel 2025",
 breve:["Un fluido reale ha viscosità η (Pa·s): serve una differenza di pressione per farlo scorrere.","Legge di Poiseuille (moto laminare): Q = π r⁴ Δp / (8 η l). La portata dipende dalla QUARTA potenza del raggio.","Resistenza idrodinamica R = Δp/Q = 8ηl/(πr⁴): in serie si sommano, in parallelo si sommano gli inversi.","Il profilo di velocità è parabolico: massima al centro, zero sulle pareti.","Il profilo parabolico nasce dal gradiente di velocità tra strati di fluido vicini (attrito interno).","Numero di Reynolds Re = ρvd/η (adimensionale): basso → laminare, alto (oltre circa 2000) → turbolento. Il syllabus chiede la distinzione laminare/turbolento; il numero di Reynolds non è nominato, ma è uscito nel 2° appello 2025."],
 form:[["Q = π·r⁴·Δp / (8·η·l)"],["R = Δp/Q"],["Re = ρ·v·d / η"]],
 trap:"Raggio dimezzato → portata ridotta di 16 volte (2⁴), non di 2 o 4."},
{id:"u3e",u:"u3",t:"Tensione superficiale e capillarità",
 breve:["Tensione superficiale τ (N/m): l'energia necessaria per aumentare la superficie di un liquido.","Legge di Laplace per una sfera (bolla, alveolo): Δp = 2τ/r. Più piccolo il raggio, maggiore la pressione.","Il surfattante polmonare riduce la tensione superficiale e stabilizza gli alveoli.","Capillarità: un liquido che bagna le pareti risale in un tubo sottile (acqua), uno che non le bagna scende (mercurio)."],
 form:[["Δp = 2τ / r  (sfera)"]],
 trap:"È nel syllabus 2026 (legge di Laplace in forma qualitativa) ma non è uscito nelle prove 2025: basta capirne il significato. Bolla piccola = pressione interna maggiore."},
/* ---------- U4 ---------- */
{id:"u4a",u:"u4",t:"Onde: grandezze fondamentali",anim:"onda",
 breve:["Un'onda trasporta energia, non materia.","Onde trasversali (oscillazione perpendicolare alla propagazione) e longitudinali (parallela: il suono).","Lunghezza d'onda λ, periodo T, frequenza f = 1/T, pulsazione ω = 2πf, velocità v = λ·f.","Onda armonica: y(x,t) = A·sin(kx − ωt), con numero d'onda k = 2π/λ.","Quando un'onda cambia mezzo la frequenza resta la stessa: cambiano velocità e lunghezza d'onda.","Le onde meccaniche hanno bisogno di un mezzo: il suono non si propaga nel vuoto."],
 form:[["v = λ·f"],["f = 1/T"]],
 trap:"Passando dall'aria all'acqua il suono va più veloce: λ aumenta, f no."},
{id:"u4b",u:"u4",t:"Suono, intensità e decibel",anim:"decibel",
 breve:["Intensità I = potenza / area (W/m²); per una sorgente puntiforme I diminuisce come 1/r².","L'intensità è proporzionale al quadrato dell'ampiezza (e, a parità di ampiezza, al quadrato della frequenza).","Livello sonoro β = 10·log₁₀(I/I₀) dB, con I₀ = 10⁻¹² W/m² (soglia di udibilità = 0 dB).","+10 dB = intensità ×10; +20 dB = ×100; +3 dB ≈ ×2.","Udibile da circa 20 Hz a 20 kHz; sopra 20 kHz ultrasuoni (ecografia), sotto 20 Hz infrasuoni."],
 form:[["I = P / A"],["β = 10·log₁₀(I / I₀)   I₀ = 10⁻¹² W/m²"]],
 trap:"0 dB NON è assenza di suono: è la soglia di udibilità."},
{id:"u4c",u:"u4",t:"Effetto Doppler ed ecografia",anim:"doppler",
 breve:["Se sorgente e osservatore si avvicinano la frequenza percepita aumenta; se si allontanano diminuisce.","Il syllabus 2026 chiede solo la descrizione qualitativa (al 2° appello 2025 era uscito un calcolo in percentuale).","In medicina: ecodoppler per misurare la velocità del sangue.","Ecografia: ultrasuoni (MHz) riflessi alle interfacce tra tessuti di diversa impedenza acustica; dal tempo di ritorno si ricava la profondità."],
 form:[["sorgente in avvicinamento: f' = f · v / (v − v_s)"],["osservatore in avvicinamento: f' = f · (v + v_o) / v"]],
 trap:"Cambia la frequenza PERCEPITA, non quella emessa dalla sorgente."},
{id:"u4d",u:"u4",t:"Oscillatore armonico, sovrapposizione e interferenza",anim:"molla",
 breve:["Oscillatore armonico: una massa su una molla oscilla con x(t) = A·cos(ωt); è il modello base che genera le onde.","Periodo della molla: T = 2π√(m/k). Massa ×4 → periodo ×2; molla più rigida → oscillazioni più rapide. Il periodo non dipende dall'ampiezza.","Principio di sovrapposizione: quando due onde si incontrano gli spostamenti si sommano.","Interferenza costruttiva (onde in fase, differenza di cammino = nλ): ampiezza massima. Distruttiva (in opposizione di fase, differenza = λ/2, 3λ/2…): le onde si annullano."],
 form:[["T = 2π·√(m/k)"],["ω = 2π/T = 2πf"],["costruttiva: Δ = n·λ   distruttiva: Δ = (n + ½)·λ"]],
 trap:"Al 1° appello 2025 è uscita la relazione tra periodo e costante elastica di una molla: il periodo dipende da m e k, non dall'ampiezza."},
/* ---------- U5 ---------- */
{id:"u5a",u:"u5",t:"Temperatura, calore e passaggi di stato",anim:"riscaldamento",
 breve:["T(K) = T(°C) + 273,15. Lo zero assoluto è 0 K = −273,15 °C. Una variazione di 1 °C equivale a 1 K.","Calore Q = c·m·ΔT (c calore specifico; acqua 4186 J/(kg·K) ≈ 1 cal/(g·°C)).","Capacità termica C = c·m (J/K): riguarda l'oggetto intero.","Durante un passaggio di stato la temperatura resta costante: Q = λ·m (calore latente).","Calorimetria: mescolando due corpi senza perdite, calore ceduto = calore assorbito. Temperatura d'equilibrio T_eq = (m₁c₁T₁ + m₂c₂T₂)/(m₁c₁ + m₂c₂).","Sistema e ambiente; variabili di stato p, V, T; funzioni di stato (energia interna, entropia) dipendono solo dallo stato, non dal percorso."],
 form:[["T[K] = T[°C] + 273"],["Q = c·m·ΔT"],["C = c·m"],["Q = λ·m (passaggio di stato)"]],
 trap:"Mentre l'acqua bolle la sua temperatura non sale: tutto il calore serve a cambiare stato."},
{id:"u5b",u:"u5",t:"Gas perfetti",anim:"gas",
 breve:["Equazione di stato: pV = nRT (T in kelvin!).","Boyle (T costante): pV = costante. Gay-Lussac: V/T costante (p cost.) e p/T costante (V cost.).","Una mole di gas perfetto a 0 °C e 1 atm occupa circa 22,4 L.","La temperatura misura l'energia cinetica media delle molecole: l'energia interna di un gas perfetto dipende solo da T (ΔU = n·c_v·ΔT).","Gas reali: a pressioni alte o temperature basse pV = nRT non vale più esattamente (non è nel syllabus 2026, ma è uscito nel 2° appello 2025)."],
 form:[["p·V = n·R·T   R = 8,31 J/(mol·K)"],["p₁V₁/T₁ = p₂V₂/T₂"],["ΔU = n·c_v·ΔT"]],
 trap:"Nei conti con pV = nRT la temperatura va SEMPRE in kelvin: a volume costante, da 27 °C a 54 °C la pressione non raddoppia."},
{id:"u5c",u:"u5",t:"Primo principio e trasformazioni",anim:"pv",
 breve:["Primo principio: ΔU = Q − L (Q assorbito dal sistema, L compiuto dal sistema).","Lavoro a pressione costante: L = p·ΔV; in generale è l'area sotto la curva nel piano p–V.","Isocora (V cost.): L = 0 → ΔU = Q. Isobara: L = pΔV. Isoterma (gas perfetto): ΔU = 0 → Q = L. Adiabatica: Q = 0 → ΔU = −L.","In un ciclo ΔU = 0: il lavoro netto è l'area racchiusa dal ciclo.","Se la trasformazione si inverte, il lavoro cambia segno.","Trasformazione reversibile: successione di stati di equilibrio, percorribile al contrario. Quelle reali (rapide, con attriti) sono irreversibili."],
 form:[["ΔU = Q − L"],["L = p·ΔV (isobara)"],["isoterma: L = nRT·ln(V₂/V₁)"]],
 trap:"Attenti ai segni: nell'espansione il gas compie lavoro positivo; nella compressione il lavoro è negativo."},
{id:"u5d",u:"u5",t:"Secondo principio, entropia e macchine termiche",
 breve:["Enunciato di Kelvin: è impossibile trasformare integralmente in lavoro il calore preso da una sola sorgente in un ciclo.","Enunciato di Clausius: il calore non passa spontaneamente dal freddo al caldo.","Rendimento η = L/Q_ass = 1 − Q_ced/Q_ass < 1.","Macchina di Carnot (massimo rendimento): η = 1 − T_fredda/T_calda (in kelvin).","Entropia S: funzione di stato; in un sistema isolato non diminuisce mai e aumenta nelle trasformazioni irreversibili. ΔS = Q/T (reversibile, T costante).","Interpretazione statistica: l'entropia misura il numero di modi microscopici (microstati) compatibili con lo stato; i processi spontanei vanno verso gli stati più probabili, cioè più «disordinati»."],
 form:[["η = L / Q_ass = 1 − Q_ced/Q_ass"],["η_Carnot = 1 − T_f / T_c"],["ΔS = Q / T"]],
 trap:"Nel rendimento di Carnot le temperature vanno in kelvin: tra 327 °C e 27 °C η = 1 − 300/600 = 50%."},
{id:"u5e",u:"u5",t:"Trasmissione del calore",
 breve:["Conduzione: per contatto, senza spostamento di materia (Q/t = k·A·ΔT/d).","Convezione: con spostamento di materia nei fluidi (il sangue che distribuisce calore).","Irraggiamento: onde elettromagnetiche, anche nel vuoto; potenza ∝ T⁴ (Stefan-Boltzmann).","Il corpo umano perde calore soprattutto per irraggiamento ed evaporazione del sudore."],
 form:[["Q/t = k·A·ΔT / d (conduzione)"],["P ∝ ε·σ·A·T⁴ (irraggiamento)"]],
 trap:"L'unico modo di trasmettere calore nel vuoto è l'irraggiamento."},
/* ---------- U6 ---------- */
{id:"u6a",u:"u6",t:"Carica elettrica e legge di Coulomb",
 breve:["La carica si conserva ed è quantizzata: e = 1,6·10⁻¹⁹ C.","Cariche dello stesso segno si respingono, di segno opposto si attraggono.","Legge di Coulomb: F = k·q₁q₂/r², con k ≈ 9·10⁹ N·m²/C².","Distanza doppia → forza ridotta a un quarto.","Conduttori (cariche libere di muoversi) e isolanti; in un conduttore in equilibrio la carica sta sulla superficie e il campo interno è nullo.","Induzione elettrostatica: avvicinando un corpo carico a un conduttore le sue cariche si separano. Polarizzazione: in un isolante (dielettrico) le molecole si orientano senza che le cariche si spostino liberamente."],
 form:[["F = k·q₁·q₂ / r²   k ≈ 9·10⁹ N·m²/C²"],["e = 1,6·10⁻¹⁹ C"]],
 trap:"È una legge dell'inverso del quadrato, come la gravitazione: triplicando la distanza la forza diventa 1/9."},
{id:"u6b",u:"u6",t:"Campo elettrico e potenziale",anim:"campo",
 breve:["Campo elettrico E = F/q (N/C oppure V/m); per una carica puntiforme E = kQ/r².","Le linee di campo escono dalle cariche positive ed entrano nelle negative; non si incrociano mai.","Potenziale V (volt): energia potenziale per unità di carica. Il lavoro del campo è L = q·ΔV.","Superfici equipotenziali: perpendicolari alle linee di campo; per una carica puntiforme sono sfere concentriche. Spostarsi su un'equipotenziale non richiede lavoro.","Elettronvolt: energia acquistata da un elettrone che attraversa 1 V (1 eV = 1,6·10⁻¹⁹ J).","Carica in campo uniforme: F = qE costante → moto uniformemente accelerato, a = qE/m (come un proiettile nel campo di gravità). Conservazione dell'energia: ½mv² = q·ΔV."],
 form:[["E = F/q = k·Q/r²"],["V = k·Q/r"],["L = q·ΔV   ΔU = q·ΔV"],["E = ΔV / d (campo uniforme)"]],
 trap:"Il campo è un vettore, il potenziale è uno scalare: si sommano in modo diverso."},
{id:"u6c",u:"u6",t:"Condensatore",anim:"campo",animOpt:{m:3},
 breve:["Condensatore piano: due armature con cariche +Q e −Q; tra le armature il campo è uniforme, E = V/d.","Capacità C = Q/V (farad); per il piano C = ε₀εᵣA/d.","Un dielettrico tra le armature aumenta la capacità di εᵣ volte.","Energia immagazzinata: U = ½CV² = ½QV.","In serie: 1/C = 1/C₁ + 1/C₂; in parallelo: C = C₁ + C₂ (al contrario delle resistenze). La membrana cellulare si comporta come un condensatore."],
 form:[["C = Q/V"],["C = ε₀·εᵣ·A/d"],["U = ½·C·V²"]],
 trap:"Le capacità in parallelo si sommano (come le resistenze in serie), e viceversa."},
{id:"u6d",u:"u6",t:"Corrente, legge di Ohm e circuiti",anim:"circuito",
 breve:["Intensità di corrente I = Δq/Δt (ampere). Il generatore ideale mantiene una differenza di potenziale costante ai suoi capi.","Legge di Ohm: V = R·I. Resistenza di un filo R = ρ·l/A (ρ resistività del materiale, Ω·m): filo più lungo → R maggiore; più spesso → R minore.","Resistenze in serie: R = R₁ + R₂ (stessa corrente). In parallelo: 1/R = 1/R₁ + 1/R₂ (stessa tensione); due uguali in parallelo danno R/2.","Potenza (effetto Joule): P = V·I = R·I² = V²/R.","1 kWh = 3,6·10⁶ J è un'unità di energia, non di potenza."],
 form:[["V = R·I"],["R = ρ·l / A"],["serie: R = R₁ + R₂   parallelo: 1/R = 1/R₁ + 1/R₂"],["P = V·I = R·I² = V²/R"]],
 trap:"La resistenza equivalente in parallelo è sempre minore della più piccola delle due."},
{id:"u6e",u:"u6",t:"Campo magnetico e induzione",anim:"lorentz",
 breve:["Il campo magnetico B si misura in tesla; le sue linee sono sempre chiuse (non esistono monopoli magnetici).","Forza di Lorentz su una carica in moto: F = q·v·B·sin θ, perpendicolare a v e a B; su una carica ferma è nulla.","La forza di Lorentz non compie lavoro: cambia la direzione ma non il modulo della velocità (moto circolare, r = mv/(qB)).","Esperimento di Oersted: una corrente devia l'ago di una bussola → le correnti generano campi magnetici. Un filo percorso da corrente in un campo B subisce F = I·l·B·sin θ.","Induzione (Faraday-Neumann-Lenz): una variazione del flusso magnetico genera una f.e.m. che si oppone alla variazione. Base di generatori, trasformatori e risonanza magnetica."],
 form:[["F = q·v·B·sin θ"],["F = I·l·B (filo)"],["r = m·v / (q·B)"],["Φ = B·A·cos θ   f.e.m. = −ΔΦ/Δt"]],
 trap:"Un flusso costante, anche molto grande, non induce nulla: conta solo la sua VARIAZIONE."},
/* ---------- U7 ---------- */
{id:"u7a",u:"u7",t:"Onde elettromagnetiche e fotoni",anim:"spettro",
 breve:["Onde elettromagnetiche: campi E e B oscillanti, perpendicolari tra loro e alla direzione di propagazione (onde trasversali); si propagano anche nel vuoto a c = 3·10⁸ m/s.","Spettro in ordine di frequenza crescente: radio, microonde, infrarosso, visibile (rosso → violetto, 700–400 nm), ultravioletto, raggi X, raggi γ.","Energia di un fotone: E = h·f = h·c/λ (h = 6,6·10⁻³⁴ J·s). Più alta la frequenza, più energia.","Ionizzanti e non ionizzanti: conta l'energia del singolo fotone rispetto all'energia di ionizzazione degli atomi (pochi eV). Non ionizzanti: radio, microonde, infrarosso, visibile. Ionizzanti: UV di alta energia, raggi X e γ."],
 form:[["c = λ·f"],["E = h·f = h·c/λ"]],
 trap:"Il rosso ha lunghezza d'onda maggiore ma frequenza ed energia minori del violetto."},
{id:"u7b",u:"u7",t:"Riflessione, rifrazione e riflessione totale",anim:"snell",
 breve:["Riflessione: angolo di riflessione = angolo di incidenza (misurati dalla normale).","Indice di rifrazione n = c/v ≥ 1 (adimensionale). Vetro ≈ 1,5; acqua ≈ 1,33.","Legge di Snell: n₁ sin θ₁ = n₂ sin θ₂. Entrando in un mezzo più rifrangente il raggio si avvicina alla normale.","Riflessione totale: passando da un mezzo più rifrangente a uno meno, oltre l'angolo limite (sin θ_L = n₂/n₁) non c'è rifrazione. Principio delle fibre ottiche e degli endoscopi.","Lastra a facce parallele: il raggio esce parallelo a quello entrante, ma traslato."],
 form:[["n = c / v"],["n₁·sin θ₁ = n₂·sin θ₂"],["sin θ_L = n₂ / n₁"]],
 trap:"La riflessione totale avviene solo da mezzo PIÙ rifrangente a mezzo MENO rifrangente."},
{id:"u7c",u:"u7",t:"Lenti e potere diottrico",anim:"lente",
 breve:["Lente convergente: raggi paralleli all'asse convergono nel fuoco F.","Equazione dei punti coniugati: 1/p + 1/q = 1/f; ingrandimento m = −q/p.","Potere diottrico D = 1/f (in metri), unità diottria. f = 0,5 m → 2 D.","Oggetto oltre 2f: immagine reale, capovolta, rimpicciolita. Tra f e 2f: reale, capovolta, ingrandita. Dentro f: virtuale, diritta, ingrandita (lente d'ingrandimento).","Il syllabus chiede le lenti convergenti sottili; l'occhio è un sistema convergente (miopia e ipermetropia sono un approfondimento)."],
 form:[["1/p + 1/q = 1/f"],["D = 1/f [m⁻¹]"],["m = −q/p"]],
 trap:"Per il potere diottrico la focale va in METRI: f = 25 cm → D = 4 diottrie."},
{id:"u7d",u:"u7",t:"Assorbimento della radiazione: legge di Lambert-Beer",anim:"lambert",tag:"Novità 2026",
 breve:["Attraversando un mezzo assorbente l'intensità diminuisce in modo esponenziale con lo spessore: I = I₀·e^(−µx).","Legge di Lambert-Beer (forma decimale): A = log₁₀(I₀/I) = ε·c·l, con c concentrazione e l cammino ottico.","Trasmittanza T = I/I₀ = 10^(−A): A = 1 → passa il 10%; A = 2 → passa l'1%.","L'assorbanza è proporzionale alla concentrazione: è il principio della spettrofotometria (es. emoglobina, pulsossimetro)."],
 form:[["I = I₀·e^(−µ·x)"],["A = log₁₀(I₀/I) = ε·c·l"],["T = I/I₀ = 10^(−A)"]],
 trap:"Raddoppiare lo spessore NON dimezza l'intensità trasmessa: raddoppia l'assorbanza (T passa da 10% a 1% se A va da 1 a 2)."},
{id:"u7e",u:"u7",t:"Radioattività, decadimento ed emivita",anim:"decadimento",tag:"Novità 2026",
 breve:["Nucleo instabile e isotopi radioattivi: stesso numero atomico Z, diverso numero di neutroni.","Decadimenti: α (nucleo di elio: A − 4, Z − 2, poco penetrante), β⁻ (un neutrone diventa protone: Z + 1, A invariato), β⁺ (Z − 1), γ (fotone emesso da un nucleo eccitato: A e Z non cambiano; è il più penetrante).","Legge del decadimento: N(t) = N₀·e^(−λt) = N₀·(½)^(t/T½).","Emivita (tempo di dimezzamento) T½ = ln2/λ ≈ 0,693/λ: dopo n emivite resta N₀/2ⁿ.","Attività A = λ·N, si misura in becquerel (1 Bq = 1 decadimento al secondo); anche l'attività si dimezza ogni T½.","Approfondimento non presente nel syllabus: dose assorbita in gray (Gy = J/kg), dose equivalente in sievert (Sv)."],
 form:[["N = N₀·(½)^(t/T½)"],["T½ = ln2/λ"],["A = λ·N  [Bq]"]],
 trap:"Dopo 3 emivite non resta un terzo ma un ottavo (½·½·½)."}
];

/* Banca domande. k: m = risposta multipla (5 opzioni), c = completamento (una parola).
   Stile delle prove nazionali: numeri semplici, senza calcolatrice. */
const FIS_QB=[
/* U1 */
{t:"u1a",k:"m",q:"Quale tra queste è un'unità di misura fondamentale del Sistema Internazionale?",o:["newton","joule","kelvin","pascal","watt"],a:2,s:"Le unità fondamentali sono m, kg, s, A, K, mol, cd. Newton, joule, pascal e watt sono derivate."},
{t:"u1b",k:"m",q:"Un'automobile viaggia a 72 km/h. Quanto vale la sua velocità in m/s?",o:["7,2","20","36","72","259"],a:1,s:"72 / 3,6 = 20 m/s."},
{t:"u1b",k:"c",q:"1 litro corrisponde a ____ cm³.",a:["1000","1.000","MILLE","10^3"],s:"1 L = 1 dm³ = 1000 cm³."},
{t:"u1b",k:"m",q:"Una pressione di 1 atm corrisponde circa a:",o:["1013 Pa","1,013·10⁵ Pa","760 Pa","10³ Pa","10⁶ Pa"],a:1,s:"1 atm ≈ 101 300 Pa ≈ 760 mmHg."},
{t:"u1d",k:"m",q:"Quale delle seguenti grandezze è adimensionale?",o:["velocità","numero di Reynolds","pressione","energia","densità"],a:1,s:"Re = ρvd/η è un rapporto tra grandezze omogenee: non ha unità."},
{t:"u1d",k:"m",q:"Le dimensioni del lavoro sono:",o:["M L T⁻¹","M L² T⁻²","M L T⁻²","M L² T⁻¹","M L⁻¹ T⁻²"],a:1,s:"L = F·s → (M L T⁻²)·L = M L² T⁻²."},
{t:"u1a",k:"c",q:"Il prefisso «micro» (µ) corrisponde al fattore 10 elevato alla ____ .",a:["-6","MENO6","−6"],s:"micro = 10⁻⁶; milli = 10⁻³; nano = 10⁻⁹."},
{t:"u1c",k:"m",q:"Due forze perpendicolari di 3 N e 4 N agiscono sullo stesso punto. Il modulo della risultante è:",o:["7 N","1 N","5 N","12 N","3,5 N"],a:2,s:"√(3² + 4²) = √25 = 5 N."},
{t:"u1b",k:"m",q:"Una superficie di 5 mm² espressa in m² vale:",o:["5·10⁻³ m²","5·10⁻⁶ m²","5·10⁻⁴ m²","5·10⁻⁹ m²","5·10⁻² m²"],a:1,s:"1 mm = 10⁻³ m → 1 mm² = 10⁻⁶ m²."},
{t:"u1a",k:"c",q:"L'unità di misura della forza nel SI è il ____ .",a:["NEWTON","N"],s:"1 N = 1 kg·m/s²."},
{t:"u1b",k:"m",q:"1 mmHg corrisponde circa a:",o:["1 Pa","13 Pa","133 Pa","1013 Pa","760 Pa"],a:2,s:"101 300 Pa / 760 ≈ 133 Pa."},
{t:"u1c",k:"m",q:"Quale delle seguenti è una grandezza scalare?",o:["forza","velocità","accelerazione","massa","spostamento"],a:3,s:"La massa ha solo un valore numerico; le altre hanno anche direzione e verso."},
{t:"u1b",k:"c",q:"1 kWh equivale a ____ ·10⁶ J (scrivi il numero).",a:["3,6","3.6"],s:"1000 W × 3600 s = 3,6·10⁶ J."},
{t:"u1b",k:"m",q:"Una densità di 1 g/cm³ espressa in kg/m³ vale:",o:["1","10","100","1000","10⁶"],a:3,s:"1 g/cm³ = 10⁻³ kg / 10⁻⁶ m³ = 1000 kg/m³."},
{t:"u1c",k:"m",q:"Un vettore di modulo 10 forma un angolo di 60° con l'asse x. La sua componente x vale:",o:["10","8,7","5","0","20"],a:2,s:"aₓ = 10·cos 60° = 10·0,5 = 5."},
{t:"u1d",k:"m",q:"In quale unità si misura una pressione espressa in unità fondamentali?",o:["kg·m/s²","kg/(m·s²)","kg·m²/s²","kg/m³","kg·m²/s³"],a:1,s:"Pa = N/m² = (kg·m/s²)/m² = kg/(m·s²)."},
/* U2 */
{t:"u2a",k:"m",q:"Un'auto parte da ferma con accelerazione costante di 2 m/s². Dopo 5 s la sua velocità è:",o:["2 m/s","5 m/s","7 m/s","10 m/s","25 m/s"],a:3,s:"v = a·t = 2·5 = 10 m/s."},
{t:"u2a",k:"m",q:"Un'auto parte da ferma con a = 2 m/s². In 5 s percorre:",o:["10 m","20 m","25 m","50 m","100 m"],a:2,s:"s = ½·a·t² = ½·2·25 = 25 m."},
{t:"u2a",k:"m",q:"Un oggetto viene lasciato cadere da 20 m (g = 10 m/s², aria trascurabile). Il tempo di caduta è:",o:["1 s","2 s","4 s","√2 s","10 s"],a:1,s:"t = √(2h/g) = √(40/10) = 2 s."},
{t:"u2d",k:"m",q:"Con quale velocità tocca terra un oggetto lasciato cadere da 20 m? (g = 10 m/s²)",o:["10 m/s","14 m/s","20 m/s","200 m/s","40 m/s"],a:2,s:"v = √(2gh) = √400 = 20 m/s."},
{t:"u2c",k:"c",q:"In assenza di forze risultanti, un corpo in movimento prosegue di moto rettilineo ____ .",a:["UNIFORME"],s:"È il primo principio della dinamica (principio d'inerzia)."},
{t:"u2c",k:"m",q:"Un corpo di 4 kg ha un'accelerazione di 3 m/s². La forza risultante che agisce su di esso è:",o:["0,75 N","7 N","12 N","1,33 N","43 N"],a:2,s:"F = m·a = 4·3 = 12 N."},
{t:"u2c",k:"m",q:"Il peso di una persona di 70 kg sulla Terra è circa:",o:["70 N","690 N","7 N","7000 N","9,8 N"],a:1,s:"P = m·g = 70·9,8 ≈ 686 N."},
{t:"u2c",k:"m",q:"Un libro è appoggiato su un tavolo. La forza che il libro esercita sul tavolo e quella che il tavolo esercita sul libro sono:",o:["uguali e concordi","uguali in modulo e opposte","diverse in modulo","entrambe nulle","dipendenti dalla massa del tavolo"],a:1,s:"Terzo principio: azione e reazione sono uguali e opposte e agiscono su corpi diversi."},
{t:"u2c",k:"m",q:"Un corpo scivola su un piano inclinato liscio di 30°. La sua accelerazione è (g = 10 m/s²):",o:["10 m/s²","5 m/s²","8,7 m/s²","0","20 m/s²"],a:1,s:"a = g·sin 30° = 10·0,5 = 5 m/s²."},
{t:"u2d",k:"m",q:"Il lavoro necessario per sollevare di 3 m un corpo di 2 kg a velocità costante è (g = 10 m/s²):",o:["6 J","20 J","30 J","60 J","600 J"],a:3,s:"L = m·g·h = 2·10·3 = 60 J."},
{t:"u2d",k:"m",q:"L'energia cinetica di un corpo di 2 kg che si muove a 3 m/s è:",o:["3 J","6 J","9 J","18 J","12 J"],a:2,s:"Ec = ½·2·3² = 9 J."},
{t:"u2d",k:"m",q:"Se la velocità di un corpo raddoppia, la sua energia cinetica:",o:["raddoppia","quadruplica","si dimezza","resta uguale","triplica"],a:1,s:"Ec ∝ v²: 2² = 4."},
{t:"u2d",k:"c",q:"L'unità di misura della potenza nel SI è il ____ .",a:["WATT","W"],s:"1 W = 1 J/s."},
{t:"u2d",k:"m",q:"Un motore compie un lavoro di 600 J in 2 minuti. La sua potenza media è:",o:["300 W","5 W","1200 W","10 W","50 W"],a:1,s:"P = 600 J / 120 s = 5 W."},
{t:"u2e",k:"m",q:"Una leva è in equilibrio: una forza di 50 N agisce a 0,2 m dal fulcro. Quale forza serve a 0,5 m dal fulcro dall'altra parte?",o:["125 N","20 N","10 N","50 N","25 N"],a:1,s:"F₁b₁ = F₂b₂ → 50·0,2 = F·0,5 → F = 20 N."},
{t:"u2b",k:"m",q:"In un moto circolare uniforme l'accelerazione:",o:["è nulla","è tangente alla traiettoria","è diretta verso il centro","è diretta verso l'esterno","varia in modulo"],a:2,s:"È l'accelerazione centripeta v²/r, sempre verso il centro."},
{t:"u2c",k:"c",q:"Una molla di costante k = 200 N/m viene allungata di 0,1 m. La forza elastica vale ____ N.",a:["20"],s:"F = k·x = 200·0,1 = 20 N."},
{t:"u2a",k:"m",q:"In un grafico velocità–tempo, l'area sotto la curva rappresenta:",o:["l'accelerazione","lo spostamento","la forza","l'energia","il tempo"],a:1,s:"v·t = spazio: l'area è lo spostamento; la pendenza è l'accelerazione."},
{t:"u2c",k:"m",q:"Un corpo di 10 kg scivola su un piano orizzontale con coefficiente di attrito dinamico 0,2 (g = 10 m/s²). La forza d'attrito vale:",o:["2 N","5 N","20 N","50 N","200 N"],a:2,s:"F = µ·m·g = 0,2·10·10 = 20 N."},
{t:"u2d",k:"m",q:"Un corpo scivola senza attrito da un'altezza di 5 m partendo da fermo. Con che velocità arriva in fondo? (g = 10 m/s²)",o:["5 m/s","10 m/s","50 m/s","100 m/s","√5 m/s"],a:1,s:"mgh = ½mv² → v = √(2·10·5) = 10 m/s, indipendente dalla massa e dalla forma del percorso."},
{t:"u2b",k:"m",q:"Due proiettili sono lanciati con la stessa velocità, uno a 30° e uno a 60°. Le loro gittate sono:",o:["uguali","doppia quella a 60°","doppia quella a 30°","nulla quella a 60°","dipendenti dalla massa"],a:0,s:"R = v₀² sin2θ / g e sin 60° = sin 120°: angoli complementari danno la stessa gittata."},
{t:"u2b",k:"m",q:"Nel punto più alto della traiettoria di un proiettile:",o:["la velocità è nulla","l'accelerazione è nulla","è nulla solo la componente verticale della velocità","è nulla la componente orizzontale","la forza peso si annulla"],a:2,s:"vₓ resta costante; v_y è zero nel punto più alto; l'accelerazione resta g."},
{t:"u2e",k:"m",q:"L'avambraccio che regge un peso, con il bicipite tra gomito e mano, è una leva di:",o:["1° genere, vantaggiosa","2° genere, vantaggiosa","3° genere, svantaggiosa","1° genere, indifferente","non è una leva"],a:2,s:"La potenza (bicipite) sta tra fulcro (gomito) e resistenza (peso): 3° genere, sempre svantaggiosa."},
{t:"u2d",k:"c",q:"Il lavoro compiuto da una forza perpendicolare allo spostamento è ____ .",a:["NULLO","ZERO","0"],s:"L = F·s·cos 90° = 0."},
/* U3 */
{t:"u3a",k:"m",q:"Qual è la pressione idrostatica dovuta all'acqua a 10 m di profondità? (ρ = 1000 kg/m³, g = 10 m/s²)",o:["10³ Pa","10⁴ Pa","10⁵ Pa","10⁶ Pa","100 Pa"],a:2,s:"ρgh = 1000·10·10 = 10⁵ Pa ≈ 1 atm."},
{t:"u3a",k:"m",q:"Un sub si trova a 50 m di profondità in mare. La pressione totale che subisce è circa:",o:["5 atm","6 atm","50 atm","0,5 atm","4 atm"],a:1,s:"5 atm dall'acqua (1 ogni 10 m) + 1 atm dell'atmosfera = 6 atm."},
{t:"u3b",k:"m",q:"Un cubetto di ghiaccio (ρ = 920 kg/m³) galleggia in acqua (ρ = 1000 kg/m³). La frazione di volume immersa è:",o:["8%","50%","92%","100%","9,2%"],a:2,s:"V_imm/V = ρ_ghiaccio/ρ_acqua = 0,92."},
{t:"u3b",k:"c",q:"La spinta di Archimede è uguale al peso del ____ spostato.",a:["FLUIDO","LIQUIDO"],s:"S = ρ_fluido·g·V_immerso."},
{t:"u3c",k:"m",q:"In un tubo percorso da un fluido ideale la sezione si dimezza. La velocità del fluido:",o:["si dimezza","raddoppia","quadruplica","resta invariata","diventa un quarto"],a:1,s:"A₁v₁ = A₂v₂: sezione metà → velocità doppia."},
{t:"u3c",k:"m",q:"L'equazione di continuità esprime la conservazione:",o:["dell'energia","della massa (portata costante)","della quantità di moto","della pressione","della temperatura"],a:1,s:"Per un fluido incomprimibile la portata Q = A·v resta costante."},
{t:"u3c",k:"m",q:"In un tubo orizzontale, nel tratto in cui il fluido scorre più velocemente, la pressione:",o:["aumenta","diminuisce","resta uguale","si annulla","raddoppia"],a:1,s:"Bernoulli: p + ½ρv² = costante; se v aumenta, p diminuisce."},
{t:"u3d",k:"m",q:"In regime laminare, se il raggio di un vaso si dimezza (a parità di Δp, lunghezza e viscosità), la portata diventa:",o:["la metà","un quarto","un ottavo","un sedicesimo","invariata"],a:3,s:"Poiseuille: Q ∝ r⁴ → (½)⁴ = 1/16."},
{t:"u3d",k:"c",q:"Il numero di Reynolds è una grandezza ____ .",a:["ADIMENSIONALE","ADIMENSIONATA","PURA"],s:"Re = ρvd/η non ha unità di misura."},
{t:"u3c",k:"m",q:"Una portata di 6 L/min espressa in m³/s vale:",o:["10⁻⁴ m³/s","10⁻³ m³/s","6·10⁻³ m³/s","0,1 m³/s","10⁻⁵ m³/s"],a:0,s:"6·10⁻³ m³ / 60 s = 10⁻⁴ m³/s."},
{t:"u3d",k:"m",q:"Il moto turbolento di un fluido è favorito da:",o:["bassa velocità","alta viscosità","un numero di Reynolds elevato","un tubo molto sottile","un fluido ideale"],a:2,s:"Re = ρvd/η alto (grande velocità e diametro, bassa viscosità) → turbolenza."},
{t:"u3a",k:"m",q:"In un torchio idraulico i pistoni hanno aree di 1 cm² e 50 cm². Una forza di 10 N sul pistone piccolo genera sul grande una forza di:",o:["0,2 N","10 N","50 N","500 N","5000 N"],a:3,s:"Pascal: F₂ = F₁·A₂/A₁ = 10·50 = 500 N."},
{t:"u3a",k:"m",q:"Una pressione arteriosa di 120 mmHg è una pressione:",o:["assoluta","relativa (rispetto alla pressione atmosferica)","espressa in pascal","negativa","dovuta solo alla gravità"],a:1,s:"In clinica si misura la sovrapressione rispetto all'atmosfera."},
{t:"u3a",k:"c",q:"L'unità di misura della pressione nel SI è il ____ .",a:["PASCAL","PA"],s:"1 Pa = 1 N/m²."},
{t:"u3b",k:"m",q:"Un corpo immerso completamente in un liquido galleggia (risale) se la sua densità media è:",o:["maggiore di quella del liquido","minore di quella del liquido","uguale a 1000 kg/m³","nulla","doppia di quella del liquido"],a:1,s:"La spinta supera il peso quando ρ_corpo < ρ_liquido."},
{t:"u3d",k:"m",q:"Due vasi sanguigni sono collegati in serie. La loro resistenza idrodinamica totale:",o:["è la somma delle due","si calcola con la somma degli inversi","è il prodotto delle due","è la media","è uguale alla minore"],a:0,s:"In serie le resistenze idrodinamiche si sommano (come quelle elettriche)."},
{t:"u3d",k:"m",q:"La viscosità del sangue, rispetto a quella dell'acqua, è:",o:["minore","uguale","maggiore","nulla","negativa"],a:2,s:"Il sangue è circa 3–4 volte più viscoso dell'acqua."},
{t:"u3a",k:"m",q:"In un liquido in quiete, due punti alla stessa profondità hanno:",o:["pressioni diverse","la stessa pressione","pressione che dipende dalla forma del recipiente","pressione nulla","pressione doppia"],a:1,s:"Stevino: p dipende solo dalla profondità (paradosso idrostatico)."},
{t:"u3b",k:"m",q:"Un corpo di volume 2 dm³ è completamente immerso in acqua. La spinta di Archimede vale circa (g = 10 m/s²):",o:["2 N","20 N","200 N","0,2 N","2000 N"],a:1,s:"S = 1000·10·2·10⁻³ = 20 N."},
{t:"u3c",k:"m",q:"Perché il sangue scorre più lentamente nei capillari che nell'aorta?",o:["perché i capillari sono più lunghi","perché la sezione complessiva dei capillari è molto maggiore","perché la pressione nei capillari è più alta","perché il sangue è meno viscoso","perché la portata nei capillari è minore"],a:1,s:"Q = A_tot·v: la portata è la stessa, la sezione totale dei capillari è enorme → v piccola."},
/* U4 */
{t:"u4a",k:"m",q:"Un suono di frequenza 170 Hz si propaga in aria a 340 m/s. La sua lunghezza d'onda è:",o:["0,5 m","2 m","57 800 m","510 m","170 m"],a:1,s:"λ = v/f = 340/170 = 2 m."},
{t:"u4a",k:"m",q:"Il periodo di un'onda di frequenza 50 Hz è:",o:["0,02 s","50 s","0,2 s","2 s","0,5 s"],a:0,s:"T = 1/f = 1/50 = 0,02 s."},
{t:"u4a",k:"c",q:"Il suono non può propagarsi nel ____ .",a:["VUOTO"],s:"Le onde meccaniche richiedono un mezzo materiale."},
{t:"u4b",k:"m",q:"Se l'intensità di un suono aumenta di 10 volte, il livello sonoro:",o:["aumenta di 1 dB","aumenta di 10 dB","si moltiplica per 10","aumenta di 20 dB","aumenta di 3 dB"],a:1,s:"β = 10·log(I/I₀): ×10 → +10 dB."},
{t:"u4b",k:"m",q:"Un livello sonoro di 0 dB corrisponde a:",o:["assenza di suono","la soglia di udibilità","un'intensità di 1 W/m²","la soglia del dolore","un livello di 10 dB"],a:1,s:"0 dB ↔ I = I₀ = 10⁻¹² W/m², il suono più debole udibile."},
{t:"u4b",k:"m",q:"L'intensità di un'onda è proporzionale:",o:["all'ampiezza","al quadrato dell'ampiezza","alla radice dell'ampiezza","all'inverso dell'ampiezza","non dipende dall'ampiezza"],a:1,s:"I ∝ A² (e ∝ f² a parità di ampiezza)."},
{t:"u4a",k:"m",q:"Un'onda sonora che si propaga nell'aria è:",o:["trasversale","longitudinale","elettromagnetica","sempre stazionaria","priva di energia"],a:1,s:"Le particelle d'aria oscillano nella stessa direzione di propagazione."},
{t:"u4b",k:"m",q:"Gli ultrasuoni usati in ecografia hanno frequenze:",o:["inferiori a 20 Hz","tra 20 Hz e 20 kHz","superiori a 20 kHz","uguali a 340 Hz","che si propagano solo nel vuoto"],a:2,s:"Oltre il limite dell'udito umano; in ecografia si usano MHz."},
{t:"u4c",k:"m",q:"Una sorgente sonora si avvicina a un osservatore fermo. La frequenza percepita è:",o:["maggiore di quella emessa","minore di quella emessa","uguale","nulla","dipendente dall'ampiezza"],a:0,s:"Effetto Doppler: avvicinamento → frequenza percepita più alta."},
{t:"u4a",k:"c",q:"La distanza tra due creste consecutive di un'onda si chiama lunghezza d'____ .",a:["ONDA"],s:"È λ; v = λ·f."},
{t:"u4b",k:"m",q:"Passando da 60 dB a 80 dB, l'intensità sonora:",o:["raddoppia","aumenta di 20 volte","aumenta di 100 volte","aumenta di 10 volte","aumenta del 20%"],a:2,s:"+20 dB = ×10² = ×100."},
{t:"u4b",k:"m",q:"L'intensità del suono di una sorgente puntiforme, a distanza r, varia come:",o:["1/r","1/r²","r","r²","non varia"],a:1,s:"La potenza si distribuisce su una sfera di area 4πr²."},
{t:"u4a",k:"m",q:"Quando un suono passa dall'aria all'acqua, la sua frequenza:",o:["aumenta","diminuisce","resta uguale","si annulla","raddoppia"],a:2,s:"La frequenza dipende dalla sorgente; cambiano velocità e λ."},
{t:"u4b",k:"m",q:"A parità di ampiezza, se la frequenza di un'onda raddoppia, la potenza trasportata:",o:["raddoppia","quadruplica","si dimezza","resta uguale","diventa otto volte"],a:1,s:"P ∝ f²·A²: 2² = 4."},
{t:"u4c",k:"m",q:"L'ecodoppler permette di misurare:",o:["la temperatura del sangue","la velocità del sangue","la pressione osmotica","la viscosità dei tessuti","la carica elettrica del cuore"],a:1,s:"Lo spostamento di frequenza degli ultrasuoni riflessi dai globuli rossi dipende dalla loro velocità."},
/* U5 */
{t:"u5a",k:"m",q:"Una temperatura di 27 °C corrisponde a:",o:["27 K","246 K","300 K","327 K","−246 K"],a:2,s:"27 + 273 = 300 K."},
{t:"u5a",k:"m",q:"Quanto calore serve per scaldare 2 kg d'acqua di 10 °C? (c ≈ 4186 J/(kg·K))",o:["8,4 kJ","84 kJ","840 J","4,2 kJ","840 kJ"],a:1,s:"Q = c·m·ΔT = 4186·2·10 ≈ 84 000 J."},
{t:"u5b",k:"m",q:"Un gas perfetto a temperatura costante viene compresso fino a metà del volume. La pressione:",o:["si dimezza","raddoppia","quadruplica","resta invariata","diventa un quarto"],a:1,s:"Boyle: pV = costante."},
{t:"u5c",k:"m",q:"In una trasformazione isocora il lavoro compiuto dal gas è:",o:["massimo","nullo","pari a pΔV positivo","uguale all'energia interna","infinito"],a:1,s:"Volume costante → ΔV = 0 → L = 0, quindi ΔU = Q."},
{t:"u5c",k:"c",q:"Primo principio della termodinamica: ΔU = Q − ____ (una lettera o una parola).",a:["L","LAVORO","W"],s:"ΔU = Q − L, con L lavoro compiuto dal sistema."},
{t:"u5c",k:"m",q:"Un gas si espande a pressione costante di 10⁵ Pa aumentando il volume di 2 L. Il lavoro compiuto è:",o:["200 J","2·10⁵ J","20 J","2000 J","0,2 J"],a:0,s:"L = p·ΔV = 10⁵ · 2·10⁻³ = 200 J."},
{t:"u5d",k:"m",q:"Il rendimento massimo di una macchina termica che lavora tra 600 K e 300 K è:",o:["25%","50%","75%","100%","33%"],a:1,s:"η = 1 − 300/600 = 0,5."},
{t:"u5d",k:"m",q:"In una trasformazione irreversibile di un sistema isolato, l'entropia:",o:["diminuisce","aumenta","resta costante","si annulla","oscilla"],a:1,s:"Secondo principio: in un sistema isolato l'entropia non diminuisce mai; nelle irreversibili cresce."},
{t:"u5a",k:"c",q:"Il calore assorbito durante un passaggio di stato, a temperatura costante, si chiama calore ____ .",a:["LATENTE"],s:"Q = λ·m; ad es. fusione del ghiaccio 334 kJ/kg."},
{t:"u5e",k:"m",q:"Quale modalità di trasmissione del calore avviene anche nel vuoto?",o:["conduzione","convezione","irraggiamento","evaporazione","diffusione"],a:2,s:"L'irraggiamento avviene tramite onde elettromagnetiche."},
{t:"u5b",k:"m",q:"L'energia interna di un gas perfetto dipende solo da:",o:["pressione","volume","temperatura","densità","forma del recipiente"],a:2,s:"ΔU = n·c_v·ΔT."},
{t:"u5c",k:"m",q:"In una trasformazione adiabatica:",o:["Q = 0","L = 0","ΔU = 0","la temperatura resta costante","la pressione resta costante"],a:0,s:"Adiabatica = senza scambio di calore: ΔU = −L."},
{t:"u5c",k:"m",q:"In una trasformazione ciclica la variazione di energia interna è:",o:["uguale a Q","uguale a L","nulla","uguale a Q + L","non determinabile"],a:2,s:"L'energia interna è funzione di stato: il ciclo torna allo stato iniziale."},
{t:"u5a",k:"m",q:"Mentre l'acqua bolle a pressione costante, la sua temperatura:",o:["aumenta","diminuisce","resta costante","oscilla","raddoppia"],a:2,s:"Il calore fornito serve al passaggio di stato (calore latente)."},
{t:"u5a",k:"m",q:"La capacità termica di un corpo è:",o:["c·m","c/m","m/c","Q·ΔT","uguale al calore specifico"],a:0,s:"C = c·m (J/K): calore per alzare di 1 K l'intero corpo."},
{t:"u5b",k:"m",q:"In condizioni normali (0 °C, 1 atm) una mole di gas perfetto occupa circa:",o:["1 L","11,2 L","22,4 L","24 m³","2,24 L"],a:2,s:"V = nRT/p ≈ 22,4 L."},
{t:"u5d",k:"m",q:"Secondo l'enunciato di Kelvin del secondo principio è impossibile:",o:["trasformare lavoro in calore","trasformare integralmente in lavoro il calore preso da una sola sorgente in un ciclo","scaldare un gas","comprimere un gas","raffreddare un corpo"],a:1,s:"Nessuna macchina ciclica ha rendimento 100%."},
{t:"u5b",k:"m",q:"Un gas a volume costante passa da 27 °C a 327 °C. La sua pressione:",o:["resta uguale","raddoppia","aumenta di 12 volte","si dimezza","aumenta del 300%"],a:1,s:"p/T costante: da 300 K a 600 K la pressione raddoppia (le temperature in kelvin!)."},
{t:"u5c",k:"m",q:"In un'espansione isoterma di un gas perfetto:",o:["Q = 0","ΔU = 0 e Q = L","L = 0","ΔU = Q","la pressione aumenta"],a:1,s:"T costante → ΔU = 0 → il calore assorbito diventa tutto lavoro."},
/* U6 */
{t:"u6a",k:"m",q:"Se la distanza tra due cariche raddoppia, la forza di Coulomb:",o:["si dimezza","diventa un quarto","raddoppia","quadruplica","resta invariata"],a:1,s:"F ∝ 1/r²."},
{t:"u6b",k:"m",q:"Le linee del campo elettrico generato da una carica puntiforme positiva sono:",o:["radiali entranti","radiali uscenti","circonferenze","parallele","linee chiuse"],a:1,s:"Escono dalle cariche positive, entrano in quelle negative."},
{t:"u6b",k:"m",q:"Le superfici equipotenziali di una carica puntiforme sono:",o:["piani","sfere concentriche","cilindri","semirette radiali","spirali"],a:1,s:"V = kQ/r dipende solo da r."},
{t:"u6b",k:"m",q:"Un elettrone viene accelerato da una differenza di potenziale di 100 V. L'energia cinetica acquistata è:",o:["100 eV","1 eV","100 J","1,6·10⁻¹⁹ J","zero"],a:0,s:"ΔE = q·ΔV = e·100 V = 100 eV (= 1,6·10⁻¹⁷ J)."},
{t:"u6c",k:"c",q:"Tra le armature di un condensatore piano ideale il campo elettrico è ____ .",a:["UNIFORME","COSTANTE"],s:"E = V/d, stesso valore e direzione in ogni punto."},
{t:"u6c",k:"m",q:"Un condensatore da 2 µF è collegato a 10 V. La carica sulle armature è:",o:["20 µC","5 µC","0,2 µC","20 C","200 µC"],a:0,s:"Q = C·V = 2 µF·10 V = 20 µC."},
{t:"u6d",k:"m",q:"Ai capi di una resistenza di 10 Ω c'è una tensione di 5 V. La corrente è:",o:["50 A","2 A","0,5 A","15 A","5 A"],a:2,s:"I = V/R = 5/10 = 0,5 A."},
{t:"u6d",k:"m",q:"Due resistenze da 6 Ω collegate in parallelo equivalgono a:",o:["12 Ω","6 Ω","3 Ω","36 Ω","1 Ω"],a:2,s:"Due resistenze uguali in parallelo: R/2."},
{t:"u6d",k:"m",q:"Due resistenze da 2 Ω e 3 Ω collegate in serie equivalgono a:",o:["1,2 Ω","5 Ω","6 Ω","0,83 Ω","1 Ω"],a:1,s:"In serie si sommano."},
{t:"u6d",k:"m",q:"Una resistenza di 4 Ω è percorsa da 2 A. La potenza dissipata è:",o:["8 W","16 W","2 W","32 W","0,5 W"],a:1,s:"P = R·I² = 4·4 = 16 W."},
{t:"u6c",k:"c",q:"L'unità di misura della capacità elettrica è il ____ .",a:["FARAD","F"],s:"1 F = 1 C/V."},
{t:"u6e",k:"m",q:"Le linee del campo magnetico sono:",o:["aperte","sempre chiuse","uscenti dal polo sud","radiali","sempre parallele"],a:1,s:"Non esistono monopoli magnetici: le linee si chiudono su se stesse."},
{t:"u6e",k:"m",q:"Una carica ferma in un campo magnetico costante subisce una forza:",o:["massima","nulla","pari a qvB","parallela a B","dipendente dalla massa"],a:1,s:"F = qvB sin θ: con v = 0 la forza è nulla."},
{t:"u6e",k:"m",q:"La forza di Lorentz su una carica in moto è:",o:["parallela alla velocità","perpendicolare sia a v sia a B","parallela a B","sempre nulla","opposta alla velocità"],a:1,s:"Per questo non compie lavoro e curva la traiettoria."},
{t:"u6e",k:"m",q:"Secondo la legge di Faraday-Neumann-Lenz, la f.e.m. indotta in un circuito dipende:",o:["dal valore del flusso magnetico","dalla variazione del flusso nel tempo","dalla carica del circuito","solo dalla resistenza","dalla massa del circuito"],a:1,s:"f.e.m. = −ΔΦ/Δt."},
{t:"u6b",k:"m",q:"Il lavoro del campo elettrico per spostare una carica lungo una superficie equipotenziale è:",o:["massimo","nullo","pari a q·E","sempre negativo","infinito"],a:1,s:"L = q·ΔV e ΔV = 0."},
{t:"u6a",k:"m",q:"All'interno di un conduttore carico in equilibrio elettrostatico il campo elettrico è:",o:["massimo","nullo","uniforme e diverso da zero","radiale","uguale a quello esterno"],a:1,s:"Le cariche si dispongono sulla superficie e il campo interno si annulla."},
{t:"u6b",k:"c",q:"L'unità di misura del potenziale elettrico è il ____ .",a:["VOLT","V"],s:"1 V = 1 J/C."},
{t:"u6c",k:"m",q:"L'energia immagazzinata in un condensatore di capacità C carico alla tensione V è:",o:["½CV²","CV","C/V","QV²","2CV"],a:0,s:"U = ½CV² = ½QV."},
{t:"u6b",k:"m",q:"Tra due armature distanti 2 mm c'è una differenza di potenziale di 10 V. Il campo elettrico vale:",o:["5 V/m","20 V/m","5000 V/m","0,2 V/m","500 V/m"],a:2,s:"E = V/d = 10 / 0,002 = 5000 V/m."},
/* U7 */
{t:"u7a",k:"m",q:"La velocità della luce nel vuoto è circa:",o:["3·10⁵ m/s","3·10⁸ m/s","340 m/s","3·10¹⁰ m/s","1,5·10⁸ m/s"],a:1,s:"c ≈ 300 000 km/s = 3·10⁸ m/s."},
{t:"u7a",k:"m",q:"L'energia di un fotone di frequenza f è:",o:["h·f","h/f","f/h","h·λ","m·c"],a:0,s:"E = h·f = h·c/λ."},
{t:"u7a",k:"m",q:"Quale di queste radiazioni ha la frequenza più alta?",o:["onde radio","infrarosso","luce visibile","raggi X","microonde"],a:3,s:"Ordine crescente: radio, microonde, IR, visibile, UV, X, γ."},
{t:"u7b",k:"m",q:"In un vetro con indice di rifrazione 1,5 la luce viaggia a:",o:["4,5·10⁸ m/s","2·10⁸ m/s","3·10⁸ m/s","1,5·10⁸ m/s","10⁸ m/s"],a:1,s:"v = c/n = 3·10⁸/1,5 = 2·10⁸ m/s."},
{t:"u7b",k:"m",q:"Un raggio di luce passa dall'aria al vetro. Il raggio rifratto:",o:["si allontana dalla normale","si avvicina alla normale","non devia","viene sempre riflesso","si ferma"],a:1,s:"Mezzo più rifrangente: n₁ sin θ₁ = n₂ sin θ₂ con n₂ > n₁ → θ₂ < θ₁."},
{t:"u7b",k:"c",q:"Le fibre ottiche funzionano grazie alla riflessione ____ .",a:["TOTALE"],s:"La luce resta intrappolata nel nucleo più rifrangente."},
{t:"u7b",k:"m",q:"La riflessione totale può avvenire quando la luce passa:",o:["da un mezzo meno rifrangente a uno più rifrangente","da un mezzo più rifrangente a uno meno rifrangente, oltre l'angolo limite","sempre, a qualunque angolo","solo nel vuoto","solo su uno specchio"],a:1,s:"sin θ_L = n₂/n₁ esiste solo se n₁ > n₂."},
{t:"u7b",k:"m",q:"Un raggio attraversa una lastra di vetro a facce parallele. Il raggio uscente è:",o:["deviato di 90°","parallelo a quello entrante, ma traslato","riflesso all'indietro","completamente assorbito","convergente"],a:1,s:"Le due rifrazioni si compensano: stessa direzione, spostamento laterale."},
{t:"u7c",k:"m",q:"Una lente ha distanza focale 0,5 m. Il suo potere diottrico è:",o:["0,5 D","2 D","5 D","50 D","−2 D"],a:1,s:"D = 1/f = 1/0,5 = 2 diottrie."},
{t:"u7d",k:"m",q:"Secondo la legge di Lambert-Beer, l'intensità della luce trasmessa da una soluzione diminuisce con lo spessore in modo:",o:["lineare","esponenziale","quadratico","nessuna variazione","logaritmico crescente"],a:1,s:"I = I₀·e^(−µx), cioè A = εcl cresce linearmente."},
{t:"u7e",k:"c",q:"Il tempo dopo cui metà dei nuclei radioattivi è decaduta si chiama tempo di dimezzamento o ____ .",a:["EMIVITA"],s:"T½ = ln2/λ."},
{t:"u7e",k:"m",q:"Dopo 3 tempi di dimezzamento, la frazione di nuclei non ancora decaduti è:",o:["1/3","1/6","1/8","1/9","zero"],a:2,s:"(½)³ = 1/8."},
{t:"u7e",k:"m",q:"L'unità di misura dell'attività di una sorgente radioattiva è il:",o:["gray","becquerel","sievert","joule","watt"],a:1,s:"1 Bq = 1 decadimento al secondo. Gray e sievert sono dosi."},
{t:"u7e",k:"m",q:"La radiazione α è costituita da:",o:["elettroni","nuclei di elio","fotoni","neutroni","protoni singoli"],a:1,s:"2 protoni + 2 neutroni; è la meno penetrante."},
{t:"u7e",k:"m",q:"Quale radiazione è la più penetrante?",o:["α","β","γ","sono tutte uguali","nessuna penetra la materia"],a:2,s:"I fotoni γ non hanno carica: servono spessori di piombo o cemento."},
{t:"u7d",k:"m",q:"Una soluzione ha assorbanza A = 1. La frazione di luce trasmessa è:",o:["10%","1%","90%","50%","37%"],a:0,s:"T = 10^(−A) = 10⁻¹ = 10%."},
{t:"u7c",k:"m",q:"Un oggetto è posto oltre il doppio della distanza focale di una lente convergente. L'immagine è:",o:["virtuale e ingrandita","reale, capovolta e rimpicciolita","diritta e uguale","non si forma","reale e ingrandita"],a:1,s:"p > 2f → f < q < 2f: immagine reale, capovolta, più piccola."},
{t:"u7a",k:"c",q:"La luce visibile ha lunghezze d'onda tra circa 400 e 700 ____ (unità, per esteso o simbolo).",a:["NM","NANOMETRI","NANOMETRO"],s:"400 nm (violetto) – 700 nm (rosso)."},
{t:"u7e",k:"m",q:"Una sorgente ha attività 800 Bq. Dopo due tempi di dimezzamento la sua attività è:",o:["400 Bq","200 Bq","100 Bq","600 Bq","0 Bq"],a:1,s:"800 → 400 → 200 Bq."},
{t:"u7d",k:"m",q:"Raddoppiando la concentrazione di una soluzione (stesso spessore), l'assorbanza:",o:["si dimezza","raddoppia","quadruplica","resta uguale","si annulla"],a:1,s:"A = ε·c·l è proporzionale a c."},
{t:"u7c",k:"m",q:"Un oggetto posto tra il fuoco e una lente convergente dà un'immagine:",o:["reale e capovolta","virtuale, diritta e ingrandita","reale e rimpicciolita","virtuale e capovolta","nessuna immagine"],a:1,s:"È la lente d'ingrandimento."},
{t:"u1c",k:"m",q:"Quanto vale sin 30°?",o:["0","0,5","√3/2","1","2"],a:1,s:"sin 30° = 0,5 = cos 60°."},
{t:"u1a",k:"m",q:"Quale di queste grandezze è intensiva (non dipende dalla quantità di materia)?",o:["massa","volume","temperatura","energia interna","quantità di sostanza"],a:2,s:"Dividendo un corpo a metà la temperatura resta uguale; massa, volume ed energia si dimezzano."},
{t:"u2c",k:"m",q:"Se la distanza tra due masse raddoppia, la forza di attrazione gravitazionale:",o:["si dimezza","diventa un quarto","raddoppia","quadruplica","resta uguale"],a:1,s:"F = Gm₁m₂/r²."},
{t:"u2e",k:"m",q:"Una forza di 20 N agisce con un braccio di 0,3 m. Il momento torcente è:",o:["6 N·m","60 N·m","0,015 N·m","66,7 N·m","20,3 N·m"],a:0,s:"M = F·b = 20·0,3 = 6 N·m."},
{t:"u2f",k:"m",q:"La quantità di moto di un corpo di 3 kg che si muove a 4 m/s è:",o:["7 kg·m/s","12 kg·m/s","0,75 kg·m/s","24 kg·m/s","48 kg·m/s"],a:1,s:"p = m·v = 3·4 = 12 kg·m/s."},
{t:"u2f",k:"m",q:"Un carrello di 2 kg a 3 m/s urta un carrello fermo di 1 kg e i due restano attaccati. La velocità dopo l'urto è:",o:["1 m/s","1,5 m/s","2 m/s","3 m/s","6 m/s"],a:2,s:"Conservazione di p: 2·3 = (2+1)·v → v = 2 m/s."},
{t:"u2f",k:"m",q:"In un urto anelastico tra due corpi (sistema isolato) si conserva:",o:["solo l'energia cinetica","la quantità di moto totale","né quantità di moto né energia","la velocità di ciascun corpo","l'energia cinetica di ciascun corpo"],a:1,s:"La quantità di moto si conserva sempre in un sistema isolato; l'energia cinetica no."},
{t:"u2f",k:"m",q:"Una forza costante di 10 N agisce per 0,5 s. L'impulso è:",o:["20 N·s","5 N·s","10,5 N·s","0,05 N·s","50 N·s"],a:1,s:"J = F·Δt = 10·0,5 = 5 N·s, pari alla variazione di quantità di moto."},
{t:"u2f",k:"c",q:"L'impulso di una forza è uguale alla variazione della quantità di ____ .",a:["MOTO"],s:"J = Δp."},
{t:"u3a",k:"m",q:"Nell'esperimento di Torricelli la pressione atmosferica sostiene una colonna di mercurio alta circa:",o:["76 mm","760 mm","10 m","1 m","7,6 mm"],a:1,s:"1 atm = 760 mmHg."},
{t:"u4d",k:"m",q:"Se la massa appesa a una molla quadruplica, il periodo di oscillazione:",o:["raddoppia","quadruplica","si dimezza","resta uguale","diventa un quarto"],a:0,s:"T = 2π√(m/k): √4 = 2."},
{t:"u4d",k:"m",q:"Due onde uguali e in fase si sovrappongono. L'ampiezza risultante è:",o:["nulla","doppia","uguale","la metà","quadrupla"],a:1,s:"Interferenza costruttiva: le ampiezze si sommano."},
{t:"u4d",k:"m",q:"Tra due onde uguali si ha interferenza distruttiva quando la differenza di cammino è:",o:["un multiplo intero di λ","un multiplo dispari di λ/2","zero","sempre λ/4","qualsiasi"],a:1,s:"Δ = λ/2, 3λ/2…: le onde arrivano in opposizione di fase."},
{t:"u4d",k:"c",q:"La pulsazione ω è uguale a 2π moltiplicato per la ____ .",a:["FREQUENZA","F"],s:"ω = 2πf = 2π/T."},
{t:"u5a",k:"m",q:"Si mescolano 1 kg d'acqua a 20 °C e 1 kg d'acqua a 60 °C, senza perdite. La temperatura finale è:",o:["30 °C","40 °C","50 °C","80 °C","20 °C"],a:1,s:"Masse e calori specifici uguali: media delle temperature, (20+60)/2 = 40 °C."},
{t:"u5c",k:"m",q:"Una trasformazione reversibile è:",o:["sempre molto rapida","una successione di stati di equilibrio, percorribile anche al contrario","impossibile da rappresentare nel piano p–V","sempre adiabatica","una trasformazione che fa aumentare l'entropia dell'universo"],a:1,s:"Le reversibili sono ideali e lente; quelle reali sono irreversibili."},
{t:"u6b",k:"m",q:"Un protone inizialmente fermo è posto in un campo elettrico uniforme. Il protone:",o:["resta fermo","accelera nel verso del campo con a = qE/m","si muove su una circonferenza","accelera in verso opposto al campo","si muove a velocità costante"],a:1,s:"F = qE costante e concorde con E per una carica positiva."},
{t:"u6a",k:"m",q:"Avvicinando (senza toccare) una bacchetta carica a un conduttore isolato si ottiene:",o:["elettrizzazione per strofinio","induzione elettrostatica, cioè separazione di cariche nel conduttore","una corrente continua","magnetizzazione","nessun effetto"],a:1,s:"Le cariche libere del conduttore si ridistribuiscono."},
{t:"u6c",k:"m",q:"Due condensatori da 4 µF collegati in parallelo equivalgono a:",o:["2 µF","4 µF","8 µF","16 µF","1 µF"],a:2,s:"In parallelo le capacità si sommano."},
{t:"u6c",k:"m",q:"Inserendo un dielettrico con εᵣ = 3 tra le armature di un condensatore, la capacità:",o:["si dimezza","triplica","resta uguale","diventa un terzo","si annulla"],a:1,s:"C = ε₀εᵣA/d."},
{t:"u6e",k:"m",q:"L'esperimento di Oersted dimostra che:",o:["le cariche opposte si attraggono","una corrente elettrica genera un campo magnetico","la luce è un'onda","la carica si conserva","i magneti si smagnetizzano col calore"],a:1,s:"Un filo percorso da corrente devia l'ago di una bussola."},
{t:"u6e",k:"m",q:"Un filo lungo 0,5 m, percorso da 2 A, è perpendicolare a un campo B = 0,1 T. La forza sul filo è:",o:["0,1 N","1 N","0,01 N","10 N","0,25 N"],a:0,s:"F = I·l·B = 2·0,5·0,1 = 0,1 N."},
{t:"u6e",k:"c",q:"Il verso della corrente indotta si oppone alla variazione di flusso che la genera: è la legge di ____ .",a:["LENZ"],s:"Faraday-Neumann-Lenz: f.e.m. = −ΔΦ/Δt (il segno meno è Lenz)."},
{t:"u7e",k:"m",q:"Nel decadimento α il nucleo:",o:["mantiene A e aumenta Z di 1","perde 4 unità di massa (A − 4) e 2 di numero atomico (Z − 2)","aumenta A di 4","non cambia","perde solo un neutrone"],a:1,s:"Emette un nucleo di elio ⁴₂He."},
{t:"u7e",k:"m",q:"Nel decadimento β⁻ il numero atomico Z:",o:["diminuisce di 1","aumenta di 1","diminuisce di 2","resta uguale","aumenta di 4"],a:1,s:"Un neutrone diventa un protone emettendo un elettrone; A non cambia."},
{t:"u7a",k:"m",q:"Quale di queste è una radiazione ionizzante?",o:["onde radio","microonde","infrarosso","raggi X","luce rossa"],a:3,s:"I fotoni X hanno energia (keV) molto superiore a quella di ionizzazione degli atomi."},
{t:"u7e",k:"c",q:"Atomi dello stesso elemento con diverso numero di neutroni si chiamano ____ .",a:["ISOTOPI"],s:"Stesso Z, diverso A."},
{t:"u7a",k:"m",q:"In un'onda elettromagnetica i campi elettrico e magnetico sono:",o:["paralleli tra loro","perpendicolari tra loro e alla direzione di propagazione","entrambi nulli","paralleli alla direzione di propagazione","solo elettrici"],a:1,s:"È un'onda trasversale; è uscito al 1° appello 2025."},
{t:"u7c",k:"m",q:"Con una lente convergente, un oggetto posto tra f e 2f dà un'immagine:",o:["virtuale","reale, capovolta e ingrandita","reale e rimpicciolita","diritta","nessuna immagine"],a:1,s:"È il caso del proiettore; è uscito al 1° appello 2025."},
/* ---- tipo 2025: stessi argomenti degli appelli 2025, numeri diversi ---- */
{t:"u1c",k:"m",q:"Una nave percorre 8 km verso nord, 6 km verso est e 16 km verso sud. Il modulo dello spostamento risultante è:",o:["30 km","10 km","14 km","2 km","22 km"],a:1,s:"Nord-sud: 8 − 16 = 8 km a sud; est 6 km. √(8² + 6²) = 10 km (tipo 2025)."},
{t:"u1b",k:"c",q:"Un'accelerazione di 250 cm/s² vale ____ m/s².",a:["2.5","2,5"],s:"Si divide per 100 (tipo 2025)."},
{t:"u1b",k:"c",q:"Una concentrazione di 3 µg/mm³ equivale a ____ g per litro.",a:["3","TRE"],s:"1 mm³ = 10⁻⁶ L e 1 µg = 10⁻⁶ g: 3·10⁻⁶ g / 10⁻⁶ L = 3 g/L (tipo 2025)."},
{t:"u1b",k:"c",q:"1 Pa = 10^x nPa: l'esponente x vale ____.",a:["9","NOVE"],s:"1 nPa = 10⁻⁹ Pa (tipo 2025)."},
{t:"u2a",k:"c",q:"Un sasso cade da fermo da 20 m. A che altezza dal suolo (in m) la sua velocità è metà di quella con cui arriva a terra? ____",a:["15","QUINDICI"],s:"v² ∝ spazio percorso: metà velocità dopo 1/4 della caduta, cioè 5 m; altezza 20 − 5 = 15 m (tipo 2025)."},
{t:"u2f",k:"c",q:"Una pallina di 10 g a 3 m/s urta una pallina ferma di 20 g e restano attaccate. La velocità finale è ____ m/s.",a:["1","UNO"],s:"0,01·3 = 0,03·v → v = 1 m/s (tipo 2025)."},
{t:"u3a",k:"c",q:"Pressione relativa (manometrica) sul fondo di una vasca d'acqua profonda 3 m, con g = 10 m/s²: ____ Pa.",a:["30000","3*10^4","3·10⁴"],s:"ρgh = 1000·10·3 (tipo 2025)."},
{t:"u3b",k:"m",q:"Una zattera di legno (densità 0,6 g/cm³), quadrata di lato 2 m e spessa 50 cm, galleggia in acqua. Di quanto è immersa?",o:["20 cm","30 cm","40 cm","50 cm","10 cm"],a:1,s:"Frazione immersa = 0,6/1 = 60% di 50 cm (tipo 2025)."},
{t:"u3b",k:"m",q:"Sulla stessa zattera (lato 2 m, spessore 50 cm, legno 600 kg/m³) si carica una massa di 400 kg. L'altezza immersa diventa:",o:["30 cm","35 cm","40 cm","45 cm","50 cm"],a:2,s:"Massa totale 1200 + 400 = 1600 kg → volume immerso 1,6 m³ → 1,6/4 m² = 0,4 m (tipo 2025)."},
{t:"u3b",k:"c",q:"Carico massimo (in N, g = 10) che la zattera di lato 2 m, spessa 50 cm e di densità 600 kg/m³ può portare senza affondare: ____",a:["8000","8.000"],s:"Spinta massima 1000·2·10 = 20 000 N; peso zattera 12 000 N; restano 8000 N (tipo 2025)."},
{t:"u3c",k:"c",q:"In un condotto orizzontale scorrono 300 cm³/s d'acqua; la sezione passa da 1 cm² a 3 cm². La differenza di pressione tra le due sezioni è ____ Pa.",a:["4000","4.000"],s:"v = 3 m/s e 1 m/s; Δp = ½·1000·(9 − 1) = 4000 Pa (tipo 2025)."},
{t:"u4a",k:"m",q:"Un'onda sonora NON trasporta:",o:["energia","quantità di moto","massa","informazione","potenza"],a:2,s:"Le particelle oscillano attorno alla loro posizione (tipo 2025)."},
{t:"u4b",k:"m",q:"Se la frequenza di un'onda sonora raddoppia mantenendo la stessa ampiezza, la potenza trasportata:",o:["raddoppia","resta uguale","aumenta di un fattore 4","si dimezza","aumenta di un fattore 8"],a:2,s:"L'energia di un'onda è proporzionale a ω²A² (tipo 2025)."},
{t:"u4c",k:"c",q:"La sirena di un'ambulanza che si avvicina si sente il 3% più acuta. Con il suono a circa 1200 km/h, l'ambulanza va a circa ____ km/h.",a:["36","35"],s:"Per velocità piccole Δf/f ≈ v/v_suono: 0,03·1200 = 36 km/h (con la formula esatta circa 35) (tipo 2025)."},
{t:"u4d",k:"c",q:"Un pendolo reale smette di oscillare perché agiscono forze ____ (come l'attrito con l'aria).",a:["DISSIPATIVE","DISSIPATIVA","NONCONSERVATIVE"],s:"L'energia meccanica diventa calore (tipo 2025)."},
{t:"u5b",k:"m",q:"Se la temperatura assoluta di un gas perfetto triplica, l'energia cinetica media delle molecole:",o:["resta uguale","triplica","aumenta di 9 volte","aumenta di √3 volte","si riduce a un terzo"],a:1,s:"Ec media = (3/2)kT (tipo 2025)."},
{t:"u5b",k:"m",q:"Rispetto al gas perfetto, in un gas reale (approfondimento):",o:["le molecole non si urtano","il volume proprio delle molecole (covolume) non è trascurabile","la pressione è sempre nulla","la temperatura non conta","non esiste energia interna"],a:1,s:"Equazione di van der Waals: covolume e attrazioni tra molecole (tipo 2025)."},
{t:"u5c",k:"c",q:"In una trasformazione isocora il lavoro è nullo e la variazione di energia interna è uguale al ____ scambiato.",a:["CALORE"],s:"ΔU = Q (tipo 2025)."},
{t:"u6a",k:"m",q:"Un conduttore isolato porta una carica di 10 nC. La differenza di potenziale tra due suoi punti qualsiasi è:",o:["0 V","2 V","10 V","dipende dalla distanza tra i punti","infinita"],a:0,s:"Un conduttore in equilibrio è tutto allo stesso potenziale (tipo 2025)."},
{t:"u6b",k:"c",q:"Un elettrone accelerato da una d.d.p. di 2·10⁴ V acquista un'energia di ____ keV.",a:["20","VENTI"],s:"E = e·ΔV = 20 000 eV (tipo 2025)."},
{t:"u6d",k:"m",q:"A 230 V, una lavatrice da 2300 W assorbe una corrente di:",o:["0,1 A","1 A","10 A","100 A","23 A"],a:2,s:"I = P/V = 2300/230 (tipo 2025)."},
{t:"u6d",k:"c",q:"Due resistenze da 600 Ω in parallelo sono collegate in serie a una da 200 Ω. La resistenza equivalente è ____ Ω.",a:["500","CINQUECENTO"],s:"Parallelo 300 Ω + 200 Ω (tipo 2025)."},
{t:"u7a",k:"c",q:"In un'onda elettromagnetica il campo elettrico e il campo magnetico sono tra loro ____.",a:["PERPENDICOLARI","ORTOGONALI"],s:"E entrambi perpendicolari alla direzione di propagazione (tipo 2025)."},
{t:"u7a",k:"c",q:"L'energia di un fotone è direttamente proporzionale alla sua ____.",a:["FREQUENZA"],s:"E = h·f (tipo 2025)."},
{t:"u7c",k:"c",q:"Con una lente convergente, un oggetto posto tra il fuoco e il doppio della distanza focale dà un'immagine ____ e ingrandita (reale/virtuale).",a:["REALE"],s:"E capovolta (tipo 2025)."}
];


/* Test d'ingresso: 14 domande (2 per unità), livello scuola superiore */
const FIS_PT=[
{u:"u1",q:"Quanto vale 36 km/h in m/s?",o:["3,6","10","36","100","1"],a:1},
{u:"u1",q:"Quanto fa (3·10⁴) × (2·10⁻²)?",o:["6·10²","6·10⁻⁸","5·10²","6·10⁶","6"],a:0},
{u:"u2",q:"Un corpo cade liberamente (aria trascurabile). La sua accelerazione:",o:["aumenta","è costante, circa 9,8 m/s²","diminuisce","è zero","dipende dalla massa"],a:1},
{u:"u2",q:"Una forza di 10 N agisce su un corpo di 2 kg. L'accelerazione è:",o:["20 m/s²","5 m/s²","0,2 m/s²","12 m/s²","8 m/s²"],a:1},
{u:"u3",q:"La pressione è definita come:",o:["forza × area","forza / area","area / forza","massa × altezza","densità / volume"],a:1},
{u:"u3",q:"Un sasso affonda in acqua perché:",o:["la sua densità è maggiore di quella dell'acqua","la spinta di Archimede è nulla","ha una massa","è solido","l'acqua è incomprimibile"],a:0},
{u:"u4",q:"Quale relazione lega velocità, lunghezza d'onda e frequenza di un'onda?",o:["v = λ/f","v = λ·f","v = f/λ","v = λ + f","v = λ²·f"],a:1},
{u:"u4",q:"La frequenza si misura in:",o:["metri","secondi","hertz","decibel","watt"],a:2},
{u:"u5",q:"Lo zero assoluto (0 K) corrisponde a circa:",o:["0 °C","−273 °C","273 °C","−100 °C","100 °C"],a:1},
{u:"u5",q:"Per un gas perfetto a volume costante, se la temperatura assoluta raddoppia la pressione:",o:["si dimezza","raddoppia","resta uguale","quadruplica","si annulla"],a:1},
{u:"u6",q:"Due cariche elettriche dello stesso segno:",o:["si attraggono","si respingono","non interagiscono","si annullano","dipende dalla loro massa"],a:1},
{u:"u6",q:"La legge di Ohm si scrive:",o:["V = R·I","V = R/I","I = R·V","R = V·I","P = R·I"],a:0},
{u:"u7",q:"Un fascio di luce bianca attraversa un prisma di vetro. Che cosa succede?",o:["si spegne","si scompone nei colori","diventa tutta rossa","viene riflessa tutta","accelera"],a:1},
{u:"u7",q:"Nella riflessione, l'angolo di riflessione rispetto a quello di incidenza è:",o:["doppio","uguale","la metà","sempre 90°","zero"],a:1}
];
const SCHOOLS=["Liceo scientifico","Altro liceo","Istituto tecnico","Istituto professionale","Non ricordo / poca fisica"];

/* Storia e regole: fonti verificate al 10 ottobre 2026 */
const SRC={
 upo:"https://www.uniupo.it/it/infostudenti/modalit%C3%A0-di-accesso-medicina-e-chirurgia-aa-20262027",
 mur:"https://www.mur.gov.it/it/news/venerdi-19062026/semestre-aperto-aa-2026-2027",
 date:"https://www.orizzontescuola.it/semestre-filtro-medicina-2026-27-esami-il-10-dicembre-e-l11-gennaio-31-domande-per-materia/",
 tbsyl:"https://med.testbusters.it/hubfs/Semestre%20filtro%202026-27/TB%20_%20Analisi%20Syllabus%202026.pdf",
 tb2:"https://www.testbusters.it/blog/test-medicina/semestre-filtro-2025-correzione-commentata-test-secondo-appello",
 tbuddy:"https://testbuddy.it/blog/medicina/analisi-della-prova-di-fisica-del-semestre-filtro-2-sessione",
 tb1:"https://testbuddy.it/blog/medicina/commento-della-prima-prova-di-fisica-del-semestre-filtro",
 esiti:"https://www.studenti.it/test-di-medicina-del-20-novembre-risultati-disastrosi-e-allarme-fisica-cosa-sta-succedendo-e-cosa-cambia-ora.html",
 promossi:"https://www.ilgiorno.it/milano/cronaca/medicina-semestre-filtrio-fvlfut48",
 crui:"https://www.semestreaperto-medodovet.it/",
 prove:"https://futura.study/simulazioni-gratis/prove-ufficiali/test-medicina/2025",
 upoen:"https://www.uniupo.it/en/studentinfo/arrangements-access-medicine-and-surgery-ay-20262027",
 mood:"https://semestre-aperto.progetto-mood.com/",
 guida:"https://www.orizzontescuola.it/medicina-2026-2027-domani-al-via-il-semestre-filtro-la-guida-con-tutte-le-date-e-le-regole/",
 nov:"https://futura.study/blog/medicina/novita-semestre-filtro-2026-2027/",
 tar:"https://www.newsistruzione.it/2026/07/15/medicina-semestre-filtro-2026-chiarimenti-tar"
};
/* Tutte le fonti consultate (pagina «Fonti» e schede delle materie). m = materie a cui si riferisce: fis, chi, bio o tutte (*) */
const SOURCES=[
 {g:"📜 Documenti ufficiali",it:[
  ["MUR – Semestre aperto a.a. 2026/2027 (syllabus e comunicazioni)",SRC.mur,"*"],
  ["Syllabus ufficiale di Fisica 2026/27 (PDF)","https://www.mur.gov.it/sites/default/files/2026-06/Syllabus_FISICA_%20finale%202026.pdf","fis"],
  ["Syllabus ufficiale di Chimica e propedeutica biochimica 2026/27 (PDF)","https://www.mur.gov.it/sites/default/files/2026-06/Syllabus%20Chim.Prop_.Bioch_.%20-%20finale-%202026.pdf","chi"],
  ["Syllabus ufficiale di Biologia 2026/27 (PDF)","https://www.mur.gov.it/sites/default/files/2026-06/Syllabus_BIOLOGIA_%20finale%202026.pdf","bio"],
  ["UPO – Modalità di accesso a Medicina e Chirurgia 2026/27",SRC.upo,"*"],
  ["UPO – Arrangements for access to Medicine and Surgery 2026/27 (aggiornamenti al 28 settembre 2026)",SRC.upoen,"*"]]},
 {g:"🆓 Piattaforme gratuite per esercitarsi",it:[
  ["Semestre Aperto MedOdoVet (CRUI, MUR, CISIA): MOOC, esercizi per unità, simulazioni ufficiali da novembre",SRC.crui,"*"],
  ["Progetto MOOD – piattaforma di 44 atenei per il semestre aperto",SRC.mood,"*"]]},
 {g:"📅 Date, regole e novità 2026/27",it:[
  ["Orizzonte Scuola – Esami il 10 dicembre e l'11 gennaio, 31 domande per materia",SRC.date,"*"],
  ["Orizzonte Scuola – Guida con tutte le date e le regole (graduatoria, scorrimenti)",SRC.guida,"*"],
  ["Futura – Novità del semestre filtro 2026/27 (aggiornato al 30 settembre 2026)",SRC.nov,"*"],
  ["Futura – Semestre filtro 2026/27: bando, date, funzionamento","https://futura.study/blog/medicina/semestre-filtro-medicina-2026-come-funziona/","*"],
  ["TestBusters – Semestre filtro 2026: cosa cambia rispetto al 2025","https://www.testbusters.it/blog/test-medicina/semestre-filtro-2026-cosa-cambia","*"],
  ["News Istruzione – Il TAR del Lazio chiede chiarimenti al MUR (luglio 2026)",SRC.tar,"*"],
  ["Studenti.it – Simulatore e materiali gratuiti del MUR","https://www.studenti.it/simulatore-e-materiali-didattici-gratuiti-gli-strumenti-online-del-mur-a-supporto-delle-matricole.html","*"]]},
 {g:"🔍 Analisi dei syllabus 2026",it:[
  ["TestBusters – Analisi del syllabus 2026 e differenze con il 2025 (PDF)",SRC.tbsyl,"*"]]},
 {g:"📝 Prove 2025: testi, soluzioni e commenti",it:[
  ["Futura – Prove ufficiali 2025 (testi)",SRC.prove,"*"],
  ["Futura – Soluzioni del 2° appello: Chimica, Biologia, Fisica","https://futura.study/blog/medicina/soluzioni-secondo-appello-semestre-filtro-medicina/","*"],
  ["TestBusters – Correzione commentata del 1° appello","https://www.testbusters.it/blog/test-medicina/semestre-filtro-2025-correzione-commentata-test-primo-appello","*"],
  ["TestBusters – Correzione commentata del 2° appello",SRC.tb2,"*"],
  ["Skuola.net – Esami del 10 dicembre 2025: tutte le soluzioni","https://www.skuola.net/guide/test-ingresso/medicina-chirurgia/soluzioni-esami-medicina-10-dicembre-2025.html","*"],
  ["TestAmmissione – Domande del semestre filtro 2025","https://testammissione.com/domande-semestre-filtro-medicina-2025/","*"],
  ["TestAmmissione – Domande di Fisica 2025 (due appelli)","https://testammissione.com/domande-fisica-semestre-filtro-2025/","fis"],
  ["TestBuddy – Commento della prima prova di Fisica",SRC.tb1,"fis"],
  ["TestBuddy – Analisi della prova di Fisica, 2ª sessione",SRC.tbuddy,"fis"],
  ["PiTest – Chimica, 1° appello 2025 (domande commentate)","https://www.pitest.it/chimica/semestre-filtro-2025-primo-appello-chimica/","chi"],
  ["PiTest – Biologia, 1° appello 2025 (domande commentate)","https://www.pitest.it/biologia/semestre-filtro-2025-primo-appello-biologia/","bio"],
  ["PiTest – Biologia, 2° appello 2025 (domande commentate)","https://www.pitest.it/biologia/semestre-filtro-2025-secondo-appello-biologia/","bio"]]},
 {g:"📊 Risultati 2025",it:[
  ["Studenti.it – Risultati del 20 novembre 2025 e allarme Fisica",SRC.esiti,"*"],
  ["Il Giorno – Promossi sui due appelli",SRC.promossi,"*"]]}
];
